import test from 'node:test';import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.js';
import {installDOM} from './fixtures.mjs';import {createTown} from '../src/world/town.js';import {configureTownMode} from '../src/world/town-mode.js';
import {islandTerrainHeight,MOUNTAIN_VERTICES,TERRAIN_GRID,COAST_ROAD} from '../src/world/island-plan.js';import {GARDEN,gardenPoint,gardenPondAt} from '../src/world/garden-layout.js';import {routeAt,groundHeight} from '../src/world/layout.js';import {circleHitsRect} from '../physics.js';
import {AIRPORT_COUNTER,airportWorld,AIRPORT_HEIGHT} from '../src/world/airport-ground.js';
import {restoreIsland,islandState,buyFerry,ferryArrival,buyFlight,checkIn,boardFlight,flightArrival,finishRepair,completeProject,flightTimes} from '../src/island/services.js';
import {auditArchive,YEAR_MINUTES,retainArchive} from '../src/office/archive.js';

test('mountain triangles and grounded height share each vertex; existing town heights remain stable',()=>{try{configureTownMode('peninsula');const g=TERRAIN_GRID,n=Math.round((g.maxX-g.minX)/g.step)+1;for(let i=0;i<MOUNTAIN_VERTICES.length;i+=7)assert.ok(Math.abs(islandTerrainHeight(g.minX+i%n*g.step,g.minZ+Math.floor(i/n)*g.step)-MOUNTAIN_VERTICES[i])<1e-8);assert.ok(groundHeight(40,175)<1);assert.equal(groundHeight(0,-44),0);for(const [x,z] of COAST_ROAD)assert.ok(routeAt(x,z,.32),'road on land '+x+','+z);assert.equal(routeAt(400,400,.32),null);}finally{configureTownMode('legacy');}});

test('garden pond cannot be walked on; bridge, gate, loop and relocated bath approaches remain clear',()=>{try{installDOM();const world=createTown({scene:new THREE.Scene(),sites:[],townMode:'peninsula',mobile:true,shadows:false,register(){},enter(){},onAction(){}}),blocked=(x,z)=>!routeAt(x,z,.32)||world.colliders.some(c=>circleHitsRect(x,z,.32,c));assert.equal(gardenPondAt(...gardenPoint(-34,129)),true);assert.equal(blocked(...gardenPoint(-34,129)),true);for(const [a,b] of [[[-28,108],[-28,117]],[[-43,132],[-25,132]]])for(let t=0;t<=1;t+=.025){const [x,z]=gardenPoint(a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t);assert.equal(blocked(x,z),false,'garden passage '+x+','+z);}assert.equal(groundHeight(...gardenPoint(-34,132)),.1);assert.ok(world.landmarks.some(s=>s.id==='aoba-garden'));}finally{configureTownMode('legacy');}});

test('airport landing connects to passenger counter while the runway and sewage plant remain inaccessible',()=>{try{configureTownMode('peninsula');for(let z=18;z<=31;z+=.3){const p=airportWorld(-44,z);assert.ok(routeAt(...p,.32),'jetty access at '+z);}for(let x=-44;x<=-10;x+=.3){const p=airportWorld(x,18.5);assert.ok(routeAt(...p,.32),'passenger path '+x);}assert.ok(routeAt(...AIRPORT_COUNTER,.32));assert.ok(Math.abs(groundHeight(...AIRPORT_COUNTER)-AIRPORT_HEIGHT)<.001);assert.equal(routeAt(...airportWorld(0,-4),.32),null);assert.equal(routeAt(...airportWorld(-33,9),.32),null);}finally{configureTownMode('legacy');}});

test('ticket, check-in, missed flight, weather closure and return records survive restore without duplicate charges',()=>{const state={yen:1200};assert.equal(buyFerry(state,480).ok,true);assert.equal(buyFerry(state,481).already,true);ferryArrival(state,'airport',498);assert.equal(buyFlight(state,500).ok,true);assert.equal(state.yen,0);const ticket=islandState(state).journey.ticket;assert.equal(boardFlight(state,ticket).ok,false);assert.equal(checkIn(state,530).ok,true);assert.equal(boardFlight(state,540).wait,15);assert.equal(boardFlight(state,ticket,true).ok,false);assert.equal(boardFlight(state,ticket).ok,true);flightArrival(state,'naha',ticket+45);const restored={...state,island:restoreIsland(state.island)};assert.equal(restored.island.journey.location,'naha');flightArrival(restored,'airport',ticket+100);ferryArrival(restored,'town',ticket+118);assert.equal(restored.island.journey.roundTrip,false);assert.equal(restored.island.journey.ticket,null);assert.equal(restored.yen,0);assert.ok(restored.documentArchive.records.some(r=>r.title==='Commuter flight check-in'));const missed={yen:800};buyFlight(missed,500);checkIn(missed,552);assert.ok(missed.island.journey.ticket>555);assert.equal(missed.yen,0);});

test('town growth requires service evidence, spends treasury once, changes flights and produces a complete audit chain',()=>{const state={yen:1200};assert.equal(completeProject(state,'cargo',500).ok,false);finishRepair(state,510);assert.equal(finishRepair(state,511),false);assert.equal(completeProject(state,'cargo',530).ok,true);assert.equal(completeProject(state,'cargo',531).ok,false);flightArrival(state,'naha',600);assert.equal(completeProject(state,'bus',650).ok,true);ferryArrival(state,'airport',700);ferryArrival(state,'airport',900);assert.equal(completeProject(state,'guesthouse',1000).ok,true);assert.equal(state.island.treasury,16000);assert.ok(flightTimes(state).includes(660));assert.deepEqual(auditArchive(state.documentArchive),[]);retainArchive(state.documentArchive,1001+YEAR_MINUTES);assert.equal(state.documentArchive.records.length,0);});


test('large airport concourses and shopping approaches connect while construction areas are closed',()=>{try{installDOM();const world=createTown({scene:new THREE.Scene(),sites:[],townMode:'peninsula',mobile:true,register(){},enter(){},onAction(){}}),blocked=(x,z)=>!routeAt(x,z,.32)||world.colliders.some(c=>circleHitsRect(x,z,.32,c));for(const [from,to] of [[[-44,31],[-48,31]],[[-48,31],[-48,64]],[[-48,64],[155,64]],[[20,64],[20,47]],[[155,64],[155,83]],[[155,83],[98,83]],[[98,83],[98,110]],[[0,18.7],[0,31]]])for(let t=0;t<=1;t+=.025){const p=airportWorld(from[0]+(to[0]-from[0])*t,from[1]+(to[1]-from[1])*t);assert.equal(blocked(...p),false,'airport route '+p);}assert.equal(routeAt(...airportWorld(135,105),.32),null);assert.ok(routeAt(...airportWorld(170,64),.32));}finally{configureTownMode('legacy');}});

test('Rainflower Lane is reachable with clear central walking space and Thuan outfit changes preserve her skeleton',async()=>{try{installDOM();const world=createTown({scene:new THREE.Scene(),sites:[],townMode:'peninsula',mobile:true,register(){},enter(){},onAction(){}});for(let z=96;z<=129;z+=.5){assert.ok(routeAt(90,z,.32));assert.equal(world.colliders.some(c=>circleHitsRect(90,z,.32,c)),false);assert.equal(groundHeight(90,z),0);}const {buildAvatar}=await import('../src/avatars/build.js'),{recipeFor}=await import('../src/avatars/cast.js');const avatar=buildAvatar(recipeFor('Thuan'));const skeleton=avatar.body.skeleton;avatar.wear('nozomi');const alternate=avatar.root.children.find(c=>c.name==='Thuan · shopping lane outfit');assert.ok(alternate.visible);assert.equal(alternate.skeleton,skeleton);assert.equal(avatar.body.visible,false);avatar.wear('swim');assert.equal(alternate.visible,false);avatar.wear('nozomi');assert.equal(alternate.visible,true);avatar.wear('clothes');assert.equal(avatar.body.visible,true);assert.equal(alternate.visible,false);avatar.wear('sailor');const sailor=avatar.root.children.find(c=>c.name==='Thuan · harbour academy sailor');assert.ok(sailor.visible);assert.equal(sailor.skeleton,skeleton);assert.equal(avatar.body.visible,false);assert.equal(avatar.recipe.name,'Thuan');avatar.wear('clothes');assert.equal(sailor.visible,false);assert.equal(avatar.body.visible,true);avatar.dispose();}finally{configureTownMode('legacy');}});

test('rain follows the explorer and remains animated rain rather than becoming solid overhead cables',()=>{try{installDOM();const player=new THREE.Vector3(90,0,113),world=createTown({scene:new THREE.Scene(),sites:[],townMode:'peninsula',mobile:true,getPlayerPosition:()=>player,register(){},enter(){},onAction(){}}),rain=world.group.getObjectByName('Local rain streaks');assert.ok(rain?.isLineSegments);assert.ok(rain.userData.dynamicProp);world.setRain(true);world.update(.1,1,1,600);assert.equal(rain.visible,true);assert.deepEqual(rain.position.toArray(),player.toArray());const p=rain.geometry.getAttribute('position');for(let i=0;i<p.count;i+=2)assert.ok(Math.abs(p.getY(i+1)-p.getY(i)-.65)<.00001);world.setRain(false);assert.equal(rain.visible,false);}finally{configureTownMode('legacy');}});
