import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const root=new URL('..',import.meta.url).pathname.replace(/\/$/,''),out=root+'/docs/qa/japanese-hair';await mkdir(out,{recursive:true});
const server=createServer(async(req,res)=>{try{let path=new URL(req.url,'http://localhost').pathname;if(path==='/'){res.setHeader('Content-Type','text/html');res.end('<html><body>Town entry</body></html>');return;}if(path.endsWith('/'))path+='index.html';const body=await readFile(root+path);res.setHeader('Content-Type',path.endsWith('.html')?'text/html':path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.json')?'application/json':'application/octet-stream');res.end(body);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(5173,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CREATOR_CHROME,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:process.env});const results=[];
try{
 const page=await browser.newPage({viewport:{width:1200,height:1110}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());
 for(const [suffix,turn] of [['front',0],['side',-.65],['rear',3.14159]]){await page.goto('http://127.0.0.1:5173/tools/japanese-hair-preview.html?turn='+turn);await page.waitForFunction(()=>window.__READY__);await page.waitForTimeout(600);await page.screenshot({path:out+'/collection-'+suffix+'.png'});}
 await page.close();
 for(const [width,height] of [[1280,800],[390,844]]){
 const p=await browser.newPage({viewport:{width,height},hasTouch:width===390,isMobile:width===390});p.on('pageerror',e=>errors.push(e.message));await p.route('https://**/*',r=>r.abort());await p.goto('http://127.0.0.1:5173/creator/?preset=harbour-visitor');await p.getByRole('textbox',{name:'Name',exact:true}).waitFor();await p.locator('.shm-dots button').nth(1).click();await p.getByRole('tab',{name:'Hair',exact:true}).click();
 for(const label of ['Natural mash','Two-block','Flowing centre part','Comma fringe','Spiky short','Layered wolf','Mini bob','Airy fringe bob','Outward-curl bob','Face-framing layers','Hime cut','Long loose waves']){await p.getByRole('button',{name:label,exact:true}).click();}
 await p.getByRole('button',{name:'Airy fringe bob',exact:true}).click();await p.waitForTimeout(1000);await p.screenshot({path:out+'/creator-'+width+'.png'});await p.locator('.shm-dots button').nth(3).click();await p.getByRole('button',{name:'Walk the town as them',exact:true}).click();await p.goto('http://127.0.0.1:5173/creator/');await p.waitForFunction(()=>document.querySelector('.shm'));await p.reload();await p.waitForFunction(()=>document.querySelector('.shm'));const saved=await p.evaluate(async()=>{const {playerRecipe}=await import('/src/avatars/actors.js');return playerRecipe();});assert.equal(saved.hair.style,'jpseethrough');assert.equal(saved.hair.colour,'#caa568');assert.equal(saved.outfit.top,'contrastpolo');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.close();console.log('PASS creator',width);
 }
 const portraits=await browser.newPage({viewport:{width:1280,height:800}});portraits.on('pageerror',e=>errors.push(e.message));await portraits.route('https://**/*',r=>r.abort());await portraits.goto('http://127.0.0.1:5173/creator/?preset=harbour-visitor');await portraits.getByRole('textbox',{name:'Name',exact:true}).waitFor();
 for(const [name,slug,tab] of [['Thuan','thuan','Hair'],['Nhung','nhung','Hats & bows'],['Ruta','ruta','Eyes']]){
 const code=await portraits.evaluate(async(name)=>{const {recipeFor}=await import('/src/avatars/cast.js');const {encodeRecipe}=await import('/src/avatars/recipe.js');const r=structuredClone(recipeFor(name==='Ruta'?'Harbour visitor':name));if(name==='Ruta'){r.name='Ruta';r.eyes={...r.eyes,style:'doe',size:.60};r.hair={...r.hair,style:'jplayered'};}if(name==='Nhung'){r.outfit={...r.outfit,hat:'straw',hatColour:'#d8bd83'};}return encodeRecipe(r);},name);
 await portraits.goto('http://127.0.0.1:5173/creator/?r='+code);await portraits.getByRole('textbox',{name:'Name',exact:true}).waitFor();await portraits.locator('.shm-dots button').nth(1).click();await portraits.getByRole('tab',{name:tab,exact:true}).click();await portraits.waitForTimeout(600);await portraits.screenshot({path:out+'/'+slug+'-creator.png'});console.log('Portrait',name);
 }await portraits.close();
 assert.deepEqual(errors,[]);await writeFile(out+'/results.json',JSON.stringify({styles:12,viewports:[[1280,800],[390,844]],selection:true,saveReload:true,overflow:false,pageErrors:errors},null,2));console.log('PASS gallery and creator');
}finally{await browser.close();server.close();}
