import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const require=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/package.json'),{chromium}=require('playwright');
const browser=await chromium.launch({executablePath:process.env.PHOTO_CHROME||'/root/.cache/ms-playwright/chromium_headless_shell-1161/chrome-linux/headless_shell',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 for(const [width,height] of [[1440,1000],[390,844]]){
  const page=await browser.newPage({viewport:{width,height},hasTouch:width<500});page.setDefaultTimeout(90000);const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});
  await page.route('**/*',route=>route.request().url().startsWith('http://town.test/')?route.fallback():route.abort());
  let staleTitle=width===1440;await page.route('http://town.test/**',async route=>{let path=new URL(route.request().url()).pathname;if(path.endsWith('/'))path+='index.html';try{await route.fulfill({body:await (async()=>{const data=await readFile(new URL('..'+path,import.meta.url));if(staleTitle&&path==='/index.html'){staleTitle=false;return Buffer.from(data.toString().replace(/await import\('\.\/runtime\/boot-[^']+\.js'\)/,"await import('./runtime/boot-expired.js')"));}return data;})(),contentType:path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.html')?'text/html':path.endsWith('.json')?'application/json':'application/octet-stream'});}catch{await route.fulfill({status:404,body:'Not found'});}});
  await page.addInitScript(()=>{localStorage.setItem('johansson-town-clock',JSON.stringify({start:'12:00',speed:1}));Object.defineProperty(navigator,'getGamepads',{value:()=>[]});Element.prototype.requestFullscreen=async()=>{};const add=window.addEventListener.bind(window);window.addEventListener=(type,...args)=>{if(!type.startsWith('gamepad'))add(type,...args);};});
  await page.goto('http://town.test/?audit');await page.locator('#enter').click();await page.waitForFunction(()=>window.__JOHANSSON_RUNNING__&&window.__JOHANSSON_AUDIT__,{},{timeout:240000});
  await page.waitForFunction(()=>!window.__JOHANSSON_AUDIT__.blocked.catchingUp&&!window.__JOHANSSON_AUDIT__.blocked.roomLoading);
  // Use the actual menu entry; game state and actor visibility must survive staging.
  await page.locator('#directoryButton').click();for(const id of ['viewButton','timeButton','weatherButton','soundButton','fullscreenButton'])assert.equal(await page.locator('#'+id+' svg').count(),1);await page.screenshot({path:fileURLToPath(new URL(`./evidence/photo-studio/menu-${width}.png`,import.meta.url))});await page.locator('#photoButton').click();await page.locator('#photoStudio').waitFor({state:'visible'});
  const before=await page.evaluate(()=>({pose:window.__JOHANSSON_POSE__,cast:window.__JOHANSSON_CAST__.takes.map(c=>({name:c.name,at:c.at})),state:JSON.stringify(window.__JOHANSSON_AUDIT__.activities.state)}));
  await page.getByLabel('Pose',{exact:true}).selectOption('Wave');await page.getByLabel('Speech bubble',{exact:true}).fill('Greetings from Johansson Town!');
  await page.getByRole('button',{name:'Capture panel',exact:true}).click();await page.locator('[data-tab="film"]').click();await page.locator('.photo-film figure').waitFor();
  const during=await page.evaluate(()=>({pose:window.__JOHANSSON_POSE__,cast:window.__JOHANSSON_CAST__.takes.map(c=>({name:c.name,at:c.at})),state:JSON.stringify(window.__JOHANSSON_AUDIT__.activities.state)}));
  assert.deepEqual(during,before,'Staging must not move real actors, the player, or advance saved simulation state');
  await page.screenshot({path:fileURLToPath(new URL(`./evidence/photo-studio/game-${width}.png`,import.meta.url))});
  await page.locator('[data-tab="place"]').click();await page.getByRole('button',{name:'Sato Ramen',exact:true}).click();await page.waitForFunction(()=>window.__JOHANSSON_AUDIT__.room.visible&&!window.__JOHANSSON_AUDIT__.blocked.roomLoading);await page.locator('[data-tab="cast"]').click();await page.getByRole('button',{name:'Remove character',exact:true}).click();assert.equal(await page.locator('select[name=actor] option').count(),1);await page.getByRole('button',{name:'Return to town',exact:true}).click();await page.waitForFunction(()=>!window.__JOHANSSON_AUDIT__.room.visible);assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.photoActive),false);assert.equal(await page.locator('body > #game').count(),1);
  // Warehouse entry uses the real interaction path and real room builder.
  await page.evaluate(()=>window.__JOHANSSON_AUDIT__.use('Enter Harbour Warehouse'));await page.waitForFunction(()=>window.__JOHANSSON_AUDIT__.room.visible&&!window.__JOHANSSON_AUDIT__.blocked.roomLoading);
  await page.evaluate(()=>window.__JOHANSSON_AUDIT__.photo());await page.locator('#photoStudio').waitFor({state:'visible'});assert.equal(await page.locator('.photo-film figure').count(),1);
  await page.getByLabel('Add a character',{exact:true}).selectOption('Mrs Sato');await page.getByRole('button',{name:'Add',exact:true}).click();await page.getByLabel('Pose',{exact:true}).selectOption('Shrug');await page.getByLabel('Style',{exact:true}).selectOption('comic');await page.locator('[data-tab="text"]').click();await page.getByLabel('Bottom text · meme or comic',{exact:true}).fill('Meanwhile, at the warehouse…');
  await page.getByRole('button',{name:'Capture panel',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.photo-film figure').length===2);
  await page.locator('[data-tab="film"]').click();await page.getByRole('button',{name:'Save comic PNG',exact:true}).click();await page.getByRole('link',{name:'Download comic PNG',exact:true}).waitFor();
  await page.getByRole('button',{name:'Return to town',exact:true}).click();await page.evaluate(()=>window.__JOHANSSON_AUDIT__.leave());await page.waitForFunction(()=>!window.__JOHANSSON_AUDIT__.room.visible);await page.evaluate(()=>window.__JOHANSSON_AUDIT__.enter('resident-home-thuan'));await page.waitForFunction(()=>window.__JOHANSSON_AUDIT__.room.visible&&!window.__JOHANSSON_AUDIT__.blocked.roomLoading);assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.use('Open Thuan’s wardrobe')),true);
  await page.getByRole('button',{name:'Wear the harbour academy sailor set',exact:true}).click();assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.activities.state.thuanOutfit),'sailor');await page.evaluate(()=>window.__JOHANSSON_AUDIT__.step(0));assert.equal(await page.evaluate(()=>{const p=window.__JOHANSSON_AUDIT__.world.people.find(p=>p.profile.name==='Thuan');return !!p.g.getObjectByName('Thuan · harbour academy sailor')?.visible;}),true);
  assert.equal(await page.evaluate(async()=>{const {readSave}=await import('/src/save.js');return readSave(localStorage).thuanOutfit;}),'sailor');await page.screenshot({path:fileURLToPath(new URL(`./evidence/photo-studio/thuan-home-${width}.png`,import.meta.url))});await page.evaluate(()=>window.__JOHANSSON_AUDIT__.leave());
  await page.evaluate(()=>window.__JOHANSSON_AUDIT__.enter('mayor-office'));await page.waitForFunction(()=>window.__JOHANSSON_AUDIT__.room.visible&&!window.__JOHANSSON_AUDIT__.blocked.roomLoading);assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.use('Use the mayor’s computer')),true);await page.locator('#activity').waitFor({state:'visible'});await page.evaluate(()=>window.__JOHANSSON_AUDIT__.activities.close());assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.use('Sit at the mayor’s desk')),true);assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.seated),true);await page.screenshot({path:fileURLToPath(new URL(`./evidence/photo-studio/mayor-office-${width}.png`,import.meta.url))});await page.evaluate(()=>window.__JOHANSSON_AUDIT__.leave());
  assert.equal(await page.locator('#fatal').isVisible(),false);assert.deepEqual(errors,[]);console.log(JSON.stringify({viewport:[width,height],status:'Published runtime: menu, outdoor capture, state freeze, warehouse capture, two-scene comic and exit passed',errors}));await page.close();
 }
}finally{await browser.close();}
