import assert from 'node:assert/strict';import {chromium} from 'playwright';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),evidence=new URL('./evidence/storage-boss/',import.meta.url);await mkdir(evidence,{recursive:true});const reports=[];
for(const [width,height] of [[1280,800],[390,844]]){
 const browser=await chromium.launch({executablePath:process.env.STORAGE_CHROME||chromium.executablePath(),args:['--no-sandbox','--single-process','--no-zygote','--disable-gpu-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 try{
 const context=await browser.newContext({viewport:{width,height},hasTouch:width===390,isMobile:width===390,serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(90000);const errors=[],networkNotes=[];page.on('pageerror',e=>{errors.push(e.message);console.log('pageerror',e.message);});page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')console.log(m.type(),m.text().slice(0,300));});page.on('requestfailed',r=>networkNotes.push(r.url()+' '+r.failure()?.errorText));
 await page.addInitScript(()=>{if(location.pathname==='/johansson-town/')history.replaceState(null,'','?audit');Object.defineProperty(navigator,'getGamepads',{value:()=>[]});Element.prototype.requestFullscreen=async()=>{};localStorage.setItem('johansson-town-clock',JSON.stringify({start:'20:10',speed:1}));});
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='town.test')return route.abort();let path=u.pathname;if(path.endsWith('/'))path+='index.html';try{
 let body=await readFile(root+path);
 if(path.includes('/assets/storage-')&&path.endsWith('.js')){
 let code=body.toString();const marker='  resetPosition();restored=restoreCheckpoint(resumeData);checkpoint();resize();';assert.ok(code.includes(marker));
 // Test-only deterministic seed, observations, positioning and clock acceleration.
 // Built gameplay, checkpoints, UI and hand-off execute without substitution.
 code=code.replace('Math.floor(Math.random()*1e9)),world=Yp(maze)','1),world=Yp(maze)');
 code=code.replace(marker,`window.__STORAGE_AUDIT__={advance(n){for(let i=0;i<Math.ceil(n*60);i++)step(1/60);checkpoint();emitHud();},atRow(r){const p=gd(10,r,maze);return [p.x,p.z];},get data(){return {seed:maze.seed,time,phase,px,pz,automatic,items:world.items.map(i=>({id:i.id,taken:!!i.taken})),boss:{who:boss.who,state:boss.state,hp:boss.hp},yenFound};}};\n${marker}`);
 code=code.replace('((n.current = t), a(`ready`));','((n.current = t), window.__STORAGE_GAME__=t, a(`ready`));');body=Buffer.from(code);
 }
 await route.fulfill({body,contentType:path.endsWith('.js')||path.endsWith('.mjs')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.html')?'text/html':path.endsWith('.json')?'application/json':'application/octet-stream'});
 }catch(e){console.log('route failure',path,e.message);await route.fulfill({status:404,body:''});}});
 const town=async()=>{await page.goto('http://town.test/johansson-town/?audit');console.log(width,'loaded');await page.locator('#enter').click();console.log(width,'clicked');await page.waitForFunction(()=>window.__JOHANSSON_RUNNING__&&window.__JOHANSSON_AUDIT__&&!window.__JOHANSSON_AUDIT__.blocked.catchingUp);await page.evaluate(()=>{const a=window.__JOHANSSON_AUDIT__;a.frozen=true;a.renderFrozen=false;});console.log(width,'ready');};
 const storageReady=()=>page.waitForFunction(()=>window.__STORAGE_GAME__&&window.__STORAGE_AUDIT__.data.phase==='playing');
 const shooRounds=n=>page.evaluate(n=>{const a=window.__STORAGE_AUDIT__,g=window.__STORAGE_GAME__;for(let r=0;r<n;r++){g._stage({thuan:a.atRow(9.6),boss:[...a.atRow(8),0]});a.advance(.4);for(let k=0;k<120&&a.data.boss.state!=='tired';k++)a.advance(.1);g._stage({thuan:a.atRow(8.6)});g.shoo();a.advance(.2);}g.pause();},n);
 console.log(width,'town');await town();const day=await page.evaluate(()=>{const a=window.__JOHANSSON_AUDIT__;const day=Math.floor(JSON.parse(window.render_game_to_text()).minutes/1440);a.setTime(day*1440+1210);a.activities.state.yen=1000;a.activities.state.sakura.restockedDay=-1;a.activities.state.sakura.stock.tea.shelf=18;a.activities.save();a.activities.action('storage-restock');return day;});
 await page.getByRole('button',{name:'Play as Thuan',exact:true}).click();await storageReady();assert.match(page.url(),new RegExp('day='+day+'&player=player-1'));console.log(width,'storage');
 await page.evaluate(()=>window.__STORAGE_AUDIT__.advance(11));await shooRounds(1);const before=await page.evaluate(()=>window.__STORAGE_AUDIT__.data);assert.equal(before.boss.hp,2);await page.screenshot({path:fileURLToPath(new URL(`fight-${width}.png`,evidence))});
 await page.reload();await storageReady();let recovered=await page.evaluate(()=>window.__STORAGE_AUDIT__.data);assert.equal(recovered.seed,before.seed);assert.equal(recovered.boss.hp,2);assert.ok(recovered.time>=before.time&&recovered.time<before.time+2);assert.deepEqual(recovered.items,before.items);
 const stockroom=page.url();await town();await page.goto(stockroom);await storageReady();assert.equal(await page.evaluate(()=>window.__STORAGE_AUDIT__.data.boss.hp),2);
 await shooRounds(2);assert.equal(await page.evaluate(()=>window.__STORAGE_AUDIT__.data.yenFound),200);await page.reload();await storageReady();assert.equal(await page.evaluate(()=>window.__STORAGE_AUDIT__.data.yenFound),200);
 await page.evaluate(()=>{window.__STORAGE_GAME__.autoRestock();for(let n=0;n<240&&window.__STORAGE_AUDIT__.data.phase!=='won';n++)window.__STORAGE_AUDIT__.advance(1);});
 await page.waitForURL('**/johansson-town/');await page.locator('#enter').click();await page.waitForFunction(()=>window.__JOHANSSON_RUNNING__&&window.__JOHANSSON_AUDIT__);
 const applied=await page.evaluate(()=>{const a=window.__JOHANSSON_AUDIT__;a.frozen=true;a.renderFrozen=false;return {yen:a.activities.state.yen,day:a.activities.state.sakura.storageOutcomeDay,restocked:a.activities.state.sakura.restockedDay};});assert.equal(applied.yen,1200);assert.equal(applied.day,day);assert.equal(applied.restocked,day);await page.screenshot({path:fileURLToPath(new URL(`return-${width}.png`,evidence))});console.log(width,'returned');
 await page.evaluate(day=>{const a=window.__JOHANSSON_AUDIT__;a.activities.state.sakura.stock.tea.shelf=17;a.activities.save();localStorage.setItem('johansson-town:storage-won:player-1',JSON.stringify({day,player:'player-1',boss:{who:'Tetsuo',animal:'bear',defeated:true},yen:200,t:123}));a.activities.consumeStorageRestock();},day);assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.activities.state.yen),1200);assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.activities.state.sakura.stock.tea.shelf),17);
 await town();assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.activities.state.yen),1200);await page.goto(stockroom);await page.waitForFunction(()=>window.__STORAGE_GAME__&&window.__STORAGE_AUDIT__.data.phase==='won');assert.equal(await page.getByRole('button',{name:'New list',exact:true}).isDisabled(),true);
 await page.waitForURL('**/johansson-town/');await page.locator('#enter').click();await page.waitForFunction(()=>window.__JOHANSSON_RUNNING__&&window.__JOHANSSON_AUDIT__);assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.activities.state.yen),1200);
 await page.evaluate(day=>{const a=window.__JOHANSSON_AUDIT__;a.frozen=true;a.setTime((day+1)*1440+1210);a.activities.save();const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('johansson-town-1988-v5'))throw Error('test quota');return original.call(this,k,v);};localStorage.setItem('johansson-town:storage-won:player-1',JSON.stringify({day:day+1,player:'player-1',boss:{who:'Tetsuo',animal:'bear',defeated:true},yen:200,t:124}));a.activities.consumeStorageRestock();},day);assert.ok(await page.evaluate(()=>localStorage.getItem('johansson-town:storage-won:player-1')));
 await town();assert.equal(await page.evaluate(()=>window.__JOHANSSON_AUDIT__.activities.state.yen),1400);assert.equal(await page.evaluate(()=>localStorage.getItem('johansson-town:storage-won:player-1')),null);
 assert.deepEqual(errors,[]);reports.push({viewport:[width,height],checks:['town player/closing-day bridge','partial fight reload','re-entry recovery','defeated boss reload','full automatic restock and town redirect','once-only 200 yen','duplicate handshake leaves shelves unchanged','completed night cannot restart','failed save recovery'],applied,errors,networkNotes});console.log(width,'passed');
 }finally{await browser.close();}
}
await writeFile(new URL('acceptance.json',evidence),JSON.stringify(reports,null,2)+'\n');
