import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as THREE from '../vendor/three.module.js';
import {GLTFLoader} from '../vendor/GLTFLoader.js';
import {createFutonRoutine,buildTatamiHome} from '../src/world/interiors/tatami-home.js';
import {TATAMI_HOME_LAYOUT,TATAMI_HOME_OWNER} from '../src/world/interiors/tatami-home-layout.js';
import {RESIDENTS} from '../src/people/residents.js';
import {sleepHours,homeLayoutFor} from '../src/people/home-life.js';
import {circleHitsRect} from '../physics.js';
const profile=RESIDENTS.find(p=>p.name===TATAMI_HOME_OWNER);
test('futon follows bedtime, overnight, waking and storage across midnight and revisits',()=>{
 const {sleep,wake}=sleepHours(profile),r=createFutonRoutine(profile);
 assert.equal(r.update(0,wake+60).phase,'stored');
 assert.equal(r.update(.9,sleep-10).phase,'unfolding');
 assert.equal(r.update(.9,sleep-9).phase,'laid out');
 assert.equal(r.update(1,3*60).phase,'laid out');
 assert.equal(r.update(1,wake+5).phase,'laid out');
 assert.equal(r.update(.9,wake+16).phase,'folding away');
 assert.equal(r.update(.9,wake+17).phase,'stored');
 assert.equal(createFutonRoutine(profile).update(0,3*60).phase,'laid out');
 assert.equal(createFutonRoutine(profile).update(0,wake+60).phase,'stored');
 assert.equal(r.update(-5,wake+60).amount,0);
});
test('Blender room carries actual cupboard bedding and a movable fan, with no embedded foreign assets',async()=>{
 const data=readFileSync(new URL('../assets/models/tatami-home/tatami-home.glb',import.meta.url));
 const gltf=await new GLTFLoader().parseAsync(data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),'');
 for(const name of ['LaidFuton','StoredFuton','FanRotor','FutonCupboardDoor','Room_straw','Room_green'])assert.ok(gltf.scene.getObjectByName(name),name);
 const json=JSON.parse(data.subarray(20,20+data.readUInt32LE(12)).toString());assert.equal(json.images,undefined);assert.ok(json.meshes.length<40,'furnishings batched for mobile');
});
test('entry, bedside and tea cushion remain accessible and inspection describes current bedding',()=>{
 const room=new THREE.Group(),colliders=[],actions=[],prompts=[];
 const home=buildTatamiHome({profile,room,box:(s,p,c,parent)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...s),new THREE.MeshBasicMaterial({color:c}));m.position.fromArray(p);parent.add(m);return m;},collider:(x,z,w,d,height)=>colliders.push({x,z,w,d,height}),reg:(o,label,fn)=>prompts.push({label,fn}),action:(...a)=>actions.push(a),exit(){}});
 assert.deepEqual(homeLayoutFor(TATAMI_HOME_OWNER),TATAMI_HOME_LAYOUT);
 for(const p of [home.spawn,home.door,home.table,home.bedside])assert.ok(!colliders.some(c=>circleHitsRect(p[0],p[2],.32,c)),String(p));
 home.tick(0,3*60);assert.equal(home.snapshot().futon.phase,'laid out');assert.equal(room.getObjectByName('LaidFuton').visible,true);
 const inspect=prompts.find(p=>p.label==='Inspect the futon cupboard');inspect.fn();assert.match(actions.at(-1)[2],/laid out/);
 home.tick(2,sleepHours(profile).wake+60);assert.equal(home.snapshot().futon.phase,'stored');assert.equal(room.getObjectByName('LaidFuton').visible,false);
 home.dispose();
});
