import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.js';
import {buildWarehouse,buildWarehouseShell,WAREHOUSE,WAREHOUSE_PLACE} from '../src/world/warehouse.js';
import {createTown} from '../src/world/harbour.js?snappy=1';
import {drawTownMap} from '../src/world/map.js?snappy=1';
import {routeAt} from '../src/world/layout.js?snappy=1';
import {circleHitsRect,sweepFraction} from '../physics.js?snappy=1';
import {installDOM} from './fixtures.mjs';
import {createIslandBusinesses as createBusinesses} from '../src/world/businesses.js';
import {HARBOUR_OFFICE} from '../src/world/business-layout.js';
test('the kit warehouse is a grounded tin shed that fits the quay plot and faces the street',()=>{
 installDOM();
 const shell=buildWarehouseShell(),bounds=new THREE.Box3().setFromObject(shell);let draws=0;
 shell.traverse(o=>{if(!o.isMesh)return;draws++;assert.ok(!o.material.map,'Painted, not photographed: '+o.name);});
 assert.ok(draws>0&&draws<12,'Batched by finish');
 assert.ok(Math.abs(bounds.min.y)<.01,'Grounded');
 assert.ok(bounds.min.x>-17&&bounds.max.x<-7.5,'Fits between western lane and main street');
 assert.ok(bounds.min.z>-48.2&&bounds.max.z<-36.4,'Roof fits the quay plot');
 assert.ok(bounds.max.y>5.4&&bounds.max.y<6.2,'Eave and ridge at the collider height');
});
test('warehouse and consolidated office share a reachable quay',async()=>{
 installDOM();const registered=[];
 const world=createTown({scene:new THREE.Scene(),sites:createBusinesses(),mobile:true,register:(o,label,fn)=>registered.push({o,label,fn}),onAction(){}});
 const blocked=(x,z)=>!routeAt(x,z,.32)||world.colliders.some(c=>circleHitsRect(x,z,.32,c));
 assert.equal(world.colliders.some(c=>c.x===13.7&&c.w===6.4),false,'The harbour office replaces the eastern cold store');
 assert.ok(world.group.getObjectByName('Consolidated harbour office'));assert.ok(world.colliders.some(c=>c.x===HARBOUR_OFFICE.x&&c.w===HARBOUR_OFFICE.width));
 assert.equal(world.colliders.some(c=>c.x===-13.7&&c.w===6.4),false,'Old western shed collider removed');
 const [x,,z]=WAREHOUSE_PLACE.exitPosition;
 const path=[[0,-46],[0,z],[x,z]];
 for(let i=1;i<path.length;i++)assert.equal(sweepFraction({x:path[i-1][0],z:path[i-1][1]},{x:path[i][0],z:path[i][1]},blocked),1,'Walk from main street to warehouse');
 for(let z=-48;z<=-49;z+=.2)assert.equal(world.colliders.some(c=>circleHitsRect(-18,z,.32,c)),false,'No collision intrudes into the western approach');
 assert.ok(world.colliders.some(c=>circleHitsRect(WAREHOUSE.x,WAREHOUSE.z,.32,c)),'Warehouse walls block movement');
 assert.ok(registered.find(a=>a.label==='Enter Harbour Warehouse'));
 assert.ok(world.group.getObjectByName('warehouse-street-door'));
 assert.ok(world.group.getObjectByName('warehouse-entrance'));
 const before=JSON.stringify(world.colliders);
 assert.equal(await world.warehouse.load(),true);assert.equal(world.warehouse.status,'ready');assert.equal(JSON.stringify(world.colliders),before);
 assert.ok(world.group.getObjectByName('Harbour Warehouse kit exterior'),'Built in code from the first frame');
 assert.ok(world.group.getObjectByName('warehouse-street-door'));
});
test('the warehouse is solid with nothing to download; visitor map names the landmark',async()=>{
 installDOM();const world={group:new THREE.Group(),colliders:[]};const state=buildWarehouse(world);
 assert.equal(state.status,'ready');assert.ok(world.group.getObjectByName('Harbour Warehouse kit exterior'));
 assert.ok(world.colliders.some(c=>circleHitsRect(WAREHOUSE.x,WAREHOUSE.z,.32,c)));
 const labels=[],ctx=document.createElement('canvas').getContext('2d');ctx.fillText=t=>labels.push(t);
 drawTownMap(ctx,680,640,{landmarks:[WAREHOUSE_PLACE]});
 assert.ok(labels.some(t=>t.includes('Harbour Warehouse')));
});
