// Generated by scripts/build-town-papers.mjs from authored public papers and native office sheets.
export const TOWN_PAPERS=[
  {
    "type": "Flyer",
    "title": "Sakura Shop · Thuan’s neighbourhood flyer",
    "organisation": "Sakura Shop",
    "author": "Thuan",
    "source": "flyer:sakura-shop-1997",
    "text": "SAKURA SHOP — Your little island convenience store\n1997 neighbourhood edition · Prepared by Thuan\nOpen daily 09:00–20:00. Cash only. All prices include tax.\nPlum rice ball · ¥110\nGreen tea · ¥120\nSalted potato crisps · ¥100\nOne stamp per ¥300 spent in a visit. Collect 10 stamps for a free green tea.\nFind us on Main Street, beside the harbour approach. The map is a neighbourhood sketch; the bus stop is north and the harbour is south.\nMeet Jaga-bo, our KOGANE potato-crisp mascot. Drop in and say hello to Thuan!\nFree copies at Sakura’s counter and the harbour notice board. Community Hall keeps a filed copy for one year."
  },
  {
    "type": "Notice",
    "title": "Blue Coral attendant",
    "organisation": "Town Services",
    "text": "Welcome! The ube scoop is our favourite. Take your time at the glass counter; the little benches outside catch the sea breeze.",
    "source": "notice:Blue Coral attendant"
  },
  {
    "type": "Notice",
    "title": "Island freight and dock shifts",
    "organisation": "Town Services",
    "text": "WESTERN QUAY · ISLAND LIFELINE\nCargo crews: 07:00–22:00. Early boat: ice, rice and shop supplies. Afternoon: post, repair parts and village parcels. Evening: chilled fish and outgoing mail.\nRiku walks the cargo circuit; Emi Kado checks manifests at the dispatch desk. Ferry passengers use the marked main quay. Dock Electrical & Repairs is beside the warehouse. Keep its doorway and the hoist bay clear.",
    "source": "notice:Island freight and dock shifts"
  },
  {
    "type": "Notice",
    "title": "East beach",
    "organisation": "Town Services",
    "text": "The opening in the seawall leads down to the sand. Follow the shore to the other beach entrance.",
    "source": "notice:East beach"
  },
  {
    "type": "Notice",
    "title": "Rainflower is closed",
    "organisation": "Town Services",
    "text": "Mrs Kinjō serves flowers from 09:00 to 18:00. You may still look around the open shop.",
    "source": "notice:Rainflower is closed"
  },
  {
    "type": "Notice",
    "title": "Rainflower Florist",
    "organisation": "Town Services",
    "text": "Fresh stems, potted greenery and hand-made wreaths. Mrs Kinjō works here from 09:00 to 18:00, and still reminds her husband that supper will not wait for the tide. The flowers are refreshed when the supply boat brings its morning delivery.",
    "source": "notice:Rainflower Florist"
  },
  {
    "type": "Flyer",
    "title": "Forest road notice",
    "organisation": "Town Services",
    "text": "The road disappears into the trees. The Harbour Line has permission to continue beyond the wall; pedestrians must turn back at the bus terminal.",
    "source": "notice:Forest road notice"
  },
  {
    "type": "Notice",
    "title": "Class board",
    "organisation": "Town Services",
    "text": "Over the cubbies: the class goal, \"Everyone friendly, cheerful, and say hello,\" eight sheets of calligraphy -- Sea sea, Dream dream, Friend friend, Sky sky -- each with a red circle from the teacher. Kenta's essay about rowing in the Hāri boat race with his grandfather. The paper wheel of cleaning duties. Summer projects: reef creatures, how to make sata andagi, a typhoon diary. This week's lunch squad: Kinjō, Arakaki, Taira -- \"don't forget your smock, cap and mask.\"",
    "source": "notice:Class board"
  },
  {
    "type": "Notice",
    "title": "For rent · Rental house",
    "organisation": "Town Services",
    "text": "2DK, tatami, kitchen and bath, water tank on the roof. ¥28,000 a month. Enquiries to the town hall, Residents Division. Somebody new could live here.",
    "source": "notice:For rent · Rental house"
  },
  {
    "type": "Notice",
    "title": "Town office telephone",
    "organisation": "Community Hall",
    "text": "The harbour master confirms Thursday’s supply ferry. Mori reports the crossing outside the school is clear. Thuan asks whether the bus-stop bench has reached the carpenter yet.",
    "source": "notice:Town office telephone"
  },
  {
    "type": "Notice",
    "title": "Town reference library",
    "organisation": "Community Hall",
    "text": "Ferry timetables, old island surveys, typhoon preparedness manuals and annotated town budgets. The most-thumbed volume is the harbour maintenance handbook.",
    "source": "notice:Town reference library"
  },
  {
    "type": "Minutes",
    "title": "Town assembly minutes, 1997",
    "organisation": "Community Hall",
    "text": "Item 3: the power house's second diesel set to be overhauled before typhoon season; the old barber's shop to be let to the post office. Item 5: the ferry company asks for a longer ramp so the new cargo trucks can board. Item 7: Mrs Sato's complaint about the gulls, again. Item 9: the sewage works on Kitano-jima to be inspected by the prefecture in November.",
    "source": "notice:Town assembly minutes, 1997"
  },
  {
    "type": "Notice",
    "title": "Bookshelf",
    "organisation": "Community Hall",
    "text": "Sea charts of the Ryūkyū arc. A Swedish–Japanese dictionary with a cracked spine. Three Wallander paperbacks. The town budget for 1997, with coffee rings.",
    "source": "notice:Bookshelf"
  },
  {
    "type": "Notice",
    "title": "Medicine cabinet",
    "organisation": "Community Hall",
    "text": "Brown bottles and white boxes behind glass, every shelf labelled in the doctor's neat katakana: Antipyretic for fevers, Stomach medicine for stomachs, the habu antivenom in the fridge underneath (two vials, checked monthly, the date on the door), seasickness tablets for the ferry, sting cream for jellyfish season, and one shelf that just says Children · children.",
    "source": "notice:Medicine cabinet"
  },
  {
    "type": "Notice",
    "title": "Minato fuel depot · Port Town Fuel Base",
    "organisation": "Town Services",
    "text": "Hazardous materials · No open flames allowed. Diesel oil (Light oil), 120 kilolitres. Filled from the tanker at the oil jetty every third day; drawn by the town truck for the power house at the town hall. In a typhoon the valves are closed and the jetty is out of bounds.",
    "source": "notice:Minato fuel depot · Port Town Fuel Base"
  },
  {
    "type": "Flyer",
    "title": "Umi-no-yu notice",
    "organisation": "Town Services",
    "text": "Harbour hot spring. Bath 10:00–22:00, adults ¥300. The footbath is free and never closes. Sodium chloride spring, 42°C at the spout — good for cold hands and long shifts on the quay. Please wash before you bathe.",
    "source": "notice:Umi-no-yu notice"
  },
  {
    "type": "Notice",
    "title": "Minato Park · Minato Park",
    "organisation": "Town Services",
    "text": "Laid out in 1972 on the old lookout mound. The kanhizakura was planted by the class of that year and flowers in January, the first cherry in Japan. Please take your rubbish home. No ball games on the mound. — Minato Town Office",
    "source": "notice:Minato Park · Minato Park"
  },
  {
    "type": "Notice",
    "title": "Mr Fujita’s television",
    "organisation": "Town Services",
    "text": "A portable set older than the boat, on a fish crate, the aerial bent to find the signal from across the water. Mr Fujita does not look away from it. \"Sit, sit. The eighth innings is the only one worth watching. Have a can; they are cold, the box is new.\"",
    "source": "notice:Mr Fujita’s television"
  },
  {
    "type": "Flyer",
    "title": "School noticeboard",
    "organisation": "Town Hall Classroom",
    "text": "Pinned in the entrance of the town hall, one over another: Typhoon shelter -- in a typhoon, the school gym and the community hall are the shelters, check your emergency bag. Port Safety -- do not play on the quay or the tetrapods. From the fishing co-op, the youth section is taking crews for the harbour boat race (Harbour Boat Race) on the fourth day of the fifth month. A felt-pen map of the town with the shelters in red. This month's kyūshoku: goya champuru, sōki-jiru, fried aji. Lost: one blue sandal, left foot.",
    "source": "notice:School noticeboard"
  },
  {
    "title": "Petitions to the mayor",
    "type": "Notice",
    "organisation": "Community Hall",
    "text": "From Mr Shimabukuro, the power house next door: The second diesel set needs new injectors before typhoon season. The parts come on the Thursday ferry if the town pays this week.\n\nFrom Mrs Nakamura, Nakamura Zenzai: The street lamp outside the east row has flickered since the rain. Customers say it makes the zenzai look grey.\n\nFrom the Higa household, Nishi-machi: May the children use the town hall field on Sunday for eisa practice? Grandmother Higa will supervise. Loudly.\n\nFrom the ferry company: The new cargo trucks are heavier. We ask the town to strengthen the quay apron where the ramp lands.\n\nFrom Thuan, Sakura Shōten: A request for a bench at the bus stop by the ferry. People wait there with their shopping.",
    "source": "notice:Petitions to the mayor"
  },
  {
    "title": "Community kitchen bookings",
    "type": "Schedule",
    "organisation": "Community Hall",
    "text": "Saturday: Women's Association · women's association, andagi for the eisa night (Mrs Nakamura)\n\nSunday: Higa family, 33rd anniversary memorial lunch\n\nWednesday: Years 5–6 cooking class, goya champurū (Yonamine-sensei)\n\nFriday: open to all, 18:00 -- bring your own fish (Kōji has promised tuna)",
    "source": "notice:Community kitchen bookings"
  },
  {
    "title": "Minato Clinic opening hours",
    "type": "Schedule",
    "organisation": "Minato Clinic",
    "text": "Mon–Fri · Mon–Fri 9:00–12:00, 14:00–17:00\n\nEarth · Sat 9:00–12:00\n\nAfter hours: ring the bell, the doctor lives behind the clinic\n\nEmergencies to Naha by the ferry, or the prefecture helicopter from Kitano-jima",
    "source": "notice:Minato Clinic opening hours"
  },
  {
    "type": "Message",
    "title": "The Venture",
    "organisation": "Aya’s bookshop",
    "text": "The Venture\nAya’s reading copy. Please return it to the display shelf.\n\nTHE VENTURE\nThe rain has not let up in three days. At the waterside inn, a young sailor watches the clerk put away his pen. A berth is available. The price of passage is work.\n\nBOOKMARK\nA faded ferry ticket marks this page. On the back: “Meet me after the last boat.”",
    "source": "item:book"
  },
  {
    "type": "Message",
    "title": "The Gallows Years",
    "organisation": "Aya’s bookshop",
    "text": "The Gallows Years\nAya’s reading copy. Please return it to the display shelf.\n\nTHE GALLOWS YEARS\nThe old captain keeps his coat on by the fire. Nobody asks him about the rope marks. He has come to hear whether the packet ship made harbour before the storm.\n\nBOOKMARK\nA faded ferry ticket marks this page. On the back: “Meet me after the last boat.”",
    "source": "item:book2"
  },
  {
    "type": "Message",
    "title": "Kings of Bengal",
    "organisation": "Aya’s bookshop",
    "text": "Kings of Bengal\nAya’s reading copy. Please return it to the display shelf.\n\nKINGS OF BENGAL\nBetween the cargo columns somebody has pressed a flower. The accounts say nothing about it. The flower says nothing about the accounts.\n\nBOOKMARK\nA faded ferry ticket marks this page. On the back: “Meet me after the last boat.”",
    "source": "item:book3"
  },
  {
    "type": "Message",
    "title": "The Poppy",
    "organisation": "Aya’s bookshop",
    "text": "The Poppy\nAya’s reading copy. Please return it to the display shelf.\n\nTHE POPPY\nA boat waits at the river steps. Its owner counts the bundles once, then again. On the other bank, the morning market has begun.\n\nBOOKMARK\nA faded ferry ticket marks this page. On the back: “Meet me after the last boat.”",
    "source": "item:book4"
  },
  {
    "type": "Message",
    "title": "The Watchman’s Daughter",
    "organisation": "Aya’s bookshop",
    "text": "The Watchman’s Daughter\nAya’s reading copy. Please return it to the display shelf.\n\nTHE WATCHMAN’S DAUGHTER\nShe carries a white bowl through the crowded lane. It was her father’s. In a new city, it is useful to know the weight of one familiar thing.\n\nBOOKMARK\nA faded ferry ticket marks this page. On the back: “Meet me after the last boat.”",
    "source": "item:book5"
  },
  {
    "type": "Message",
    "title": "The Engine Room",
    "organisation": "Aya’s bookshop",
    "text": "The Engine Room\nAya’s reading copy. Please return it to the display shelf.\n\nTHE ENGINE ROOM\nThe watch changes at four. A hand rests on the bearing housing; the new engineer listens before he touches a tool. Above them, the harbour lights drift past.\n\nBOOKMARK\nA faded ferry ticket marks this page. On the back: “Meet me after the last boat.”",
    "source": "item:book6"
  },
  {
    "type": "Message",
    "title": "NILS JOHANSSON · MARINE SERVICE FOLIO",
    "organisation": "Harbour office",
    "text": "MARINE SERVICE\nNils Johansson · Visiting engineer\n\nDiesel machinery, pumps, controls and workshop measurements.\n\nLeave a written fault report with the harbour office. Record what happened, when it happened and which checks have already been made.\n\nDAILY RECORD · 14 SEPTEMBER 1997\n06:40 — fishing boat cooling-water pump\n09:10 — workshop instrument check\n13:00 — harbour winch inspection\n16:30 — collect replacement seals\n\nA blue pencil underlines the last entry twice.",
    "source": "item:cv"
  },
  {
    "type": "Notice",
    "title": "Harbour maintenance notice",
    "organisation": "Evening Press",
    "text": "Harbour maintenance notice\n14 September 1997\n\nThe outer pier remains open to pedestrians. Keep the mooring lanes clear. Return borrowed tools before the office closes.",
    "source": "item:bligh"
  },
  {
    "type": "Notice",
    "title": "The evening deliveries",
    "organisation": "Evening Press",
    "text": "The evening deliveries\n14 September 1997\n\nThe press has bundled the evening edition. Deliver one parcel to the Harbour Line terminal and two to the general store.",
    "source": "item:discipline"
  },
  {
    "type": "Notice",
    "title": "A letter from Nam Phuoc",
    "organisation": "Harbour notice board",
    "text": "A letter from Nam Phuoc\n12 September 1997\n\nDear Nils,\nThe rain arrived before breakfast. The sewing machine is behaving itself. I have put the last length of blue cloth aside. Write when you reach the next harbour.",
    "source": "item:vietnam"
  },
  {
    "type": "Notice",
    "title": "Evening edition",
    "organisation": "Harbour notice board",
    "text": "Minato Nippo · 14 SEPTEMBER 1997\nLocal baseball: Harbour 3, Mountain 2.\nThe harbour office remains staffed through the night.\nHarbour Line: check the terminal timetable for day and night services.\nA ginger cat has been seen near the ramen stall.",
    "source": "item:journal"
  },
  {
    "type": "Message",
    "title": "Brass key tag",
    "organisation": "Kenji’s pattern bench",
    "text": "KEY TAG\nThe stamping reads COLD STORE. The key is missing.",
    "source": "item:keychain"
  },
  {
    "type": "Message",
    "title": "Workshop calculator",
    "organisation": "Instruments",
    "text": "MEASUREMENT NOTES\n1. Record the known values.\n2. Keep the units consistent.\n3. Estimate the answer before calculating.\n4. Check the result.",
    "source": "item:stepwise"
  },
  {
    "type": "Message",
    "title": "Workshop parts ledger",
    "organisation": "Wall delivery shelf",
    "text": "Workshop parts ledger\nSeals, belts, bearings and four pencils.\n\n14 September 1997",
    "source": "item:github"
  },
  {
    "type": "Notice",
    "title": "Service certificates",
    "organisation": "Wall delivery shelf",
    "text": "Service certificates\nInspection stamps and neatly folded carbon copies.\n\n14 September 1997",
    "source": "item:linkedin"
  },
  {
    "type": "Message",
    "title": "Parcel for Sato",
    "organisation": "Wall delivery shelf",
    "text": "Parcel for Sato\nHousehold goods, wrapped in brown paper.\n\n14 September 1997",
    "source": "item:etsy"
  },
  {
    "type": "Message",
    "title": "Airmail envelope",
    "organisation": "Wall delivery shelf",
    "text": "Airmail envelope\nA letter from Nam Phuoc. The stamp has been carefully kept.\n\n14 September 1997",
    "source": "item:wordpress"
  },
  {
    "type": "Message",
    "title": "Johansson Town · 1:40",
    "organisation": "Kenji’s workshop",
    "text": "JOHANSSON TOWN\nA scale model of the old shopping street. 1:40. Handle with care.",
    "source": "item:model"
  },
  {
    "type": "Workbook",
    "title": "Harbour berth register",
    "organisation": "Harbour Office",
    "source": "workbook:berth-register",
    "text": "Call ID | Vessel | Berth | Arrival | Departure | Stay (hours) | Cargo | Status\nBR-8814-01 | Aoba Maru | East quay 1 | 32400.26388888889 | 32400.38888888889 | 3 | Fish boxes | Departed\nBR-8814-02 | Harbour launch | South jetty | 32400.354166666668 | 32400.708333333332 | 8.5 | Service equipment | Alongside\nBR-8814-03 | Midori | East quay 2 | 32400.416666666668 | 32400.729166666668 | 7.5 | General stores | Alongside\nBR-8814-04 | Shiosai | East quay 1 | 32400.708333333332 | 32401.25 | 13 | Paper and tea | Expected\nBR-8814-05 | Mellosa | Outer berth | 32400.770833333332 | 32401.354166666668 | 14 | Workshop supplies | Expected\nBR-8814-06 | Nam Phuoc | East quay 2 | 32401.375 | 32401.625 | 6 | Household goods | Expected"
  },
  {
    "type": "Workbook",
    "title": "Warehouse stock ledger",
    "organisation": "Harbour Office",
    "source": "workbook:warehouse-stock",
    "text": "Stock code | Item | Unit | Opening | Received | Issued | On hand | Minimum | Reorder qty\nWH-001 | Mooring line | Coils | 8 | 3 | 7 | 4 | 6 | 2\nWH-002 | Rubber fenders | Each | 12 | 4 | 3 | 13 | 8 | 0\nWH-003 | Fish boxes | Each | 120 | 40 | 115 | 45 | 60 | 15\nWH-004 | Printer paper | Reams | 9 | 5 | 4 | 10 | 6 | 0\nWH-005 | Work gloves | Pairs | 24 | 0 | 18 | 6 | 12 | 6\nWH-006 | Packing tape | Rolls | 15 | 12 | 8 | 19 | 10 | 0"
  },
  {
    "type": "Workbook",
    "title": "Marine service work log",
    "organisation": "Harbour Office",
    "source": "workbook:service-work-log",
    "text": "Job ID | Equipment | Work requested | Owner | Due date | Planned hours | Worked hours | Hours left | Closed date | State\nSV-001 | Quay light 2 | Replace lamp and test | Tetsuo | 32399 | 2 | 1 | 1 |  | Overdue\nSV-002 | Harbour launch | Check instrument panel | Kenji | 32400 | 4 | 2.5 | 1.5 |  | Open\nSV-003 | Office printer | Clean feed rollers | Tetsuo | 32400 | 1.5 | 1.5 | 0 | 32400 | Closed\nSV-004 | Warehouse trolley | Replace wheel bearing | Kenji | 32402 | 3 | 0 | 3 |  | Open\nSV-005 | Vessel records | File service certificates | Harbour master | 32401 | 2 | 1 | 1 |  | Open\nSV-006 | Quay hand pump | Inspect seals | Kenji | 32403 | 2.5 | 0 | 2.5 |  | Open"
  }
];
