title: "Nils Johansson Blog"
description: "A personal blog exploring engineering, travel, and cultural insights."
author: "Nils Johansson"
url: "https://nj22az.github.io"
# replace if you have a custom domain
baseurl: ""
# leave blank for GitHub Pages root

# Use the minima theme for a clean, minimalist blog
theme: minima

# Social links (shown in minima if provided)
twitter_username: yourhandle
github_username: nj22az
linkedin_username: nils-johansson-86744583

# Plugins
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
