"""Blender authoring source for the body-relative polo collar.
Run: blender -b --python tools/blender/build-contrast-polo.py
or: python tools/blender/build-contrast-polo.py (with Blender's bpy installed).
X is signed chest-width fraction; Y is torso-height fraction; Z is lift in metres.
The exported triangles are fitted to each avatar's torso by build.js, then joined
into the existing skinned body. No model download or extra draw call is required.
"""
import bpy, json, math
from pathlib import Path
root = Path(__file__).resolve().parents[2]
bpy.ops.object.select_all(action='SELECT'); bpy.ops.object.delete(use_global=False)
# A short pointed polo collar, deliberately separate from the open camp collar.
outline = [(0.10,1.025),(0.57,1.01),(0.79,.935),(0.38,.825),(0.17,.925)]
vertices=[]; faces=[]
for side in [-1,1]:
    pts=[(side*x,y,.010) for x,y in outline]
    # Fan triangles are subdivided in Blender to wrap onto different chest shapes.
    base=len(vertices); vertices.extend(pts)
    faces.extend([(base,base+i,base+i+1) for i in range(1,len(pts)-1)])
mesh=bpy.data.meshes.new('Contrast polo collar authoring mesh')
mesh.from_pydata(vertices,[],faces); mesh.update()
obj=bpy.data.objects.new('Contrast polo collar',mesh); bpy.context.collection.objects.link(obj)
bpy.context.view_layer.objects.active=obj;obj.select_set(True)
bpy.ops.object.mode_set(mode='EDIT');bpy.ops.mesh.select_all(action='SELECT');bpy.ops.mesh.subdivide(number_cuts=7);bpy.ops.mesh.quads_convert_to_tris();bpy.ops.object.mode_set(mode='OBJECT')
# Export the Blender-authored topology before displaying it on the reference torso.
coords=[list(v.co) for v in mesh.vertices]; indices=[i for p in mesh.polygons for i in p.vertices]
module=root/'src/avatars/contrast-polo-mesh.js'
module.write_text('// Generated by tools/blender/build-contrast-polo.py; edit the Blender source.\n'
                  'export const POLO_COLLAR = Object.freeze('+json.dumps({'vertices':coords,'indices':indices},separators=(',',':'))+');\n')
prof=[(1,.66),(.985,.74),(.95,.8),(.88,.87),(.76,.93),(.58,.98),(.38,1.01),(.19,1.03),(0,1.04)]
def radius(t):
    for (r0,t0),(r1,t1) in zip(prof,prof[1:]):
        if t<=t1:return r0+(r1-r0)*(t-t0)/(t1-t0)
    return 0
for v in mesh.vertices:
    f,t,lift=v.co; r=radius(t)
    v.co=(f*.18*r,.5+t*.5,.115*r*math.sqrt(max(0,1-f*f))+lift)
solid=obj.modifiers.new('Cloth thickness','SOLIDIFY');solid.thickness=.003
mat=bpy.data.materials.new('Ivory knit');mat.diffuse_color=(.92,.90,.85,1);obj.data.materials.append(mat)
obj['runtime_asset']='src/avatars/contrast-polo-mesh.js'
obj['fitting']='Body-relative coordinates fitted to all heights and builds, chest bone.'
bpy.ops.wm.save_as_mainfile(filepath=str(root/'art/avatars/contrast-polo-collar.blend'))
print('Exported',len(coords),'vertices and',len(indices)//3,'triangles')
