"""The single Week 40 entry point. Schedule remains available as a secondary view."""

def page(w, schedule):
    lessons = [('franskiljning', 'Måndag först', 'Frånskiljning och mätteknik', 'Fyra uppgifter med figur och instrumentkort på plats.'),
               ('sinus', 'Del 1', 'Sinus och mätvärden', 'Periodtid, toppvärde och effektivvärde. Läs, följ exemplet och räkna själv.'),
               ('impedans', 'Del 2', 'Spole, motstånd och ström', 'Reaktans, impedans och ström. Förklaringen kommer före varje ny typ av uppgift.'),
               ('effekt', 'Del 3', 'Effekt och effektfaktor', 'Aktiv och skenbar effekt, matningsström och kompensering.')]
    rows = ''.join(f'<li id="{id_}" data-lesson="{id_}"><h3>{number}: {title}</h3><p>{text}</p><p class="lesson-progress" aria-live="polite">Inte påbörjad</p><a class="sj-btn" href="Genomgang.html?del={id_}&amp;fortsatt=1">Öppna {title.lower()}</a></li>' for id_, number, title, text in lessons)
    return f'''<!doctype html><html lang="sv"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vecka 40 · Frånskiljning och växelström · Sjöskolan</title><link rel="canonical" href="https://nj22az.github.io/sjoskolan/vecka-40/aktuell/"><link rel="icon" href="/assets/images/apple-touch-icon.png"><link rel="stylesheet" href="../../gemensamt/sjoskolan.css?v=20260926"><link rel="stylesheet" href="../../course.css?v=20260930d"><link rel="stylesheet" href="arbetsrum.css?v=20260927b"><script src="/sjoskolan/gemensamt/oversattning.js?v=20260927" defer></script><script type="module" src="dagplan.mjs?v=20260927b"></script></head>
<body class="course"><nav class="school-nav" aria-label="Sjöskolan"><a href="/sjoskolan/"><strong>SJÖSKOLAN</strong></a><a href="/sjoskolan/#veckor">Alla veckor</a></nav><main id="main-content" class="study-main">
<header><p class="study-kicker">Vecka 40 · 28 september–2 oktober 2026</p><h1>Frånskiljning och växelström</h1><p>Läs en kort förklaring, följ ett exempel och gör ett eget försök. Underlag och hjälp finns i samma arbetsrum.</p><div id="nu" class="study-panel"><p id="resume-text">Börja med måndagens frånskiljning och mätteknik.</p><a id="resume" class="sj-btn primary large" href="Genomgang.html?del=franskiljning">Börja här</a></div><p class="study-note">Avsnitt markeras automatiskt som genomgångna. Övningarna visar rätt svar, sparat försök eller behov av hjälp. Framstegen sparas i den här webbläsaren.</p></header>
<section aria-labelledby="ordning"><h2 id="ordning">Din arbetsgång</h2><ol class="study-lessons">{rows}</ol></section>
<section class="study-stage" id="labb"><h2>Efter del 1–3: guidad labb</h2><p>Använd det du har lärt dig i åtta labbuppgifter. Förutsäg, läs av och förklara.</p><a class="sj-btn" href="../../vaxelstromslabbet/?lage=guidad">Öppna växelströmslabbet</a></section>
<section class="study-stage" id="inlamning"><h2>Lämna in senast söndag 4 oktober</h2><ol><li><a href="Inlamning.html">Växelström, uppgift 1–4</a></li><li><a href="../../vecka-38/aktuell/Inlamning.html">Frånskiljning och mätteknik, uppgift 1–3</a></li></ol><p>Lämna via den kanal läraren har anvisat. <a href="Resultat.html">Skicka resultat med QR-koden</a> efter lektionen. Skriftliga övningssvar kan skrivas ut från arbetsrummet.</p></section>
<details class="study-resources" id="schema"><summary>Schema: vad gör vi på lektionen och hemma?</summary>{schedule}</details>
<details class="study-resources"><summary>Presentationer, filmer och uppslagsmaterial</summary><p><a href="../../bildspel/">Bildspel, PowerPoint och PDF</a> · <a href="Kortfilmer.html">Korta filmer</a> · <a href="Beteckningar.html">Beteckningar</a> · <a href="../../gemensamt/Raknehjalp.html">Räknarhjälp</a></p><p>Varje lektion har också dessa länkar under ”Film, utskrift och mer att läsa”.</p></details>
</main><footer class="school-nav">Sjöskolan · Elteknik och ellära · Nils Johansson</footer></body></html>'''
