import {buildPlane,AIRPORT_ISLAND} from '../world/airport-island.js';
import {airportWorld} from '../world/airport-ground.js';
import * as THREE from '../../vendor/three.module.js';
import {AIRPORT_LANDING,AIRPORT_HEIGHT,AIRPORT_COUNTER} from '../world/airport-ground.js';
import {islandState,buyFerry,ferryArrival,buyFlight,checkIn,boardFlight,flightArrival,finishRepair,completeProject,DEVELOPMENT_PROJECTS,projectReady,stamp,flightTimes} from './services.js';
export const NAHA_ARRIVALS={id:'naha-airport-arrivals',title:'Naha Commuter Arrivals',jp:'Naha Commuter Arrivals',sub:'RETURN CONNECTION · KITANO-JIMA',x:AIRPORT_COUNTER[0],z:AIRPORT_COUNTER[1],exitPosition:[AIRPORT_COUNTER[0],AIRPORT_HEIGHT,AIRPORT_COUNTER[1]],entryFacing:0,line:'A small domestic arrivals room. Your return ticket takes you back to Kitano-jima.'};
/** Ticketing and physical ferry crossing. Mid-crossing saves retain the last safe shore. */
export function createIslandPlay({world,player,camera,activities,getMinutes,getRain,passTime,place,enterNaha,leaveNaha}){
 let ride=null;const a=activities,state=a.state,s=islandState(state);
 const thuan=world.people.find(p=>p.profile?.name==='Thuan'||p.g.userData.name==='Thuan')?.g;if(thuan)thuan.userData.alternativeOutfit=state.thuanOutfit==='nozomi'?'nozomi':'clothes';
 const boat=new THREE.Group();boat.name='Kitano-jima passenger launch';boat.userData.dynamicProp=true;boat.visible=false;world.group.add(boat);const aircraft=buildPlane();aircraft.name='Boarded commuter aircraft';aircraft.userData.dynamicProp=true;aircraft.visible=false;world.group.add(aircraft);
 for(const [size,pos,c] of [[[3.4,.7,7],[0,0,0],0x3c6880],[[3,.12,6],[0,.45,0],0xd6c8a6],[[2.6,1.9,2.6],[0,1.4,-1.1],0xe0d9c2],[[2.3,.6,.04],[0,1.7,.23],0x496c77]]){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),new THREE.MeshStandardMaterial({color:c,roughness:.8}));m.position.set(...pos);boat.add(m);}
 const result=(title,r,back)=>{a.save();if(!r.ok){a.menu(title,r.message,[['Back',back]]);return false;}return true;};
 function crossing(location){if(ride)return;const from=location==='airport'?[2,-60]:AIRPORT_LANDING,to=location==='airport'?AIRPORT_LANDING:[2,-60];a.close();ride={kind:'ferry',from,to,location,elapsed:0,duration:18};boat.visible=true;player.position.set(from[0],.65,from[1]);a.save();}
 function fly(location){a.close();const ground=airportWorld(0,-4),air=airportWorld(95,-4);ride={kind:'flight',from:location==='naha'?ground:air,to:location==='naha'?air:ground,location,elapsed:0,duration:12};aircraft.visible=true;a.save();}
 function ferry(home=false){const j=s.journey;a.menu(home?'Kitano-jima → Minato':'Minato → Kitano-jima','Local airport ferry · 18-minute crossing.\nReturn fare ¥400. The return journey remains valid until used.\nThe terminal counter and passenger walkway are open all day.',[[j.roundTrip?'Board the local ferry':'Buy return ticket · ¥400',()=>{if(!j.roundTrip){if(!result('Airport ferry',buyFerry(state,getMinutes()),()=>ferry(home)))return;ferry(home);}else crossing(home?'town':'airport');}],['Stay here',a.close]]);}
 function counter(){const j=s.journey,now=getMinutes(),times=flightTimes(state).map(stamp).join(' · ');const buttons=[];if(j.ticket===null)buttons.push(['Buy Naha return ticket · ¥800',()=>{if(result('Commuter flight',buyFlight(state,getMinutes(),getRain()),counter))counter();}]);else if(!j.checked)buttons.push(['Check in with one cabin bag',()=>{if(result('Check-in',checkIn(state,getMinutes(),getRain()),counter))counter();}]);else buttons.push(['Board the Naha commuter flight',()=>{const r=boardFlight(state,getMinutes(),getRain());if(r.wait){a.menu('Waiting for the commuter flight',r.message,[['Wait until departure',()=>{passTime(r.wait);counter();}],['Keep exploring',a.close]]);return;}if(!result('Boarding',r,counter))return;fly('naha');}]);buttons.push(['Back to the passenger walkway',a.close]);a.menu('Kitano-jima Airport','Island commuter service · 1997 · Terminal district expanding\nDepartures: '+times+'\nCheck-in closes ten minutes before departure.\n'+(getRain()?'Heavy rain: flights suspended; tickets remain valid.':'Weather permitting, twin-prop aircraft serve Naha.')+(j.ticket!==null?'\nYour flight: '+stamp(j.ticket)+(j.checked?' · checked in':' · check-in required'):''),buttons);}
 function projects(){const buttons=DEVELOPMENT_PROJECTS.filter(p=>!s.projects.includes(p.id)).map(p=>[p.title+' · ¥'+p.budget,()=>{const r=completeProject(state,p.id,getMinutes());if(result('Island development',r,projects))projects();}]);buttons.push(['Back to town',a.close]);a.menu('Island development programme','Town treasury: ¥'+s.treasury+'\nCompleted: '+(s.projects.join(', ')||'none')+'\n\n'+DEVELOPMENT_PROJECTS.map(p=>p.title+'\n'+p.text+'\n'+(s.projects.includes(p.id)?'Completed':projectReady(state,p)?'Service requirement met':'Needed: '+({repair:'complete the airport radio service at the docks',flight:'complete an outbound commuter flight',visits:'make two airport ferry visits'}[p.requires]))).join('\n\n')+'\n\nEvery completed project files its decision, works order, completion, invoice, payment and ledger posting at the Community Hall.',buttons);}
 function action(kind,title,data){if(ride)return true;if(kind==='thuan-wardrobe'){a.menu('Thuan’s wardrobe','Keep Thuan’s own face and hairstyle. The alternative outfit follows the reference: cream long sleeves, red plaid skirt and brown boots.',[['Wear the Nozomi-inspired outfit',()=>{state.thuanOutfit='nozomi';if(thuan)thuan.userData.alternativeOutfit='nozomi';a.save();a.close();}],['Wear Thuan’s usual outfit',()=>{state.thuanOutfit='clothes';if(thuan)thuan.userData.alternativeOutfit='clothes';a.save();a.close();}],['Keep exploring',a.close]]);return true;}if(kind==='airport-shop'||kind==='rainflower-shop'){a.menu(title,'A local shop on the airport promenade. Open during the terminal expansion.',[['Buy '+data.item+' · ¥'+data.price,()=>{if(!a.spend(data.price))return;state.inventory.push(data.item);a.save();a.close();}],['Keep exploring',a.close]]);return true;}if(kind==='airport-ferry'){ferry();return true;}if(kind==='airport-return'){ferry(true);return true;}if(kind==='airport-counter'){counter();return true;}if(kind==='island-projects'){projects();return true;}if(kind==='island-repair'){a.menu('Airport ground-service radio','Tetsuo supervises a service test: isolate the supply, inspect the cable, check the reference signal and record the result.',[[s.repair?'Review completed test':'Complete the supervised service test',()=>{finishRepair(state,getMinutes());a.save();passTime(15);a.menu('Airport radio service complete','The work order, test sheet and maintenance posting are filed in the Community Hall. The radio can return to service.',[['Back to the docks',a.close]]);}],['Leave it for now',a.close]]);return true;}if(kind==='island-shop'){a.menu('Hoshizaki General Store','Rice crackers, island tea and postcards. The fishing families collect their daily supplies here.',[['Buy island tea · ¥100',()=>{if(!a.spend(100))return;state.inventory.push('Hoshizaki island tea');a.save();a.close();}],['Ask about the village',()=>a.menu('Hoshizaki','Fishing boats land their catch each morning. The family guesthouse opens when the town completes its visitor programme.',[['Thank you',a.close]])],['Keep walking',a.close]]);return true;}if(kind==='island-bus'){a.menu('Coastal Harbour Line',s.projects.includes('bus')?'The local coastal service returns to Minato. Town-funded service; no fare.':'The village bus service awaits the town development programme.',s.projects.includes('bus')?[['Ride back to Minato',()=>{a.close();passTime(30);place(0,30);}],['Keep walking',a.close]]:[['Keep walking',a.close]]);return true;}return false;}
 return {action,get active(){return !!ride;},tick(dt){world.airportIsland?.setDepartures(flightTimes(state));world.islandLandscape?.update(state,getMinutes());world.traditionalGarden?.update(getMinutes()*60);world.shoppingLane?.update(getRain());if(!ride)return;ride.elapsed+=Math.max(0,dt);const t=Math.min(1,ride.elapsed/ride.duration),u=t*t*(3-2*t),x=ride.from[0]+(ride.to[0]-ride.from[0])*u,z=ride.from[1]+(ride.to[1]-ride.from[1])*u;const flying=ride.kind==='flight',y=flying?2+(ride.location==='naha'?u*u:(1-u)*(1-u))*22:0;const vehicle=flying?aircraft:boat;vehicle.position.set(x,flying?y:-.1,z);vehicle.rotation.y=flying?AIRPORT_ISLAND.yaw:Math.atan2(ride.to[0]-ride.from[0],ride.to[1]-ride.from[1]);player.position.set(x,y+.7,z);camera.position.set(x-9,y+6,z+13);camera.lookAt(x,y+1,z);if(t>=1){const destination=ride.location,kind=ride.kind;ride=null;boat.visible=false;aircraft.visible=false;passTime(kind==='flight'?45:18);if(kind==='flight'){flightArrival(state,destination,getMinutes());place(...AIRPORT_COUNTER);a.save();if(destination==='naha')enterNaha();}else{ferryArrival(state,destination,getMinutes());a.save();const p=destination==='airport'?AIRPORT_LANDING:[2,-60];place(...p);}}},returnFlight(){a.close();s.journey.location='airport';leaveNaha();fly('airport');},recover(){if(s.journey.location==='airport')place(...AIRPORT_LANDING);else if(s.journey.location==='naha')enterNaha();},snapshot(){return {location:s.journey.location,crossing:ride?{destination:ride.location,progress:ride.elapsed/ride.duration}:null,ticket:s.journey.ticket,checked:s.journey.checked,projects:s.projects,treasury:s.treasury};}};
}
