import {fileDocument,restoreArchive} from '../office/archive.js';
export const FLIGHT_TIMES=[555,760,975,1140];
export const DEVELOPMENT_PROJECTS=[
 {id:'cargo',title:'Harbour and airport cargo shelter',budget:18000,requires:'repair',text:'A covered cargo bay protects parcels, fish boxes and airport maintenance supplies.'},
 {id:'bus',title:'Coastal village bus service',budget:24000,requires:'flight',text:'The Harbour Line gains a local coastal service to Hoshizaki and West Cape.'},
 {id:'guesthouse',title:'Hoshizaki guesthouse and morning flight',budget:32000,requires:'visits',text:'A small family guesthouse opens; an additional 11:00 commuter flight serves the island.'},
];
export function restoreIsland(saved){const s=saved||{};return {v:1,projects:DEVELOPMENT_PROJECTS.filter(p=>Array.isArray(s.projects)&&s.projects.includes(p.id)).map(p=>p.id),treasury:Number.isFinite(s.treasury)?Math.max(0,s.treasury):90000,repair:s.repair===true,flights:Number.isSafeInteger(s.flights)?Math.max(0,s.flights):0,visits:Number.isSafeInteger(s.visits)?Math.max(0,s.visits):0,journey:s.journey&&['town','airport','naha'].includes(s.journey.location)?{location:s.journey.location,roundTrip:s.journey.roundTrip===true,ticket:Number.isFinite(s.journey.ticket)?s.journey.ticket:null,checked:s.journey.checked===true}: {location:'town',roundTrip:false,ticket:null,checked:false}};}
export function islandState(state){return state.island??=restoreIsland();}
export function flightTimes(state){return islandState(state).projects.includes('guesthouse')?[...FLIGHT_TIMES,660].sort((a,b)=>a-b):FLIGHT_TIMES;}
export function nextFlight(now,state){const day=Math.floor(now/1440)*1440,times=flightTimes(state);return times.map(t=>day+t).find(t=>t>=now)??day+1440+times[0];}
export function stamp(m){const n=((m%1440)+1440)%1440;return String(Math.floor(n/60)).padStart(2,'0')+':'+String(Math.floor(n%60)).padStart(2,'0');}
function paper(state,spec,now){state.documentArchive??=restoreArchive();return fileDocument(state,{organisation:'Island Transport Office',author:'Harbour master',...spec},now);}
export function buyFerry(state,now){const s=islandState(state);if(s.journey.roundTrip)return {ok:true,already:true};if(state.yen<400)return {ok:false,message:'The return ferry ticket costs ¥400.'};state.yen-=400;s.journey.roundTrip=true;paper(state,{type:'Receipt',title:'Airport ferry return ticket',source:'FERRY-'+now,amount:400,text:'AIRPORT FERRY\nOne return passenger fare: ¥400\nRoute: Minato — Kitano-jima\nThe return crossing remains valid until used.'},now);return {ok:true};}
export function ferryArrival(state,location,now){const s=islandState(state);s.journey.location=location;if(location==='airport')s.visits++;if(location==='town')s.journey.roundTrip=false;paper(state,{type:'Schedule',title:'Airport ferry passenger entry',source:'FERRY-ARRIVAL-'+now+'-'+location,text:'PASSENGER RECORD\nOne passenger arrived at '+(location==='airport'?'Kitano-jima':'Minato')+' at '+stamp(now)+'.'},now);}
export function buyFlight(state,now,rain=false){const s=islandState(state);if(rain)return {ok:false,message:'Flights are suspended in heavy rain. The ferry can take you back to town.'};if(s.journey.ticket!==null)return {ok:true,already:true};if(state.yen<800)return {ok:false,message:'The same-day return flight costs ¥800.'};state.yen-=800;s.journey.ticket=nextFlight(now+10,state);s.journey.checked=false;const ref='AIR-'+now;const receipt=paper(state,{type:'Receipt',title:'Naha commuter return ticket',source:ref,transaction:ref,amount:800,text:'KITANO-JIMA AIR SERVICES\nOne return passenger fare: ¥800\nDestination: Naha\nDeparture: '+stamp(s.journey.ticket)+'\nCheck-in closes ten minutes before departure.'},now);paper(state,{type:'Ledger entry',title:'Flight ticket sales posting',source:ref+'-ledger',transaction:ref,amount:800,links:[receipt.id],text:receipt.text},now);return {ok:true};}
export function checkIn(state,now,rain=false){const s=islandState(state);if(rain)return {ok:false,message:'Flights are suspended. Your ticket remains valid for the next available service.'};if(s.journey.ticket===null)return {ok:false,message:'Buy a ticket at the counter first.'};if(now>s.journey.ticket-10&&!s.journey.checked){s.journey.ticket=nextFlight(now+10,state);return {ok:false,message:'Check-in has closed. Your ticket was moved to '+stamp(s.journey.ticket)+' without another charge.'};}s.journey.checked=true;paper(state,{type:'Handover',title:'Commuter flight check-in',source:'CHECK-IN-'+s.journey.ticket,text:'CHECK-IN\nOne passenger; one cabin bag.\nDeparture '+stamp(s.journey.ticket)+'\nGate: passenger walkway.'},now);return {ok:true};}
export function boardFlight(state,now,rain=false){const s=islandState(state);if(rain)return {ok:false,message:'The flight is suspended. Keep your ticket or use the ferry home.'};if(!s.journey.checked||s.journey.ticket===null)return {ok:false,message:'Check in before boarding.'};if(now<s.journey.ticket)return {ok:false,wait:s.journey.ticket-now,message:'Boarding begins at '+stamp(s.journey.ticket)+'.'};if(now>s.journey.ticket+10){s.journey.ticket=nextFlight(now+10,state);s.journey.checked=false;return {ok:false,message:'The flight has left. Your ticket is valid for the next service; check in again.'};}return {ok:true};}
export function flightArrival(state,location,now){const s=islandState(state);s.journey.location=location;if(location==='naha')s.flights++;else{s.journey.ticket=null;s.journey.checked=false;}paper(state,{type:'Schedule',title:'Commuter flight arrival',source:'FLIGHT-ARRIVAL-'+now+'-'+location,text:'FLIGHT RECORD\nOne passenger arrived at '+(location==='naha'?'Naha':'Kitano-jima')+' at '+stamp(now)+'.'},now);}
export function finishRepair(state,now){const s=islandState(state);if(s.repair)return false;s.repair=true;const ref='AIRPORT-RADIO-001',order=paper(state,{type:'Order',title:'Airport radio repair work order',source:ref,transaction:ref,quantity:1,text:'WORK ORDER\nRepair one airport ground-service radio.\nAssigned to: Dock Electrical & Repair Workshop.\nRequirement: isolate supply, inspect cable, check zero and reference signal.'},now);const report=paper(state,{type:'Handover',title:'Airport radio test sheet',source:ref+'-test',transaction:ref,links:[order.id],text:'TEST SHEET\nSupply isolated: yes\nCable inspected: yes\nReference signal checked: yes\nResult: passed; radio returned to airport service.\nWitness: Tetsuo.'},now);paper(state,{type:'Ledger entry',title:'Workshop maintenance posting',source:ref+'-ledger',transaction:ref,links:[order.id,report.id],amount:0,text:'Airport radio maintenance completed. Town-owned equipment; no passenger charge.'},now);return true;}
export function projectReady(state,p){const s=islandState(state);return p.requires==='repair'?s.repair:p.requires==='flight'?s.flights>0:s.visits>=2;}
export function completeProject(state,id,now){const s=islandState(state),p=DEVELOPMENT_PROJECTS.find(p=>p.id===id);if(!p||s.projects.includes(id))return {ok:false,message:'This project is already complete.'};const prior=DEVELOPMENT_PROJECTS.slice(0,DEVELOPMENT_PROJECTS.indexOf(p));if(prior.some(q=>!s.projects.includes(q.id))||!projectReady(state,p))return {ok:false,message:'Complete the preceding project and its island service requirement first.'};if(s.treasury<p.budget)return {ok:false,message:'The town treasury cannot cover this project.'};s.treasury-=p.budget;s.projects.push(id);const ref='ISLAND-PROJECT-'+id;const minutes=paper(state,{type:'Minutes',title:'Town development decision — '+p.title,source:ref,transaction:ref,text:'COMMUNITY HALL\nProject approved: '+p.title+'\nBudget: ¥'+p.budget+'\nEvidence: radio repair '+s.repair+', completed outbound flights '+s.flights+', airport visits '+s.visits+'.\n'+p.text},now);const order=paper(state,{type:'Order',title:p.title+' — works order',source:ref+'-order',transaction:ref,quantity:1,amount:p.budget,links:[minutes.id],text:'WORKS ORDER\n'+p.title+'\nOne completed project: ¥'+p.budget},now);const delivery=paper(state,{type:'Delivery note',title:p.title+' — completion',source:ref+'-delivery',transaction:ref,quantity:1,links:[order.id],text:'COMPLETION RECORD\nOne completed project inspected and accepted by the town clerk.'},now);const invoice=paper(state,{type:'Invoice',title:p.title+' — invoice',source:ref+'-invoice',transaction:ref,quantity:1,amount:p.budget,links:[order.id,delivery.id],text:'INVOICE\nOne completed project: ¥'+p.budget},now);const receipt=paper(state,{type:'Receipt',title:p.title+' — treasury payment',source:ref+'-payment',transaction:ref,amount:p.budget,links:[invoice.id],text:'PAYMENT RECEIPT\nTown treasury paid ¥'+p.budget+'\nBalance: ¥'+s.treasury},now);paper(state,{type:'Ledger entry',title:p.title+' — ledger posting',source:ref+'-posting',transaction:ref,amount:p.budget,links:[receipt.id],text:'Town development payment: ¥'+p.budget+'; treasury balance ¥'+s.treasury},now);return {ok:true};}
