import * as THREE from '../the-front-row-seat/pelican/vendor/three.module.min.js';
export const DIALOGUE={
 Aiko:[['books','The Swedish engineer keeps leaving historical novels here as if they were spare parts.'],['shelf','Six books. The shelf has requested a structural assessment.'],['century','Which century did you like? The seventeenth leaks through the shutters.','book'],['job','So he does have a real job. I assumed he only wrote about captains.','cv'],['cat','Tama has not read them. He reviews the binding by sleeping on it.'],['rain','Please leave the rain outside. The histories have enough disasters.'],['chair','The window chair is free. Twenty seconds of peace is an excellent bargain.'],['water','The harbour office tray is towards the water. Documents, not treasure.']],
 Kenji:[['delivery','This trolley steers beautifully towards whichever ankle is nearest.'],['folio','Harbour office tray, unless the wind took it. Look for the blue tape.'],['game','One perfect Star Port run and I will show you the workshop. No charge for directions.'],['book','I delivered those books. My back now has a historical perspective.','book'],['part','A keychain without keys. Sensible. Nothing to lose yet.','keychain'],['map','The workshop is on your left. Unless you face the other way.'],['weather','Rain is just the harbour making a delivery inland.'],['model','Don’t drop it. We’re inside.']],
 'Mrs Sato':[['stock','I sell many useful things. You seem determined to pick up paper.'],['homes','Stora Mellösa. Nam Phuoc. Two homes is not the same as no home.','cv'],['bligh','A captain is easier to judge from a dry chair.','bligh'],['fish','That fish is not becoming fresher while we discuss it.'],['food','Umeboshi rice ball. Eighty yen. Twenty seconds of renewed purpose.'],['book','Six books? He should charge by the kilogram.'],['weather','The noren is not an umbrella. Visitors continue to test this.'],['home','Leave things where you found them. A town runs on this small miracle.']],
 'Harbour master':[['obvious','Did you check the obvious thing twice? Good. Now check the connector.'],['folio','It is a document, not a relic. Put it back in the tray.'],['pattern','I still prefer a wooden pattern and a sharp pencil.','keychain'],['bligh','Read the Bligh paper? Command is not the same thing as shouting.','bligh'],['commission','Commissioning: prove it works before everyone goes home.'],['diagnostics','A useful fault report begins with what happened. Not what you hoped happened.'],['tide','The tide has not read the work order. Allow for this.'],['radio','Harbour Service, 82.1. Clear instructions. Mostly clear reception.']],
 'Bus driver':[['time','The timetable is optimistic. I admire that in paper.'],['stop','This is the Harbour Line. The bus is the part currently missing.'],['book','Those Swedish books need their own ticket.','book'],['cv','Two bases? I have two stops. It is not quite the same.','cv'],['rain','A wet timetable is still wrong.'],['route','Station that way. Harbour the other way. I keep it simple.']],
 'Cold-storage kid':[['ice','Ice. Twenty yen. Briefly solid.'],['books','The Swedish books weigh more than the fish.'],['paper','The Bligh paper is dry. That is already a good voyage.','bligh'],['key','That blank could label the freezer key. We have lost the label twice.','keychain'],['shift','Night shift. The fish keep very unsociable hours.'],['home','Go home before you smell like your work.']]
};
export function createCastAI({world,player,state,paused,collides}){
 const schedules={
  Aiko:[[4.3,35,'dusting The Venture'],[4.3,34,'shelving The Venture'],[4.3,33,'closing the half-shutter']],
  Kenji:[[-3.5,17,'wheeling deliveries'],[4.5,21,'losing at Star Port'],[4.5,30,'collecting the bicycle']],
  'Mrs Sato':[[-4.2,-26,'opening the noren'],[-4.4,25,'reading the newspaper'],[-4.2,-26,'counting the till']],
  'Harbour master':[[1.6,-70,'watching the tide'],[4.2,-48,'posting a tide notice'],[1.6,-75,'taking a smoke break']],
  'Bus driver':[[-4.5,44,'waiting at Harbour Line'],[-4.5,44,'checking the timetable'],[-4.5,44,'waiting for the last service']],
  'Cold-storage kid':[[-8,-55,'checking ice'],[-8,-55,'checking ice'],[-8,-55,'working the night shift']]
 };
 for(const p of world.people)p.g.userData.scheduled=true;
 let catIndex=0;
 const catPath=[[4,35],[4,-47],[-7.2,-53]];
 const move=(g,x,z,dt)=>{const dx=x-g.position.x,dz=z-g.position.z,d=Math.hypot(dx,dz);if(d<.08)return;const step=Math.min(d,dt*.85),nx=g.position.x+dx/d*step,nz=g.position.z+dz/d*step;if(!collides(nx,nz,.22)){g.position.set(nx,0,nz);}else if(!collides(g.position.x,nz,.22)){g.position.z=nz;}else if(!collides(nx,g.position.z,.22)){g.position.x=nx;}g.rotation.y=Math.atan2(-dx,-dz);};
 return {update(dt,minutes,rain){const h=minutes/60%24,phase=h<11?0:h<17?1:2;
  for(const p of world.people){const g=p.g,s=schedules[g.userData.name];if(!s)continue;let [x,z,activity]=s[phase];if(rain){x=g.userData.name==='Harbour master'?-7.2:Math.sign(x)*4.5;z=g.userData.name==='Harbour master'?-53:z;activity='sheltering from rain';}g.visible=g.userData.name!=='Cold-storage kid'||h>=17||h<7;g.userData.activity=activity;if(paused())continue;if(g.userData.name==='Kenji'&&state().kenjiEscort==='walking'){x=-7.3;z=-57.5;if(g.position.distanceTo(player.position)>6)continue;if(Math.hypot(g.position.x-x,g.position.z-z)<.3){state().kenjiEscort='done';g.userData.activity='showing the workshop';}}
   // Use the open centre of the street for long journeys before approaching a frontage.
   if(Math.abs(g.position.z-z)>3&&Math.abs(g.position.x)>3)x=Math.sign(g.position.x)*2.6;
   move(g,x,z,dt);
  }
  if(!paused()&&world.cat){const cat=world.cat,s=state();let goal=catPath[catIndex];if(rain)goal=[4.8,33];else if(s.inventory.includes('Mackerel')||s.inventory.includes('Sea bream')||s.quest===2)goal=[player.position.x+.7,player.position.z+.7];else if(s.quest===1)goal=[-4,-18];else if(h<10)goal=[-4,-18];else if(h>=17)goal=[-1.6,-76];else if(Math.hypot(cat.position.x-goal[0],cat.position.z-goal[1])<.4)catIndex=(catIndex+1)%catPath.length;move(cat,...goal,dt);}
 },pose(dt){for(const p of world.people){const a=p.g.userData.character;if(!a||a.speed>.12)continue;const mode=p.g.userData.activity||'';a.rig.torso.rotation.z=Math.sin(performance.now()*.0008+p.index)*.008;if(/dusting|posting|checking|counting/.test(mode)){a.rig.arms[1].shoulder.rotation.x=-.35;a.rig.arms[1].elbow.rotation.x=-.45;}if(/smoke|watching/.test(mode)){a.rig.arms[1].shoulder.rotation.x=-.65;a.rig.arms[1].elbow.rotation.x=-.85;}if(p.g.position.distanceTo(player.position)<3)a.rig.head.rotation.y=THREE.MathUtils.clamp(Math.sin(p.g.rotation.y-Math.atan2(player.position.x-p.g.position.x,player.position.z-p.g.position.z)),-.35,.35);}}};
}
