// Snapshot: homepage config.js and reader index.html, 7 September 2026.
// Journal full text is not bundled: cards explicitly direct readers to the journal.
export const ROOT='https://nj22az.github.io';
export const JOURNAL=[
  ['17 November 2025','More Survivor Than Tyrant: The Captain Bligh You Don’t Know'],
  ['16 November 2025','The Discipline of Building Something That Lasts'],
  ['10 November 2025','Vietnam']
];
export const BOOKS=['The Venture','The Gallows Years','Kings of Bengal','The Poppy',"The Watchman’s Daughter",'The Engine Room'];
export const ITEMS=[
  {id:'book',title:'The Front-Row Seat',kind:'book',place:'Bookshop · Johansson Street',pos:[5.25,1.12,35.5],color:0x633f36,url:ROOT+'/the-front-row-seat/',action:'Open the full reader',note:'Opened The Venture. Five centuries; six volumes.',pages:[
    ['THE VENTURE','Book One · 1603–1635\nThe Front-Row Seat\nNils Johansson\n\nSix books. Five centuries.\nRead in the chair by the window.'],
    ['FOREWORD','I am an engineer, not a historian. I have spent most of my working life at sea and in the yards and engine rooms of other people’s countries. This book is fiction. I want to say that plainly, before you start.'],
    ['FOREWORD · continued','The people in it never existed. Tom, Maggie, Daniel, Su — I made them up, and their names too.\n\nBut the history is real. The Company sailed. The docks burned. Ten million people starved while the account books balanced. Those things happened, to people who were not invented.'],
    ['THE PELICAN · 1603','The rain has not let up in three days. It comes in cold off the North Sea, turns the mud of Wapping Wall to something a man could lose a boot in, and beats against the tavern shutters with the force of thrown gravel.'],
    ['CHAPTER ONE','Inside the Pelican, the fire is built high, and the room holds its regulars the way the river holds its craft, each at a known mooring.\n\nThe house will wear other names before the river is done with it — the Devil’s Tavern, the Prospect of Whitby — but in this first year of the Company it is the Pelican, and its shutters hold.'],
    ['CONTINUE READING','This is a short extract from the published reader.\n\nThe Venture is approximately 100,000 words. The complete illustrated omnibus opens through “Open the full reader”.']
  ]},
  {id:'cv',title:'NILS JOHANSSON — FIELD NOTES / CV',kind:'folio',place:'Harbour office · Quayside',pos:[-8.1,1.02,-53.2],color:0xded5bb,action:'Copy contact path',note:'CV found in the harbour tray. Sweden and Vietnam.',pages:[
    ['NILS JOHANSSON','FIELD NOTES / CV\nField Service Engineer · Marine Systems\n\nMarine engineer turned field service engineer, working across maritime systems, precision material testing, and industrial commissioning.\n\nHands-on diagnostics. Structured delivery. Clear documentation. Cross-cultural collaboration.\n\nBASES\nStora Mellösa, Sweden\nNam Phuoc, Vietnam\n\nAVAILABILITY · Week 37 snapshot\nMon–Fri, office hours. Not available on public holidays. Check the homepage for current availability.'],
    ['SELECTED WORK','The Front-Row Seat · six-book illustrated historical omnibus.\nForm 3D Studio · private browser tools; STL & STEP.\nMizuhama 1988 · Three.js harbour adventure.\nStepWise · step-by-step engineering calculator.\nGitHub · open-source tools and prototypes.\nLinkedIn · professional work.\nEtsy · products and field templates.\nWordPress · technical and cultural dispatches.\n\nJOURNAL\nMore Survivor Than Tyrant: The Captain Bligh You Don’t Know\nThe Discipline of Building Something That Lasts\nVietnam\n\nCompiled from the public homepage; not a formal employment record.']
  ]},
  ...JOURNAL.map(([date,title],i)=>({id:['bligh','discipline','vietnam'][i],title,kind:'paper',place:i===2?'Notice board · Harbour approach':'Field Notes rack · Journal Press',pos:i===2?[5.6,1.4,-48.1]:[-5.4,1.2,-.4-i*1.25],color:0xd8cbb0,url:ROOT+'/blog/',action:'Read full dispatch',note:'Read Field Note: '+title,pages:[[title,date+'\n\n'+(i===2?'AIRMAIL · NAM PHUOC\n\n':'FIELD NOTES\n\n')+'Featured on The Office of Nils Johansson.\n\nThe full dispatch is on the journal. Its article text is not bundled in this street edition.']]})),
  {id:'journal',title:'Read all posts',kind:'paper',place:'Notice board · Harbour approach',pos:[5.5,1.25,-46.6],color:0xcac5aa,url:ROOT+'/blog/',note:'Located the complete journal.',pages:[['FIELD NOTES','Read all posts\n\nnj22az.github.io/blog/']]},
  {id:'keychain',title:'Form 3D Studio',kind:'keychain',place:'Workshop · Fishing-gear store',pos:[-8.7,1.12,-56.8],color:0x67a7aa,url:ROOT+'/form-3d-studio/',note:'Inspected the keychain. Browser-private; STL and STEP.',pages:[['FORM 3D STUDIO','Private, in-browser, STL & STEP.\nImage keychains and simple 3D forms.']]},
  {id:'stepwise',title:'StepWise',kind:'calculator',place:'Drafting bench · Instruments',pos:[5.2,1.06,6],color:0x446454,url:ROOT+'/stepbuddy/',note:'StepWise. Precision before speed.',pages:[['STEPWISE','Precision before speed.\nStep-by-step engineering calculator.\n\n1. State the known values.\n2. Keep units consistent.\n3. Check the result.']]},
  ...[['github','GitHub','SOURCE','https://github.com/nj22az'],['linkedin','LinkedIn','Career · maritime and industrial field service','https://www.linkedin.com/in/nils-johansson-86744583'],['etsy','Etsy Shop','Templates from the field','https://www.etsy.com/shop/Colonialclub'],['wordpress','WordPress Blog','Dispatches','https://theofficeofnils.wordpress.com']].map(([id,title,label,url],i)=>({id,title,kind:i===1?'paper':'parcel',place:'Post kiosk · Johansson Street',pos:[5.2,1.04,12.6+i*1.25],color:0xa58b62,url,note:'Found the '+title+' outbound channel.',pages:[[title,label+'\n\n'+url]]})),
  {id:'model',title:'Johansson Town · 1:40',kind:'model',place:'Workshop · Fishing-gear store',pos:[-8.7,1.12,-58.3],color:0x726044,note:'Kenji: “Don’t drop it. We’re inside.”',pages:[['JOHANSSON TOWN','A scale model of this street.\n1:40 · handle with care.']]},
  ...BOOKS.slice(1).map((title,i)=>({id:'book'+(i+2),title,kind:'book',place:'Bookshop · companion stack',pos:[5.5,1.1+i*.08,37.2],color:[0x455e60,0x645735,0x714637,0x414e59,0x555e42][i],url:ROOT+'/the-front-row-seat/',note:'Opened companion volume: '+title,pages:[[title,'The Front-Row Seat\nBook '+(i+2)+'\nNils Johansson'],['COMPACT EDITION','Companion volume.\nThis street copy contains the title page only.\n\nOpen the full reader for the published text.']]}))
];
