// Fictional period documents. No outbound links or live portfolio content.
export const JOURNAL=[['14 September 1988','Harbour maintenance notice'],['14 September 1988','The evening deliveries'],['12 September 1988','A letter from Nam Phuoc']];
export const BOOKS=['The Venture','The Gallows Years','Kings of Bengal','The Poppy',"The Watchman’s Daughter",'The Engine Room'];
const bookPages=[
 ['THE VENTURE','The rain has not let up in three days. At the waterside inn, a young sailor watches the clerk put away his pen. A berth is available. The price of passage is work.'],
 ['THE GALLOWS YEARS','The old captain keeps his coat on by the fire. Nobody asks him about the rope marks. He has come to hear whether the packet ship made harbour before the storm.'],
 ['KINGS OF BENGAL','Between the cargo columns somebody has pressed a flower. The accounts say nothing about it. The flower says nothing about the accounts.'],
 ['THE POPPY','A boat waits at the river steps. Its owner counts the bundles once, then again. On the other bank, the morning market has begun.'],
 ["THE WATCHMAN’S DAUGHTER",'She carries a white bowl through the crowded lane. It was her father’s. In a new city, it is useful to know the weight of one familiar thing.'],
 ['THE ENGINE ROOM','The watch changes at four. A hand rests on the bearing housing; the new engineer listens before he touches a tool. Above them, the harbour lights drift past.']
];
export const ITEMS=[
 ...BOOKS.map((title,i)=>({id:i?'book'+(i+1):'book',title,kind:'book',place:'Aiko’s bookshop · display shelf',pos:i?[5.5,1.1+i*.08,37.2]:[5.25,1.12,35.5],color:[0x633f36,0x455e60,0x645735,0x714637,0x414e59,0x555e42][i],note:'Read '+title+'.',pages:[[title,'Aiko’s reading copy. Please return it to the display shelf.'],bookPages[i],['BOOKMARK','A faded ferry ticket marks this page. On the back: “Meet me after the last boat.”']]})),
 {id:'cv',title:'NILS JOHANSSON · MARINE SERVICE FOLIO',kind:'folio',place:'Harbour office · Quayside',pos:[-8.1,1.02,-53.2],color:0xded5bb,note:'Found Johansson’s marine service folio.',pages:[['MARINE SERVICE','Nils Johansson · Visiting engineer\n\nDiesel machinery, pumps, controls and workshop measurements.\n\nLeave a written fault report with the harbour office. Record what happened, when it happened and which checks have already been made.'],['DAILY RECORD · 14 SEPTEMBER 1988','06:40 — fishing boat cooling-water pump\n09:10 — workshop instrument check\n13:00 — harbour winch inspection\n16:30 — collect replacement seals\n\nA blue pencil underlines the last entry twice.']]},
 ...JOURNAL.map(([date,title],i)=>({id:['bligh','discipline','vietnam'][i],title,kind:'paper',place:i===2?'Harbour notice board':'Evening Press · paper rack',pos:i===2?[5.6,1.4,-48.1]:[-5.4,1.2,-.4-i*1.25],color:0xd8cbb0,note:'Read '+title+'.',pages:[[title,date+'\n\n'+['The outer pier remains open to pedestrians. Keep the mooring lanes clear. Return borrowed tools before the office closes.','The press has bundled the evening edition. Deliver one parcel to the bathhouse, one to the bus hut and two to the general store.','Dear Nils,\nThe rain arrived before breakfast. The sewing machine is behaving itself. I have put the last length of blue cloth aside. Write when you reach the next harbour.'][i]]]})),
 {id:'journal',title:'Evening edition',kind:'paper',place:'Harbour notice board',pos:[5.5,1.25,-46.6],color:0xcac5aa,note:'Read the evening edition.',pages:[['港日報 · 14 SEPTEMBER 1988','Local baseball: Harbour 3, Mountain 2.\nBathhouse closes at 21:00.\nLast passenger bus: 18:20.\nA ginger cat has been seen near the ramen stall.']]},
 {id:'keychain',title:'Brass key tag',kind:'keychain',place:'Kenji’s pattern bench',pos:[-8.7,1.12,-56.8],color:0x9f8a56,note:'Inspected Kenji’s brass key tag.',pages:[['KEY TAG','The stamping reads COLD STORE. The key is missing.']]},
 {id:'stepwise',title:'Workshop calculator',kind:'calculator',place:'Instruments · drafting bench',pos:[5.2,1.06,6],color:0x446454,note:'Checked the workshop calculator.',pages:[['MEASUREMENT NOTES','1. Record the known values.\n2. Keep the units consistent.\n3. Estimate the answer before calculating.\n4. Check the result.']]},
 ...[['github','Workshop parts ledger','Seals, belts, bearings and four pencils.'],['linkedin','Service certificates','Inspection stamps and neatly folded carbon copies.'],['etsy','Parcel for Sato','Household goods, wrapped in brown paper.'],['wordpress','Airmail envelope','A letter from Nam Phuoc. The stamp has been carefully kept.']].map(([id,title,body],i)=>({id,title,kind:i===1?'paper':'parcel',place:'Street delivery shelf',pos:[5.2,1.04,12.6+i*1.25],color:0xa58b62,note:'Found '+title+'.',pages:[[title,body+'\n\n14 September 1988']]})),
 {id:'model',title:'Johansson Town · 1:40',kind:'model',place:'Kenji’s workshop',pos:[-8.7,1.12,-58.3],color:0x726044,note:'Kenji: “Don’t drop it. We’re inside.”',pages:[['JOHANSSON TOWN','A scale model of the old shopping street. 1:40. Handle with care.']]}
];
