import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s),isIOS=/iP(hone|ad|od)/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0,mobile=isIOS||touch,canvas=$('#game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance',alpha:false,stencil:false});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.6));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=!mobile;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb7c4bd);scene.fog=new THREE.Fog(0xb7c4bd,54,120);const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.07,160);const loader=new GLTFLoader();
const bands=new Uint8Array([48,48,48,255,115,115,115,255,184,184,184,255,255,255,255,255]),gradient=new THREE.DataTexture(bands,4,1,THREE.RGBAFormat);gradient.needsUpdate=true;gradient.magFilter=THREE.NearestFilter;gradient.minFilter=THREE.NearestFilter;const outlineMat=new THREE.MeshBasicMaterial({color:0x252821,side:THREE.BackSide}),boxCache=new Map();
const toon=(c,map=null)=>new THREE.MeshToonMaterial({color:c,map,gradientMap:gradient});const boxGeo=s=>{const k=s.join(',');if(!boxCache.has(k))boxCache.set(k,new THREE.BoxGeometry(...s));return boxCache.get(k)};
function box(size,pos,color,parent,outline=true){const g=boxGeo(size),m=new THREE.Mesh(g,toon(color));m.position.set(...pos);m.castShadow=!mobile;m.receiveShadow=!mobile;parent.add(m);if(outline){const o=new THREE.Mesh(g,outlineMat);o.position.copy(m.position);o.rotation.copy(m.rotation);o.scale.set(1.018,1.018,1.018);parent.add(o)}return m}
function mesh(geo,pos,color,parent,outline=true){const m=new THREE.Mesh(geo,toon(color));m.position.set(...pos);parent.add(m);if(outline){const o=new THREE.Mesh(geo,outlineMat);o.position.copy(m.position);o.scale.set(1.022,1.022,1.022);parent.add(o)}return m}
function signTex(a,b,accent='#9b4035'){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#efe3c7';x.fillRect(0,0,512,128);x.fillStyle=accent;x.fillRect(0,0,14,128);x.strokeStyle='#252821';x.lineWidth=5;x.strokeRect(5,5,502,118);x.fillStyle='#252821';x.textAlign='center';x.textBaseline='middle';x.font='700 43px Yu Gothic,system-ui';x.fillText(a,256,50);x.font='800 15px system-ui';x.fillText(b.toUpperCase(),256,99);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
const town=new THREE.Group(),room=new THREE.Group();scene.add(town,room);room.visible=false;scene.add(new THREE.HemisphereLight(0xe7eee8,0x5a554d,1.7));const sun=new THREE.DirectionalLight(0xffd39a,mobile?3.4:4.1);sun.position.set(-28,38,18);sun.castShadow=!mobile;if(!mobile){sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-40;sun.shadow.camera.right=40;sun.shadow.camera.top=60;sun.shadow.camera.bottom=-60}scene.add(sun);
const SITES=[
{id:'office',title:'The Office',jp:'事務所',sub:'HOME · ABOUT · LOCATIONS',side:-1,z:38,color:0x62776e,accent:'#49675d',url:'/',line:'Charts, travel notes and engineering papers.',props:['desk.glb','computerScreen.glb']},
{id:'frontrow',title:'Front-Row Books',jp:'前列書房',sub:'THE FRONT-ROW SEAT',side:1,z:30,color:0x735849,accent:'#8b3f36',url:'/the-front-row-seat/',line:'The reading room is open until late.',props:['bookcaseOpen.glb','loungeChair.glb']},
{id:'form3d',title:'Form 3D Workshop',jp:'立体工房',sub:'FORM 3D STUDIO',side:-1,z:18,color:0x566b73,accent:'#385f6e',url:'/form-3d-studio/',line:'Small parts, prototypes and fabrication work.',props:['desk.glb','laptop.glb']},
{id:'stepwise',title:'StepWise Instruments',jp:'計算器店',sub:'ENGINEERING CALCULATOR',side:1,z:8,color:0x6b6753,accent:'#6c633d',url:'/stepbuddy/',line:'Measuring tools and calculation instruments.',props:['deskCorner.glb','computerScreen.glb']},
{id:'journal',title:'The Journal Press',jp:'日報印刷所',sub:'JOURNAL',side:-1,z:-4,color:0x78615c,accent:'#8f433d',url:'https://theofficeofnils.wordpress.com',line:'Fresh copy stacked beside the press.',props:['desk.glb','radio.glb']},
{id:'electronics',title:'Johansson Electronics',jp:'電子工作所',sub:'CODE · PROTOTYPES',side:1,z:-16,color:0x565f68,accent:'#3f515e',url:'https://github.com/nj22az',line:'Computers, circuits and unfinished experiments.',props:['computerScreen.glb','speaker.glb']},
{id:'market',title:'Colonial Club Market',jp:'雑貨市場',sub:'MARKET',side:-1,z:-28,color:0x7a684f,accent:'#8e6439',url:'https://www.etsy.com/shop/Colonialclub',line:'Practical goods and curious little objects.',props:['kitchenBar.glb','cardboardBoxOpen.glb']},
{id:'career',title:'Career Bureau',jp:'職歴案内所',sub:'PROFESSIONAL',side:1,z:-39,color:0x586c68,accent:'#3f615d',url:'https://www.linkedin.com/in/nils-johansson-86744583',line:'Records from ships, commissioning and field service.',props:['desk.glb','coatRackStanding.glb']}
];
const interactables=[],doors=new Map();let current=null,active=null,started=false,yaw=0,pitch=-.1,cam=0,minutes=1002,subtitleTimer=0,roomToken=0;const keys={},clock=new THREE.Clock(),moveTouch={id:null,cx:0,cy:0,x:0,y:0},lookTouch={id:null,x:0,y:0};
const player=new THREE.Group();scene.add(player);player.position.set(0,0,46);mesh(new THREE.SphereGeometry(.21,10,8),[0,1.75,0],0xd19b73,player);box([.54,.7,.28],[0,1.2,0],0x3f5862,player);box([.19,.62,.19],[-.16,.54,0],0x29343a,player);box([.19,.62,.19],[.16,.54,0],0x29343a,player);
const reg=(o,label,fn,inside=false)=>{o.userData.hit={label,fn,inside};interactables.push(o)};function say(t,sec=3){const e=$('#subtitle');e.textContent=t;e.classList.add('on');subtitleTimer=sec}
box([15,.15,108],[0,-.08,0],0x69706b,town,false);box([4.8,.22,108],[-9.9,.02,0],0xa8a296,town,false);box([4.8,.22,108],[9.9,.02,0],0xa8a296,town,false);for(let z=-50;z<52;z+=9)box([.1,.025,3.6],[0,.025,z],0xd7cfaa,town,false);
function buildSite(s){const g=new THREE.Group();g.position.z=s.z;town.add(g);const side=s.side,front=side*7.45;box([7,5.8,9.5],[side*11.3,2.9,0],s.color,g);box([7.6,.3,10.1],[side*11.3,6,0],0x414847,g);const st=new THREE.Mesh(new THREE.PlaneGeometry(5.5,1.28),new THREE.MeshToonMaterial({map:signTex(s.jp,s.title,s.accent),gradientMap:gradient}));st.position.set(front-side*.03,4,-.7);st.rotation.y=side>0?-Math.PI/2:Math.PI/2;g.add(st);const win=new THREE.Mesh(new THREE.PlaneGeometry(3.6,1.85),toon(0x4f6969));win.position.set(front,1.62,-1.8);win.rotation.y=side>0?-Math.PI/2:Math.PI/2;g.add(win);const door=new THREE.Mesh(new THREE.PlaneGeometry(1.22,2.42),toon(0x806047));door.position.set(front-side*.13,1.28,2.5);door.rotation.y=side>0?-Math.PI/2:Math.PI/2;g.add(door);reg(door,`ENTER · ${s.title}`,()=>enterRoom(s));doors.set(s.id,new THREE.Vector3(side*5.9,0,s.z+2.5));const plate=new THREE.Mesh(new THREE.PlaneGeometry(2.7,.62),new THREE.MeshToonMaterial({map:signTex(s.sub,'JOHANSSON TOWN',s.accent),gradientMap:gradient}));plate.position.set(front-side*.035,3.05,2.2);plate.rotation.y=door.rotation.y;g.add(plate);box([1.45,.18,5.2],[side*7,2.9,-1.2],side>0?0x6c4a43:0x4f665e,g)}SITES.forEach(buildSite);
for(const side of [-1,1])for(let z=-44;z<=44;z+=16){const g=new THREE.Group();g.position.set(side*7.05,0,z);town.add(g);mesh(new THREE.CylinderGeometry(.08,.11,4.8,7),[0,2.4,0],0x404541,g);const l=mesh(new THREE.SphereGeometry(.11,8,6),[-side*.55,4.55,0],0xf0be6d,g,false);l.material.emissive=new THREE.Color(0xffa54d);l.material.emissiveIntensity=.8}
const FURN='https://cdn.jsdelivr.net/gh/eturner58/game-assets@main/kenney/3D%20assets/Furniture%20Kit/Models/GLTF%20format/',assetCache=new Map();async function getAsset(name){if(assetCache.has(name))return assetCache.get(name).clone(true);const d=await loader.loadAsync(FURN+name);d.scene.traverse(n=>{if(n.isMesh){const old=Array.isArray(n.material)?n.material[0]:n.material;n.material=new THREE.MeshToonMaterial({color:old?.color?.clone?.()||new THREE.Color(0xbab39c),map:old?.map||null,gradientMap:gradient});n.castShadow=!mobile;n.receiveShadow=!mobile}});assetCache.set(name,d.scene);return d.scene.clone(true)}
async function putAsset(name,pos,target,parent,rot=0){try{const o=await getAsset(name),b=new THREE.Box3().setFromObject(o),sz=b.getSize(new THREE.Vector3()),max=Math.max(sz.x,sz.y,sz.z)||1;o.scale.setScalar(target/max);const bb=new THREE.Box3().setFromObject(o);o.position.set(pos[0],pos[1]-bb.min.y,pos[2]);o.rotation.y=rot;parent.add(o);return o}catch{return null}}
function clearRoom(){roomToken++;while(room.children.length)room.remove(room.children[0]);for(let i=interactables.length-1;i>=0;i--)if(interactables[i].userData?.hit?.inside)interactables.splice(i,1)}
function roomShell(s){clearRoom();town.visible=false;room.visible=true;box([13,.18,13],[0,-.08,0],0x9e957f,room,false);box([13,4.4,.24],[0,2.2,-6.45],s.color,room);box([.24,4.4,13],[-6.45,2.2,0],s.color,room);box([.24,4.4,13],[6.45,2.2,0],s.color,room);box([5,4.4,.24],[-4,2.2,6.45],s.color,room);box([5,4.4,.24],[4,2.2,6.45],s.color,room);box([3,1.4,.24],[0,3.7,6.45],s.color,room);const back=new THREE.Mesh(new THREE.PlaneGeometry(5.8,1.35),new THREE.MeshToonMaterial({map:signTex(s.jp,s.title,s.accent),gradientMap:gradient}));back.position.set(0,3.35,-6.28);room.add(back);const notice=new THREE.Mesh(new THREE.PlaneGeometry(3.7,1.7),new THREE.MeshToonMaterial({map:signTex(s.title,s.line,s.accent),gradientMap:gradient}));notice.position.set(-3.2,1.9,-6.27);room.add(notice);reg(notice,'READ NOTICE',()=>say(s.line,4),true);const terminal=box([2.3,2.55,.18],[.4,1.28,-5.95],0x2e3b3a,room);reg(terminal,'USE TERMINAL',()=>openLink(s.url),true);const exit=new THREE.Mesh(new THREE.PlaneGeometry(2.45,2.7),toon(0x8c684d));exit.position.set(0,1.35,6.31);exit.rotation.y=Math.PI;room.add(exit);reg(exit,'EXIT',leaveRoom,true)}
async function streamRoomProps(s,token){const ps=[[-3.7,0,-2.3],[2.6,0,-2.2]];for(let i=0;i<s.props.length;i++){if(token!==roomToken)return;await new Promise(r=>setTimeout(r,mobile?70:20));const o=await putAsset(s.props[i],ps[i],1.7-i*.2,room,i?Math.PI:0);if(o)o.userData.inside=true}}
function enterRoom(s){current=s;roomShell(s);player.position.set(0,0,4.3);yaw=0;$('#place').textContent=s.title.toUpperCase();$('#placeSub').textContent=`${s.jp} · ${s.sub}`;$('#timeText').textContent=s.line;say(s.title,1.5);streamRoomProps(s,roomToken)}
function leaveRoom(){const s=current;current=null;room.visible=false;town.visible=true;if(s){player.position.copy(doors.get(s.id));player.position.z+=.6}$('#place').textContent='JOHANSSON TOWN';$('#placeSub').textContent='ヨハンソン町 · HARBOUR DISTRICT';$('#timeText').textContent='Shops are open.';say('Johansson Street',1.5)}
function openLink(url){say('Connecting…',.7);const u=new URL(url,location.origin);if(u.origin===location.origin)location.href=u.href;else window.open(u.href,'_blank','noopener')}
function interaction(){active=null;let best=null,dmax=3.1;const p=player.position.clone();p.y=1,fw=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion);for(const o of interactables){const h=o.userData.hit;if(current&&!h.inside||!current&&h.inside)continue;const q=new THREE.Vector3();o.getWorldPosition(q);const v=q.sub(p),d=v.length();if(d>dmax)continue;v.y=0;if(v.lengthSq()&&fw.dot(v.normalize())<-.2)continue;dmax=d;best=h}const e=$('#prompt');if(best){active=best;e.textContent=(touch?'':'E · ')+best.label;e.classList.add('on')}else e.classList.remove('on')}
function doInteract(){active?.fn?.()}
function updatePlayer(dt){let f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),s=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0);if(moveTouch.id!==null){s+=THREE.MathUtils.clamp((moveTouch.x-moveTouch.cx)/48,-1,1);f+=THREE.MathUtils.clamp(-(moveTouch.y-moveTouch.cy)/48,-1,1)}const v2=new THREE.Vector2(s,f);if(v2.lengthSq()>1)v2.normalize();const fw=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),rt=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),v=fw.multiplyScalar(v2.y).add(rt.multiplyScalar(v2.x));if(v.lengthSq()>.02){v.normalize();player.position.addScaledVector(v,(keys.ShiftLeft?5.2:3)*dt);player.quaternion.slerp(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),Math.atan2(-v.x,-v.z)),1-Math.pow(.001,dt))}if(current){player.position.x=THREE.MathUtils.clamp(player.position.x,-5.5,5.5);player.position.z=THREE.MathUtils.clamp(player.position.z,-5.4,5.7)}else{player.position.x=THREE.MathUtils.clamp(player.position.x,-7,7);player.position.z=THREE.MathUtils.clamp(player.position.z,-51,51)}const dist=[5.1,7.1,3.4][cam],target=player.position.clone().add(new THREE.Vector3(0,1.2,0)),h=Math.cos(pitch)*dist,desired=new THREE.Vector3(target.x+Math.sin(yaw)*h,target.y+1+Math.sin(-pitch)*dist,target.z+Math.cos(yaw)*h);camera.position.lerp(desired,1-Math.pow(.00005,dt));camera.lookAt(target)}
const fmt=m=>`${String(Math.floor((m%1440)/60)).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;function setTime(){const h=(minutes/60)%24,day=h>=7&&h<18?1:h>=18&&h<20?1-(h-18)/2:0;sun.intensity=1+day*3;scene.background.set(day>.5?0xb7c4bd:0x4c5b60);scene.fog.color.copy(scene.background);renderer.toneMappingExposure=.84+day*.17}
function toggleDir(open){$('#directory').classList.toggle('hidden',!open)}$('#directoryGrid').innerHTML=SITES.map(s=>`<button class="dir-item" data-id="${s.id}"><b>${s.title}</b><span>${s.sub}</span></button>`).join('');document.querySelectorAll('.dir-item').forEach(b=>b.onclick=()=>{if(current)leaveRoom();const s=SITES.find(x=>x.id===b.dataset.id);player.position.copy(doors.get(s.id));player.position.z+=.5;toggleDir(false);say(s.title,1.4)});$('#directoryButton').onclick=()=>toggleDir(true);$('#closeDirectory').onclick=()=>toggleDir(false);
$('#enter').onclick=async()=>{started=true;$('#start').classList.add('hidden');$('#hud').classList.remove('hidden');if(!touch)canvas.requestPointerLock?.();else if(!isIOS){try{await document.documentElement.requestFullscreen?.()}catch{}}};canvas.onclick=()=>{if(started&&!touch&&$('#directory').classList.contains('hidden'))canvas.requestPointerLock?.()};document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==canvas)return;yaw-=e.movementX*.0023;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0018,-.42,.34)});document.addEventListener('keydown',e=>{keys[e.code]=true;if(!started)return;if(e.code==='KeyE'&&!e.repeat)doInteract();if(e.code==='KeyQ'&&!e.repeat)toggleDir($('#directory').classList.contains('hidden'));if(e.code==='KeyV'&&!e.repeat)cam=(cam+1)%3;if(e.code==='KeyN'&&!e.repeat)minutes=[1002,1100,1208,550][(Math.floor(minutes)%4+1)%4]});document.addEventListener('keyup',e=>keys[e.code]=false);$('#act').onpointerdown=e=>{e.preventDefault();doInteract()};
const stick=$('#stick'),knob=$('#knob');canvas.addEventListener('touchstart',e=>{if(!started)return;const r=stick.getBoundingClientRect();for(const t of e.changedTouches){if(t.clientX<innerWidth*.48&&moveTouch.id===null){moveTouch.id=t.identifier;moveTouch.cx=r.left+r.width/2;moveTouch.cy=r.top+r.height/2;moveTouch.x=t.clientX;moveTouch.y=t.clientY}else if(lookTouch.id===null){lookTouch.id=t.identifier;lookTouch.x=t.clientX;lookTouch.y=t.clientY}}e.preventDefault()},{passive:false});canvas.addEventListener('touchmove',e=>{for(const t of e.changedTouches){if(t.identifier===moveTouch.id){moveTouch.x=t.clientX;moveTouch.y=t.clientY;knob.style.transform=`translate(${THREE.MathUtils.clamp(t.clientX-moveTouch.cx,-42,42)}px,${THREE.MathUtils.clamp(t.clientY-moveTouch.cy,-42,42)}px)`}else if(t.identifier===lookTouch.id){yaw-=(t.clientX-lookTouch.x)*.005;pitch=THREE.MathUtils.clamp(pitch-(t.clientY-lookTouch.y)*.0037,-.42,.34);lookTouch.x=t.clientX;lookTouch.y=t.clientY}}e.preventDefault()},{passive:false});function endTouch(e){for(const t of e.changedTouches){if(t.identifier===moveTouch.id){moveTouch.id=null;knob.style.transform='translate(0,0)'}if(t.identifier===lookTouch.id)lookTouch.id=null}}canvas.addEventListener('touchend',endTouch,{passive:false});canvas.addEventListener('touchcancel',endTouch,{passive:false});addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});document.addEventListener('visibilitychange',()=>{moveTouch.id=null;lookTouch.id=null;knob.style.transform='translate(0,0)'});
let last=0;function loop(now=0){requestAnimationFrame(loop);if(mobile&&now-last<33)return;if(mobile)last=now;const dt=Math.min(clock.getDelta(),.05);if(started&&!document.hidden){minutes+=dt*.16;$('#clock').textContent=fmt(minutes);updatePlayer(dt);interaction();setTime();if(subtitleTimer>0&&(subtitleTimer-=dt)<=0)$('#subtitle').classList.remove('on');renderer.render(scene,camera)}}renderer.render(scene,camera);loop();