import * as THREE from '../the-front-row-seat/pelican/vendor/three.module.min.js';
import { createTown } from './world.js?v=8';
import { createActivities } from './activities.js?v=8';
const $=s=>document.querySelector(s),isIOS=/iP(hone|ad|od)/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0,mobile=isIOS||touch,canvas=$('#game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:mobile?'default':'high-performance',alpha:false,stencil:false,preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.6));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb7c4bd);scene.fog=new THREE.Fog(0xb7c4bd,54,120);const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.07,220);
const bands=new Uint8Array([48,48,48,255,115,115,115,255,184,184,184,255,255,255,255,255]),gradient=new THREE.DataTexture(bands,4,1,THREE.RGBAFormat);gradient.needsUpdate=true;gradient.magFilter=THREE.NearestFilter;gradient.minFilter=THREE.NearestFilter;const outlineMat=new THREE.MeshBasicMaterial({color:0x252821,side:THREE.BackSide}),boxCache=new Map();
const toon=(c,map=null)=>new THREE.MeshStandardMaterial({color:c,map,roughness:.88});const boxGeo=s=>{const k=s.join(',');if(!boxCache.has(k))boxCache.set(k,new THREE.BoxGeometry(...s));return boxCache.get(k)};
function box(size,pos,color,parent,outline=true){const g=boxGeo(size),m=new THREE.Mesh(g,toon(color));m.position.set(...pos);m.castShadow=!mobile;m.receiveShadow=!mobile;parent.add(m);if(false&&outline){const o=new THREE.Mesh(g,outlineMat);o.position.copy(m.position);o.rotation.copy(m.rotation);o.scale.set(1.018,1.018,1.018);parent.add(o)}return m}
function mesh(geo,pos,color,parent,outline=true){const m=new THREE.Mesh(geo,toon(color));m.position.set(...pos);parent.add(m);if(false&&outline){const o=new THREE.Mesh(geo,outlineMat);o.position.copy(m.position);o.scale.set(1.022,1.022,1.022);parent.add(o)}return m}
function signTex(a,b,accent='#9b4035'){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#efe3c7';x.fillRect(0,0,512,128);x.fillStyle=accent;x.fillRect(0,0,14,128);x.strokeStyle='#252821';x.lineWidth=5;x.strokeRect(5,5,502,118);x.fillStyle='#252821';x.textAlign='center';x.textBaseline='middle';x.font='700 43px Yu Gothic,system-ui';x.fillText(a,256,50);x.font='800 15px system-ui';x.fillText(b.toUpperCase(),256,99);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
const town=new THREE.Group(),room=new THREE.Group();scene.add(town,room);room.visible=false;const ambient=new THREE.HemisphereLight(0xdde9ec,0x7c6a51,1.7);scene.add(ambient);const sun=new THREE.DirectionalLight(0xffd39a,mobile?3.4:4.1);sun.position.set(-28,38,18);sun.castShadow=!mobile;if(!mobile){sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-40;sun.shadow.camera.right=40;sun.shadow.camera.top=60;sun.shadow.camera.bottom=-60;sun.shadow.bias=-.0004;sun.shadow.normalBias=.05}scene.add(sun);
const SITES=[
{id:'office',title:'The Office',jp:'事務所',sub:'HOME · ABOUT · LOCATIONS',side:-1,z:38,color:0x62776e,accent:'#49675d',url:'/',line:'Charts, travel notes and engineering papers.'},
{id:'frontrow',title:'Front-Row Books',jp:'前列書房',sub:'THE FRONT-ROW SEAT',side:1,z:30,color:0x735849,accent:'#8b3f36',url:'/the-front-row-seat/',line:'The reading room is open until late.'},
{id:'form3d',title:'Form 3D Workshop',jp:'立体工房',sub:'FORM 3D STUDIO',side:-1,z:18,color:0x566b73,accent:'#385f6e',url:'/form-3d-studio/',line:'Small parts, prototypes and fabrication work.'},
{id:'stepwise',title:'StepWise Instruments',jp:'計算器店',sub:'ENGINEERING CALCULATOR',side:1,z:8,color:0x6b6753,accent:'#6c633d',url:'/stepbuddy/',line:'Measuring tools and calculation instruments.'},
{id:'journal',title:'The Journal Press',jp:'日報印刷所',sub:'JOURNAL',side:-1,z:-4,color:0x78615c,accent:'#8f433d',url:'https://theofficeofnils.wordpress.com',line:'Fresh copy stacked beside the press.'},
{id:'electronics',title:'Johansson Electronics',jp:'電子工作所',sub:'CODE · PROTOTYPES',side:1,z:-16,color:0x565f68,accent:'#3f515e',url:'https://github.com/nj22az',line:'Computers, circuits and unfinished experiments.'},
{id:'market',title:'Colonial Club Market',jp:'雑貨市場',sub:'MARKET',side:-1,z:-28,color:0x7a684f,accent:'#8e6439',url:'https://www.etsy.com/shop/Colonialclub',line:'Practical goods and curious little objects.'},
{id:'career',title:'Career Bureau',jp:'職歴案内所',sub:'PROFESSIONAL',side:1,z:-39,color:0x586c68,accent:'#3f615d',url:'https://www.linkedin.com/in/nils-johansson-86744583',line:'Records from ships, commissioning and field service.'}
];
const interactables=[],roomColliders=[],doors=new Map();let current=null,active=null,started=false,yaw=0,pitch=-.1,cam=0,minutes=1002,subtitleTimer=0,weather=false,activities=null,timePreset=0,characters=null;const keys={},clock=new THREE.Clock(),moveTouch={id:null,cx:0,cy:0,x:0,y:0},lookTouch={id:null,x:0,y:0};
const player=new THREE.Group();scene.add(player);player.position.set(0,0,46);mesh(new THREE.SphereGeometry(.21,10,8),[0,1.75,0],0xd19b73,player);box([.54,.7,.28],[0,1.2,0],0x3f5862,player);box([.19,.62,.19],[-.16,.54,0],0x29343a,player);box([.19,.62,.19],[.16,.54,0],0x29343a,player);
const reg=(o,label,fn,inside=false)=>{o.userData.hit={label,fn,inside};interactables.push(o)};function say(t,sec=3){const e=$('#subtitle');e.textContent=t;e.classList.add('on');subtitleTimer=sec}
const world=createTown({scene:town,sites:SITES,mobile,register:reg,enter:enterRoom,onAction:(...args)=>{if(args[0]==='resident'){const person=world.people.find(p=>p.g.userData.name===args[1]);if(person){person.g.lookAt(player.position.x,0,player.position.z);person.g.rotateY(Math.PI);characters?.gesture(person.g);}}activities.action(...args);}});
SITES.forEach(s=>doors.set(s.id,new THREE.Vector3(s.side*5.9,0,s.z+2.5)));
activities=createActivities({say,onWeather:value=>{weather=value;world.setRain(value);},onTime:value=>{if(value==='cycle'){timePreset=(timePreset+1)%4;minutes=[1002,1110,1230,540][timePreset];}else minutes+=value;},onCamera:()=>{cam=(cam+1)%4;say(['Follow camera','Wide camera','Close camera','First person'][cam]);}});
// Character models stream in locally without blocking ENTER TOWN.
import('./characters.js?v=8').then(({createCharacters})=>{
  characters=createCharacters({mobile,onError:(file,error)=>console.warn('Character asset unavailable:',file,error)});
  characters.attach(player,'character-male-a.glb',1.82);
  const models=['character-female-f.glb','character-male-a.glb','character-female-e.glb','character-male-a.glb'];
  world.people.forEach((p,i)=>characters.attach(p.g,models[i],i===2?1.65:1.76));
}).catch(error=>console.warn('Character loader unavailable',error));
function addRoomProps(s){const addDesk=(x,z)=>{roomColliders.push({x,z,w:2.2,d:1});box([2.2,.18,1],[x,.82,z],0x765b43,room);for(const dx of [-.88,.88])for(const dz of [-.35,.35])box([.16,.72,.16],[x+dx,.36,z+dz],0x4b4036,room,false)};const addScreen=(x,z)=>{box([.95,.7,.65],[x,1.48,z+.28],0x303a39,room);box([.62,.42,.03],[x,1.48,z-.055],0x6e8b83,room,false);box([.12,.38,.12],[x,1.08,z],0x303a39,room,false)};const addShelf=(x,z)=>{roomColliders.push({x,z,w:1.7,d:.6});const shelf=box([1.7,2.55,.45],[x,1.28,z],0x5a4636,room);for(let y=.42;y<2.3;y+=.48){box([1.48,.08,.52],[x,y,z],0x8a694c,room,false);for(let n=0;n<7;n++)box([.13,.3+(n%2)*.06,.22],[x-.58+n*.19,y+.19,z+.25],[0x975544,0x486975,0xb2a57e,0x677c62][n%4],room,false);}reg(shelf,'Browse the shelves',()=>say(s.id==='frontrow'?'Sea voyages, harbour histories and The Front-Row Seat. Use the terminal to enter the reading collection.':s.line,5),true)};const addCrates=(x,z)=>{roomColliders.push({x:x+.3,z:z+.2,w:1.8,d:1.5});box([1,.72,1],[x,.36,z],0x9a764e,room);box([.85,.58,.85],[x+.8,.29,z+.55],0x806447,room)};const addChair=(x,z)=>{box([.72,.12,.72],[x,.64,z],0x4f5d58,room);box([.72,.7,.1],[x,1,z+.3],0x4f5d58,room);for(const dx of [-.25,.25])for(const dz of [-.25,.25])box([.1,.62,.1],[x+dx,.31,z+dz],0x3f4744,room,false)};if(s.id==='frontrow'){addShelf(-3.8,-2.5);addShelf(-3.8,.2);addChair(2.2,-1.4);box([1.3,.12,1.3],[2.2,.58,.2],0x6b533d,room)}else if(s.id==='market'){addCrates(-3,-1.8);addCrates(2.5,-2.5);box([4,.9,.7],[0,.45,1.2],0x795d43,room)}else{addDesk(-2.3,-1.9);addScreen(-2.3,-1.92);addChair(1.6,-.9);if(s.id==='electronics'||s.id==='form3d')addCrates(3,-3);else addShelf(3,-3)}}
function clearRoom(){roomColliders.length=0;const materials=new Set(),geos=new Set();room.traverse(o=>{if(o.isMesh){materials.add(o.material);if(![...boxCache.values()].includes(o.geometry))geos.add(o.geometry);}});materials.forEach(m=>{m.map?.dispose();m.dispose();});geos.forEach(g=>g.dispose());while(room.children.length)room.remove(room.children[0]);for(let i=interactables.length-1;i>=0;i--)if(interactables[i].userData?.hit?.inside)interactables.splice(i,1)}
function roomShell(s){clearRoom();town.visible=false;room.visible=true;box([13,.18,13],[0,-.08,0],0x9e957f,room,false);box([13,4.4,.24],[0,2.2,-6.45],s.color,room);box([.24,4.4,13],[-6.45,2.2,0],s.color,room);box([.24,4.4,13],[6.45,2.2,0],s.color,room);box([5,4.4,.24],[-4,2.2,6.45],s.color,room);box([5,4.4,.24],[4,2.2,6.45],s.color,room);box([3,1.4,.24],[0,3.7,6.45],s.color,room);const back=new THREE.Mesh(new THREE.PlaneGeometry(5.8,1.35),new THREE.MeshToonMaterial({map:signTex(s.jp,s.title,s.accent),gradientMap:gradient}));back.position.set(0,3.35,-6.28);room.add(back);const notice=new THREE.Mesh(new THREE.PlaneGeometry(3.7,1.7),new THREE.MeshToonMaterial({map:signTex(s.title,s.line,s.accent),gradientMap:gradient}));notice.position.set(-3.2,1.9,-6.27);room.add(notice);reg(notice,'READ NOTICE',()=>say(s.line,4),true);const terminal=box([2.3,2.55,.18],[.4,1.28,-5.95],0x2e3b3a,room);reg(terminal,'Open '+s.title,()=>openLink(s.url),true);const terminalLabel=new THREE.Mesh(new THREE.PlaneGeometry(1.95,.65),new THREE.MeshBasicMaterial({map:signTex('接続','OPEN '+s.title,s.accent)}));terminalLabel.position.set(.4,1.7,-5.83);room.add(terminalLabel);const exit=new THREE.Mesh(new THREE.PlaneGeometry(2.45,2.7),toon(0x8c684d));exit.position.set(0,1.35,6.31);exit.rotation.y=Math.PI;room.add(exit);reg(exit,'EXIT',leaveRoom,true)}
function enterRoom(s){activities.close();activities.visit(s.id);current=s;roomShell(s);addRoomProps(s);player.position.set(0,0,4.3);yaw=0;active=null;$('#place').textContent=s.title.toUpperCase();$('#placeSub').textContent=`${s.jp} · ${s.sub}`;$('#timeText').textContent=s.line;say(s.title,1.5);camera.position.set(0,2.8,5.7)}
function leaveRoom(){active=null;const s=current;current=null;room.visible=false;town.visible=true;if(s){player.position.copy(doors.get(s.id));player.position.z+=.6}$('#place').textContent='JOHANSSON TOWN';$('#placeSub').textContent='ヨハンソン町 · HARBOUR DISTRICT';$('#timeText').textContent='Shops are open.';say('Johansson Street',1.5)}
function openLink(url){say('Connecting…',.7);const u=new URL(url,location.origin);if(u.origin===location.origin)location.href=u.href;else window.open(u.href,'_blank','noopener')}
function interaction(){active=null;let best=null,dmax=3.1;const p=player.position.clone();p.y=1;const fw=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));for(const o of interactables){const h=o.userData.hit;if(current&&!h.inside||!current&&h.inside)continue;const q=new THREE.Vector3();o.getWorldPosition(q);const v=q.sub(p),d=v.length();if(d>dmax)continue;v.y=0;if(v.lengthSq()&&fw.dot(v.normalize())<-.2)continue;dmax=d;best=h}const e=$('#prompt');if(best){active=best;e.textContent=(touch?'':'E · ')+best.label;e.classList.add('on')}else e.classList.remove('on')}
function doInteract(){if(!activities.paused&&$('#directory').classList.contains('hidden')){interaction();active?.fn?.();}}
function collides(x,z){if(current)return (x<-5.6||x>5.6||z<-5.5||z>5.7)||roomColliders.some(c=>Math.abs(x-c.x)<c.w/2+.27&&Math.abs(z-c.z)<c.d/2+.27);if(z < -62||z>58.2)return true;const limit=z < -52?17.2:7;if(Math.abs(x)>limit)return true;return world.colliders.some(c=>Math.abs(x-c.x)<c.w/2+.27&&Math.abs(z-c.z)<c.d/2+.27);}
function updatePlayer(dt){
  let f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),s=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0);
  if(moveTouch.id!==null){s+=THREE.MathUtils.clamp((moveTouch.x-moveTouch.cx)/48,-1,1);f+=THREE.MathUtils.clamp(-(moveTouch.y-moveTouch.cy)/48,-1,1);}
  const v2=new THREE.Vector2(s,f);if(v2.lengthSq()>1)v2.normalize();
  const fw=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),rt=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),v=fw.multiplyScalar(v2.y).add(rt.multiplyScalar(v2.x));
  if(v.lengthSq()>.02){const speed=(keys.ShiftLeft?5.2:3)*dt,nx=player.position.x+v.x*speed,nz=player.position.z+v.z*speed;if(!collides(nx,player.position.z))player.position.x=nx;if(!collides(player.position.x,nz))player.position.z=nz;player.quaternion.slerp(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),Math.atan2(-v.x,-v.z)),1-Math.pow(.001,dt));}
  player.visible=cam!==3;
  if(cam===3){camera.position.copy(player.position).add(new THREE.Vector3(0,1.7,0));camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);return;}
  const dist=[4.8,6.7,2.6][cam],target=player.position.clone().add(new THREE.Vector3(0,1.3,0)),h=Math.cos(pitch)*dist;
  const desired=new THREE.Vector3(target.x+Math.sin(yaw)*h,target.y+1+Math.sin(-pitch)*dist,target.z+Math.cos(yaw)*h);
  const sideLimit=current?5.95:player.position.z<-53?17.6:6.9;desired.x=THREE.MathUtils.clamp(desired.x,-sideLimit,sideLimit);desired.z=THREE.MathUtils.clamp(desired.z,current?-5.9:-62.5,current?5.95:61);
  camera.position.lerp(desired,1-Math.pow(.00005,dt));camera.lookAt(target);
}
const fmt=m=>`${String(Math.floor((m%1440)/60)).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;function setTime(){const h=(minutes/60)%24,day=h>=7&&h<17?1:h>=17&&h<20?1-(h-17)/3:h>=5&&h<7?(h-5)/2:0;sun.intensity=(.2+day*3)*(weather?.6:1);ambient.intensity=.6+day*1.15;sun.color.set(h>=17&&h<20?0xffb278:0xffe1b0);sun.position.set(-30,12+day*25,12);scene.background.set(weather?0x687c86:day>.7?0xa1bbc4:day>.1?0xa07d76:0x162b43);scene.fog.color.copy(scene.background);scene.fog.near=weather?30:62;scene.fog.far=weather?120:175;renderer.toneMappingExposure=.9+day*.15;$('.timecard small').textContent=h<7?'EARLY MORNING':h<17?'AFTERNOON':h<20?'EVENING':'NIGHT';return day;}
function toggleDir(open){if(open){document.exitPointerLock?.();Object.keys(keys).forEach(k=>keys[k]=false);moveTouch.id=null;}$('#directory').classList.toggle('hidden',!open);if(open)$('#closeDirectory').focus();}$('#directoryGrid').innerHTML=SITES.map(s=>`<button class="dir-item" data-id="${s.id}"><b>${s.title}</b><span>${s.sub}</span></button>`).join('');document.querySelectorAll('.dir-item').forEach(b=>b.onclick=()=>{if(current)leaveRoom();const s=SITES.find(x=>x.id===b.dataset.id);player.position.copy(doors.get(s.id));player.position.z+=.5;yaw=-s.side*Math.PI/2;toggleDir(false);say(s.title,1.4)});$('#directoryButton').onclick=()=>toggleDir(true);$('#closeDirectory').onclick=()=>toggleDir(false);
started=true;$('#start').classList.add('hidden');$('#hud').classList.remove('hidden');window.__JOHANSSON_RUNNING__=true;camera.position.set(0,3.5,50);say('Speak to Aiko near the southern shops. B opens your notebook.',5);canvas.onclick=()=>{if(started&&!touch&&$('#directory').classList.contains('hidden'))canvas.requestPointerLock?.()?.catch?.(()=>{})};document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==canvas||activities.paused)return;yaw-=e.movementX*.0023;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0018,-.42,.34)});document.addEventListener('keydown',e=>{if(activities.paused)return;if(e.code==='Escape'){toggleDir(false);return;}if(!$('#directory').classList.contains('hidden')){if(e.code==='KeyQ')toggleDir(false);return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(!started)return;if(e.code==='KeyE'&&!e.repeat)doInteract();if(e.code==='KeyQ'&&!e.repeat)toggleDir(true);if(e.code==='KeyB'&&!e.repeat)activities.inventory();if(e.code==='KeyV'&&!e.repeat)$('#cameraButton').click();if(e.code==='KeyN'&&!e.repeat)$('#timeButton').click();});document.addEventListener('keyup',e=>keys[e.code]=false);$('#act').onpointerdown=e=>{e.preventDefault();doInteract()};
const stick=$('#stick'),knob=$('#knob');canvas.addEventListener('touchstart',e=>{if(!started||activities.paused||!$('#directory').classList.contains('hidden'))return;const r=stick.getBoundingClientRect();for(const t of e.changedTouches){if(t.clientX<innerWidth*.48&&moveTouch.id===null){moveTouch.id=t.identifier;moveTouch.cx=r.left+r.width/2;moveTouch.cy=r.top+r.height/2;moveTouch.x=t.clientX;moveTouch.y=t.clientY}else if(lookTouch.id===null){lookTouch.id=t.identifier;lookTouch.x=t.clientX;lookTouch.y=t.clientY}}e.preventDefault()},{passive:false});canvas.addEventListener('touchmove',e=>{for(const t of e.changedTouches){if(t.identifier===moveTouch.id){moveTouch.x=t.clientX;moveTouch.y=t.clientY;knob.style.transform=`translate(${THREE.MathUtils.clamp(t.clientX-moveTouch.cx,-42,42)}px,${THREE.MathUtils.clamp(t.clientY-moveTouch.cy,-42,42)}px)`}else if(t.identifier===lookTouch.id){yaw-=(t.clientX-lookTouch.x)*.005;pitch=THREE.MathUtils.clamp(pitch-(t.clientY-lookTouch.y)*.0037,-.42,.34);lookTouch.x=t.clientX;lookTouch.y=t.clientY}}e.preventDefault()},{passive:false});function endTouch(e){for(const t of e.changedTouches){if(t.identifier===moveTouch.id){moveTouch.id=null;knob.style.transform='translate(0,0)'}if(t.identifier===lookTouch.id)lookTouch.id=null}}canvas.addEventListener('touchend',endTouch,{passive:false});canvas.addEventListener('touchcancel',endTouch,{passive:false});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();started=false;const d=$('#fatal');if(d){d.classList.remove('hidden');d.querySelector('p').textContent='Graphics paused. Reload Johansson Town to continue.'}});addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});function resetInput(){Object.keys(keys).forEach(k=>keys[k]=false);moveTouch.id=null;lookTouch.id=null;knob.style.transform='translate(0,0)';}addEventListener('blur',resetInput);document.addEventListener('visibilitychange',()=>{resetInput();moveTouch.id=null;lookTouch.id=null;knob.style.transform='translate(0,0)'});
const mapCanvas=$('#minimap'),mapCtx=mapCanvas.getContext('2d');
function drawMap(){const ctx=mapCtx,w=mapCanvas.width,h=mapCanvas.height;ctx.fillStyle='#172b35';ctx.fillRect(0,0,w,h);const px=x=>w/2+x*3,pz=z=>(z+66)/130*h;ctx.fillStyle='#58686a';ctx.fillRect(px(-7),0,42,h);ctx.fillStyle='#527e8a';ctx.fillRect(0,0,w,11);for(const s of SITES){ctx.fillStyle=activities.state.visited.includes(s.id)?'#dfb971':'#b9baab';ctx.fillRect(px(s.side<0?-13:8),pz(s.z)-4,15,8);}ctx.fillStyle='#df8a63';world.people.forEach(p=>{ctx.beginPath();ctx.arc(px(p.g.position.x),pz(p.g.position.z),2,0,Math.PI*2);ctx.fill();});const pos=current?doors.get(current.id):player.position;ctx.save();ctx.translate(px(pos.x),pz(pos.z));ctx.rotate(-yaw);ctx.fillStyle='#fff4ce';ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(4,4);ctx.lineTo(-4,4);ctx.fill();ctx.restore();}
let last=0,elapsed=0,mapTick=0;function loop(now=0){requestAnimationFrame(loop);if(mobile&&now-last<33)return;if(mobile)last=now;const dt=Math.min(clock.getDelta(),.05);if(started&&!document.hidden){const paused=activities.paused||!$('#directory').classList.contains('hidden');if(!paused){minutes+=dt*.16;elapsed+=dt;updatePlayer(dt);interaction();}else{resetInput();$('#prompt').classList.remove('on');}$('#clock').textContent=fmt(minutes);const day=setTime();if(!current&&!paused)world.update(dt,elapsed,day);characters?.update(dt);if((mapTick+=dt)>.15){drawMap();mapTick=0;}if(subtitleTimer>0&&(subtitleTimer-=dt)<=0)$('#subtitle').classList.remove('on');renderer.render(scene,camera)}}renderer.render(scene,camera);loop();
