import * as THREE from '../the-front-row-seat/pelican/vendor/three.module.min.js';
import { createTown } from './world.js?v=11';
import { createActivities } from './activities.js?v=9';
import { createInspector } from './inspect-3d.js';
import { createContentItems } from './content-items.js';
import { createCastAI } from './cast-ai.js';
import { createCharacters } from './characters.js?v=11';
import { circleHitsRect,circleHitsCircle,roomBoundsBlocked,townBoundsBlocked,sweepFraction } from './physics.js?v=10';

const $=s=>document.querySelector(s);
const isIOS=/iP(hone|ad|od)/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
const mobile=isIOS||touch,tabletLike=touch&&Math.min(innerWidth,innerHeight)>=700,highTier=!mobile||tabletLike,shadows=highTier,canvas=$('#game');
const renderDpr=()=>Math.min(window.devicePixelRatio||1,mobile?(tabletLike?1.45:1.2):2);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',alpha:false,stencil:false,preserveDrawingBuffer:false});
renderer.setPixelRatio(renderDpr());renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=.96;renderer.shadowMap.enabled=shadows;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xb7c4bd);scene.fog=new THREE.Fog(0xb7c4bd,58,145);const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.07,220);
const bands=new Uint8Array([48,48,48,255,115,115,115,255,184,184,184,255,255,255,255,255]),gradient=new THREE.DataTexture(bands,4,1,THREE.RGBAFormat);gradient.needsUpdate=true;gradient.magFilter=THREE.NearestFilter;gradient.minFilter=THREE.NearestFilter;
const outlineMat=new THREE.MeshBasicMaterial({color:0x252821,side:THREE.BackSide}),boxCache=new Map();
const toon=(c,map=null)=>new THREE.MeshStandardMaterial({color:c,map,roughness:.82});
const boxGeo=s=>{const k=s.join(',');if(!boxCache.has(k))boxCache.set(k,new THREE.BoxGeometry(...s));return boxCache.get(k)};
function box(size,pos,color,parent,outline=true){const g=boxGeo(size),m=new THREE.Mesh(g,toon(color));m.position.set(...pos);m.castShadow=shadows;m.receiveShadow=shadows;parent.add(m);if(false&&outline){const o=new THREE.Mesh(g,outlineMat);o.position.copy(m.position);o.rotation.copy(m.rotation);o.scale.set(1.018,1.018,1.018);parent.add(o)}return m}
function mesh(geo,pos,color,parent,outline=true){const m=new THREE.Mesh(geo,toon(color));m.position.set(...pos);m.castShadow=shadows;m.receiveShadow=shadows;parent.add(m);if(false&&outline){const o=new THREE.Mesh(geo,outlineMat);o.position.copy(m.position);o.scale.set(1.022,1.022,1.022);parent.add(o)}return m}
function signTex(a,b,accent='#9b4035'){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#efe3c7';x.fillRect(0,0,512,128);x.fillStyle=accent;x.fillRect(0,0,14,128);x.strokeStyle='#252821';x.lineWidth=5;x.strokeRect(5,5,502,118);x.fillStyle='#252821';x.textAlign='center';x.textBaseline='middle';x.font='700 43px Yu Gothic,system-ui';x.fillText(a,256,50);x.font='800 15px system-ui';x.fillText(b.toUpperCase(),256,99);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t}

const town=new THREE.Group(),room=new THREE.Group();scene.add(town,room);room.visible=false;
const ambient=new THREE.HemisphereLight(0xdde9ec,0x695c4d,1.35);scene.add(ambient);
const sun=new THREE.DirectionalLight(0xffd39a,highTier?3.8:3.2);sun.position.set(-28,38,18);sun.castShadow=shadows;
if(shadows){sun.shadow.mapSize.set(tabletLike?1024:2048,tabletLike?1024:2048);sun.shadow.camera.left=-34;sun.shadow.camera.right=34;sun.shadow.camera.top=64;sun.shadow.camera.bottom=-64;sun.shadow.camera.near=.5;sun.shadow.camera.far=120;sun.shadow.bias=-.00035;sun.shadow.normalBias=.045}scene.add(sun);

const SITES=[
  {id:'office',title:'The Office',jp:'事務所',sub:'HOME · ABOUT · LOCATIONS',side:-1,z:38,color:0x62776e,accent:'#49675d',url:'/',line:'Charts, travel notes and engineering papers.'},
  {id:'frontrow',title:'Front-Row Books',jp:'前列書房',sub:'THE FRONT-ROW SEAT',side:1,z:30,color:0x735849,accent:'#8b3f36',url:'/the-front-row-seat/',line:'The reading room is open until late.'},
  {id:'form3d',title:'Form 3D Workshop',jp:'立体工房',sub:'FORM 3D STUDIO',side:-1,z:18,color:0x566b73,accent:'#385f6e',url:'/form-3d-studio/',line:'Small parts, prototypes and fabrication work.'},
  {id:'stepwise',title:'StepWise Instruments',jp:'計算器店',sub:'ENGINEERING CALCULATOR',side:1,z:8,color:0x6b6753,accent:'#6c633d',url:'/stepbuddy/',line:'Measuring tools and calculation instruments.'},
  {id:'journal',title:'The Journal Press',jp:'日報印刷所',sub:'JOURNAL',side:-1,z:-4,color:0x78615c,accent:'#8f433d',url:'https://theofficeofnils.wordpress.com',line:'Fresh copy stacked beside the press.'},
  {id:'electronics',title:'Johansson Electronics',jp:'電子工作所',sub:'CODE · PROTOTYPES',side:1,z:-16,color:0x565f68,accent:'#3f515e',url:'https://github.com/nj22az',line:'Computers, circuits and unfinished experiments.'},
  {id:'market',title:'Colonial Club Market',jp:'雑貨市場',sub:'MARKET',side:-1,z:-28,color:0x7a684f,accent:'#8e6439',url:'https://www.etsy.com/shop/Colonialclub',line:'Practical goods and curious little objects.'},
  {id:'career',title:'Career Bureau',jp:'職歴案内所',sub:'PROFESSIONAL',side:1,z:-39,color:0x586c68,accent:'#3f615d',url:'https://www.linkedin.com/in/nils-johansson-86744583',line:'Records from ships, commissioning and field service.'}
];

const interactables=[],roomColliders=[],doors=new Map();
let inspector=null,content=null,castAI=null;
let current=null,active=null,started=false,yaw=0,pitch=-.1,cam=0,minutes=1002,subtitleTimer=0,weather=false,activities=null,timePreset=0,characters=null;
const keys={},clock=new THREE.Clock(),moveTouch={id:null,cx:0,cy:0,x:0,y:0},lookTouch={id:null,x:0,y:0};
const PLAYER_RADIUS=.28,NPC_RADIUS=.35,CAMERA_RADIUS=.1,MAX_FRAME_DT=.08,SIM_STEP=1/60;
const move2=new THREE.Vector2(),fwVec=new THREE.Vector3(),rtVec=new THREE.Vector3(),moveVec=new THREE.Vector3(),turnQ=new THREE.Quaternion(),yAxis=new THREE.Vector3(0,1,0),camTarget=new THREE.Vector3(),camDesired=new THREE.Vector3(),camResolved=new THREE.Vector3();

const player=new THREE.Group();scene.add(player);player.position.set(0,0,46);
mesh(new THREE.SphereGeometry(.21,12,10),[0,1.75,0],0xd19b73,player);box([.54,.7,.28],[0,1.2,0],0x3f5862,player);box([.19,.62,.19],[-.16,.54,0],0x29343a,player);box([.19,.62,.19],[.16,.54,0],0x29343a,player);

const reg=(o,label,fn,inside=false)=>{o.userData.hit={label,fn,inside};interactables.push(o)};
function say(t,sec=3){const e=$('#subtitle');e.textContent=t;e.classList.add('on');subtitleTimer=sec}

const world=createTown({scene:town,sites:SITES,mobile,shadows,maxAnisotropy:renderer.capabilities.getMaxAnisotropy(),register:reg,enter:enterRoom,getPlayerPosition:()=>player.position,onAction:(...args)=>{if(args[0]==='resident'){const person=world.people.find(p=>p.g.userData.name===args[1]);if(person){person.g.userData.facePlayerUntil=performance.now()+1600;person.g.lookAt(player.position.x,0,player.position.z);person.g.rotateY(Math.PI);characters?.gesture(person.g);}}if(args[1]==='Convex traffic mirror')world.beats?.mirror();activities.action(...args);}});
SITES.forEach(s=>doors.set(s.id,new THREE.Vector3(s.side*5.9,0,s.z+2.5)));
activities=createActivities({say,getMinutes:()=>minutes,onPhone:()=>{const p=world.people.find(p=>p.g.userData.name==='Harbour master');if(p?.g.position.z<-63){characters.gesture(p.g);activities.close();say('The harbour master waves from the pier.',4);return true;}return false;},onEscort:()=>{activities.state.kenjiEscort='walking';activities.save();},onWeather:value=>{weather=value;world.setRain(value);},onTime:value=>{if(value==='cycle'){timePreset=(timePreset+1)%4;minutes=[1002,1110,1230,540][timePreset];}else minutes+=value;},onCamera:()=>{cam=(cam+1)%4;say(['Follow camera','Wide camera','Close camera','First person'][cam]);}});
characters=createCharacters({mobile,shadows,onError:(name,error)=>console.warn('Character construction failed:',name,error)});characters.attach(player,'player',1.82);world.people.forEach(p=>characters.attach(p.g,p.g.userData.name));

inspector=createInspector({scene,camera,renderer,canvas,resetInput,onReturn:item=>{const o=content?.objects.get(item.id);if(o)o.visible=true;},onInspect:item=>{const o=content?.objects.get(item.id);if(o)o.visible=false;activities.inspectItem(item);if(item.id==='model')say(item.note,4);},onLink:url=>activities.openURL(url),onContact:()=>activities.note('nj22az.github.io · LinkedIn via Selected Work')});
content=createContentItems({group:world.group,colliders:world.colliders,register:reg,onInspect:item=>inspector.open(item),onRead:()=>activities.quietRead()});
castAI=createCastAI({world,player,state:()=>activities.state,paused:()=>activities.paused||inspector.active,collides:(x,z,r)=>townBoundsBlocked(x,z,r)||world.colliders.some(c=>circleHitsRect(x,z,r,c))});
function roomHit(object,label,kind,title,text){reg(object,label,()=>activities.action(kind,title,text),true);return object;}
function roomCollider(x,z,w,d){roomColliders.push({x,z,w,d});}
function furnitureBox(size,pos,color,label,title,text,kind='inspect',collide=true){const m=box(size,pos,color,room);if(collide)roomCollider(pos[0],pos[2],size[0]+.08,size[2]+.08);return roomHit(m,label,kind,title,text);}
function wallPanel(text,sub,pos,w=2.6,h=.82,accent='#6f5545'){const p=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:signTex(text,sub,accent)}));p.position.set(...pos);room.add(p);return p;}
function addChair(x,z,title='Chair',text='A sturdy chair polished smooth by years of use.'){const g=new THREE.Group();g.position.set(x,0,z);room.add(g);box([.7,.12,.68],[0,.62,0],0x4f5d58,g);box([.7,.72,.10],[0,1,.29],0x4f5d58,g);for(const dx of [-.25,.25])for(const dz of [-.25,.25])box([.09,.62,.09],[dx,.31,dz],0x3f4744,g,false);roomCollider(x,z,.78,.78);roomHit(g,'Sit down','seat',title,text);return g;}
function addDesk(x,z,title='Desk',text='A practical wooden desk with carefully arranged paperwork.'){const g=new THREE.Group();g.position.set(x,0,z);room.add(g);box([2.2,.18,1],[0,.82,0],0x765b43,g);for(const dx of [-.88,.88])for(const dz of [-.35,.35])box([.16,.72,.16],[dx,.36,dz],0x4b4036,g,false);roomCollider(x,z,2.3,1.08);roomHit(g,'Inspect desk','inspect',title,text);return g;}
function addShelf(x,z,title,text,books=true){const g=new THREE.Group();g.position.set(x,0,z);room.add(g);box([1.7,2.55,.45],[0,1.28,0],0x5a4636,g);for(let y=.42;y<2.3;y+=.48){box([1.48,.08,.52],[0,y,0],0x8a694c,g,false);if(books)for(let n=0;n<7;n++)box([.13,.3+(n%2)*.06,.22],[-.58+n*.19,y+.19,.25],[0x975544,0x486975,0xb2a57e,0x677c62][n%4],g,false);}roomCollider(x,z,1.8,.62);roomHit(g,'Browse shelves','inspect',title,text);return g;}
function addCabinet(x,z,title,text,color=0x53615f){const g=new THREE.Group();g.position.set(x,0,z);room.add(g);box([1.1,2.15,.55],[0,1.08,0],color,g);for(let y=.38;y<1.9;y+=.38){box([.86,.29,.035],[0,y,-.292],0x7b8178,g,false);box([.12,.025,.025],[0,y,-.318],0x2c3434,g,false);}roomCollider(x,z,1.2,.65);roomHit(g,'Open cabinet','inspect',title,text);return g;}
function addScreen(x,z,title,text){const g=new THREE.Group();g.position.set(x,0,z);room.add(g);box([.95,.7,.65],[0,1.48,.28],0x303a39,g);box([.62,.42,.03],[0,1.48,-.055],0x6e8b83,g,false);box([.12,.38,.12],[0,1.08,0],0x303a39,g,false);roomHit(g,'Use terminal','machine',title,text);return g;}
function addMachine(x,z,w,d,h,color,title,text){const g=new THREE.Group();g.position.set(x,0,z);room.add(g);box([w,h,d],[0,h/2,0],color,g);box([w*.66,.24,.06],[0,h*.72,-d/2-.035],0x253b3e,g,false);for(let i=-1;i<=1;i++)box([.09,.09,.04],[i*w*.18,h*.43,-d/2-.055],[0xb45d46,0xd0aa55,0x5f8b72][i+1],g,false);roomCollider(x,z,w+.12,d+.12);roomHit(g,'Operate '+title,'machine',title,text);return g;}
function addCounter(x,z,w,title,text){const g=new THREE.Group();g.position.set(x,0,z);room.add(g);box([w,.9,.72],[0,.45,0],0x795d43,g);box([w+.12,.08,.82],[0,.94,0],0x9a7654,g,false);roomCollider(x,z,w+.1,.82);roomHit(g,'Inspect counter','inspect',title,text);return g;}
function addCrates(x,z,title='Delivery crates',text='Wooden crates are stacked with their labels facing the aisle.'){const g=new THREE.Group();g.position.set(x,0,z);room.add(g);box([1,.72,1],[0,.36,0],0x9a764e,g);box([.85,.58,.85],[.8,.29,.55],0x806447,g);roomCollider(x+.3,z+.2,1.8,1.5);roomHit(g,'Inspect crates','inspect',title,text);return g;}
function addLamp(x,z){const stem=box([.08,1.45,.08],[x,.73,z],0x4b4f4a,room,false);const shade=mesh(new THREE.CylinderGeometry(.28,.42,.28,12),[x,1.55,z],0xb99a69,room,false);shade.rotation.x=Math.PI;roomHit(stem,'Switch lamp','inspect','Desk lamp','A compact late-1980s lamp with a warm tungsten bulb.');}

function addRoomProps(s){
  const warm=new THREE.PointLight(0xffcf91,highTier?2.0:1.35,14,2);warm.position.set(0,3.45,-.5);warm.castShadow=false;room.add(warm);
  box([12.4,.12,12.4],[0,4.25,0],0x6f7168,room,false);box([12.1,.035,12.1],[0,.04,0],s.id==='market'?0x80715d:0x706b5e,room,false);for(const x of [-5.7,5.7])box([.08,3.7,12],[x,2.1,0],0x4b4339,room,false);

  if(s.id==='office'){
    wallPanel('世界地図','FIELD SERVICE ROUTES',[-3.3,2.65,-6.25],3.3,1.05,s.accent);addDesk(-2.55,-1.65,'Field-service desk','Route sheets, calibration certificates and handwritten travel notes are spread across the desk.');addScreen(-2.55,-1.7,'Office computer','A beige workstation holds service records and travel planning files.');addChair(-.55,-1.55,'Visitor chair','A plain visitor chair facing the engineering desk.');addCabinet(3.35,-2.35,'Drawing cabinet','Folders contain electrical drawings, calibration sheets and old ship-engine notes.');furnitureBox([1.1,.72,.55],[3.3,.36,.2],0x8a6b4f,'Use typewriter','Typewriter','The keys are slightly stiff. A half-written service report waits in the carriage.','machine');addLamp(-3.3,-.5);
  } else if(s.id==='frontrow'){
    wallPanel('海洋書','MARITIME · HISTORY',[2.8,2.75,-6.25],3.2,.9,s.accent);addShelf(-4.15,-2.7,'Maritime shelf','Voyages, harbour histories and worn biographies fill the shelves.');addShelf(-4.15,.25,'Wapping shelf','Books on London docks, sailors and the Thames sit beside a few annotated manuscripts.');addChair(2.3,-1.55,'Reading chair','A deep chair positioned under the warmest lamp in the bookshop.');furnitureBox([1.35,.12,1.35],[2.3,.58,.1],0x6b533d,'Browse display table','New arrivals','A display of maritime history, Japanese travel books and a copy of The Front-Row Seat.');roomCollider(2.3,.1,1.45,1.45);addCounter(2.9,2.65,2.4,'Bookshop counter','A ledger, pencil cup and small brass bell sit beside the till.');addLamp(1.45,-1.2);
  } else if(s.id==='form3d'){
    wallPanel('立体工房','PROTOTYPE BAY',[2.8,2.75,-6.25],3.1,.9,s.accent);addDesk(-2.8,-1.8,'CAD workbench','Sketches, calipers and dimensioned prototype drawings cover the bench.');addScreen(-2.8,-1.85,'CAD terminal','The monochrome display shows a simple mechanical enclosure model.');addMachine(2.65,-2.25,1.55,1.25,1.55,0x54666b,'Prototype mill','The guarded machine can run a short demonstration cycle.');addCrates(3.35,.5,'Material bins','ABS, aluminium blanks and sample hardware are sorted into labelled bins.');addCabinet(-4.25,1.5,'Tool cabinet','Drills, cutters, gauges and hand tools are arranged by size.');
  } else if(s.id==='stepwise'){
    wallPanel('計測器','MEASUREMENT DESK',[2.7,2.75,-6.25],3.0,.9,s.accent);addCounter(-2.9,-1.55,2.6,'Instrument counter','Micrometers, gauges and reference blocks are laid out on felt.');addMachine(2.65,-1.8,1.45,1.05,1.25,0x4e5b5d,'Bench calibrator','A reference instrument cycles through zero, span and verification checks.');furnitureBox([1.25,.55,.72],[-3.1,.28,1.2],0x59695f,'Try calculator','Desktop calculator','A heavy desktop calculator with bright segmented digits and satisfyingly firm keys.','machine');addCabinet(3.7,1.25,'Reference standards','Cases of certified reference pieces are locked behind glass.');addChair(-.8,-1.45,'Customer chair','A chair beside the instrument counter for reviewing measurements.');
  } else if(s.id==='journal'){
    wallPanel('日報','PRINT ROOM',[2.7,2.75,-6.25],2.8,.9,s.accent);addMachine(2.55,-1.8,1.8,1.35,1.45,0x5a615d,'Printing press','The press smells of ink and warm paper. Its rollers turn slowly during the demonstration.');addDesk(-2.8,-1.9,'Editor desk','Marked proofs, wax pencils and clipped local stories cover the editor’s desk.');furnitureBox([1.45,.75,.95],[-3.3,.38,1.15],0xd4cab0,'Inspect paper stack','Fresh newspapers','Bundles of freshly printed sheets are tied with string for delivery around town.');roomCollider(-3.3,1.15,1.55,1.05);addCabinet(3.65,1.4,'Type cabinet','Metal drawers contain headline type, stamps and printing tools.');
  } else if(s.id==='electronics'){
    wallPanel('電子工作所','TEST BENCH',[2.7,2.75,-6.25],3.0,.9,s.accent);addDesk(-2.8,-1.85,'Electronics bench','Solder, test leads, small circuit boards and handwritten schematics cover the bench.');addScreen(-2.8,-1.9,'Development terminal','A green-on-black terminal is connected to a compact development board.');addMachine(2.55,-1.85,1.45,1.05,1.15,0x43575d,'Oscilloscope','The trace settles into a clean repeating waveform after a short test.');addCabinet(3.65,1.25,'Parts drawers','Resistors, capacitors, connectors and spare ICs are sorted into dozens of small drawers.');furnitureBox([1.0,.52,.55],[-3.7,.26,1.25],0x6e5843,'Tune workshop radio','Workshop radio','A small radio carries weather, baseball scores and harbour traffic reports.','machine');
  } else if(s.id==='market'){
    wallPanel('雑貨市場','HOUSEHOLD · IMPORTS',[2.6,2.75,-6.25],3.2,.9,s.accent);addShelf(-4.15,-2.45,'Dry-goods shelf','Tea, tins, stationery and household goods are packed tightly along the shelf.');addShelf(-4.15,.45,'Import shelf','Small imported goods and travel curios are arranged behind handwritten price cards.');addCounter(2.75,-1.0,2.8,'Market counter','A mechanical till, wrapping paper and a small scale sit on the counter.');addCrates(2.8,1.55,'Produce crates','Seasonal fruit and vegetables are packed in shallow wooden crates.');furnitureBox([.85,1.45,.65],[4.7,.73,-3.65],0x8f4d40,'Use drinks cooler','Glass-front cooler','Cold bottled tea and soft drinks sit behind fogged glass.','inspect');
  } else if(s.id==='career'){
    wallPanel('職歴','CAREER ARCHIVE',[2.7,2.75,-6.25],3.0,.9,s.accent);addDesk(-2.7,-1.8,'Career desk','A neatly ordered CV, certificates and field-service records are arranged for review.');addScreen(-2.7,-1.85,'Career terminal','The terminal provides access to the professional profile and current work history.');addCabinet(3.45,-2.3,'Personnel archive','Folders cover marine engineering, turbines, materials testing and commissioning work.');addCabinet(3.45,.45,'Training archive','Course notes cover automation, hydraulics, electrical systems and calibration.');addChair(-.55,-1.55,'Interview chair','A simple chair facing the career desk.');
  }
}

function clearRoom(){roomColliders.length=0;const materials=new Set(),geos=new Set();room.traverse(o=>{if(o.isMesh){const list=Array.isArray(o.material)?o.material:[o.material];list.forEach(m=>m&&materials.add(m));if(![...boxCache.values()].includes(o.geometry))geos.add(o.geometry);}});materials.forEach(m=>{m.map?.dispose?.();m.dispose?.();});geos.forEach(g=>g.dispose?.());while(room.children.length)room.remove(room.children[0]);for(let i=interactables.length-1;i>=0;i--)if(interactables[i].userData?.hit?.inside)interactables.splice(i,1);}
function roomShell(s){clearRoom();town.visible=false;room.visible=true;box([13,.18,13],[0,-.08,0],0x9e957f,room,false);box([13,4.4,.24],[0,2.2,-6.45],s.color,room);box([.24,4.4,13],[-6.45,2.2,0],s.color,room);box([.24,4.4,13],[6.45,2.2,0],s.color,room);box([5,4.4,.24],[-4,2.2,6.45],s.color,room);box([5,4.4,.24],[4,2.2,6.45],s.color,room);box([3,1.4,.24],[0,3.7,6.45],s.color,room);const back=new THREE.Mesh(new THREE.PlaneGeometry(5.8,1.35),new THREE.MeshToonMaterial({map:signTex(s.jp,s.title,s.accent),gradientMap:gradient}));back.position.set(0,3.35,-6.28);room.add(back);const notice=new THREE.Mesh(new THREE.PlaneGeometry(3.7,1.7),new THREE.MeshToonMaterial({map:signTex(s.title,s.line,s.accent),gradientMap:gradient}));notice.position.set(-3.2,1.9,-6.27);room.add(notice);reg(notice,'Read wall notice',()=>activities.action('inspect',`${s.title} notice`,s.line),true);const terminal=box([2.3,2.55,.18],[.4,1.28,-5.95],0x2e3b3a,room);roomColliders.push({x:.4,z:-5.95,w:2.4,d:.32});reg(terminal,'Open '+s.title,()=>openLink(s.url),true);const terminalLabel=new THREE.Mesh(new THREE.PlaneGeometry(1.95,.65),new THREE.MeshBasicMaterial({map:signTex('接続','OPEN '+s.title,s.accent)}));terminalLabel.position.set(.4,1.7,-5.83);room.add(terminalLabel);const exit=new THREE.Mesh(new THREE.PlaneGeometry(2.45,2.7),toon(0x8c684d));exit.position.set(0,1.35,6.31);exit.rotation.y=Math.PI;room.add(exit);reg(exit,'Exit to street',leaveRoom,true);}
function enterRoom(s){activities.close();activities.visit(s.id);current=s;roomShell(s);addRoomProps(s);player.position.set(0,0,4.3);yaw=0;active=null;$('#place').textContent=s.title.toUpperCase();$('#placeSub').textContent=`${s.jp} · ${s.sub}`;$('#timeText').textContent=s.line;say(`${s.title} — nearly everything in the room can be examined or used.`,2.5);camera.position.set(0,2.8,5.7)}
function leaveRoom(){active=null;const s=current;current=null;room.visible=false;town.visible=true;if(s){player.position.copy(doors.get(s.id));player.position.z+=.6}$('#place').textContent='JOHANSSON TOWN';$('#placeSub').textContent='ヨハンソン町 · HARBOUR DISTRICT';$('#timeText').textContent='Shops are open.';say('Johansson Street',1.5)}
function openLink(url){say('Connecting…',.7);const u=new URL(url,location.origin);if(u.origin===location.origin)location.href=u.href;else window.open(u.href,'_blank','noopener')}

function interaction(){active=null;let best=null,dmax=3.1;const p=player.position.clone();p.y=1;const fw=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));for(const o of interactables){const h=o.userData.hit;if(!o.visible||current&&!h.inside||!current&&h.inside)continue;const q=new THREE.Vector3();o.getWorldPosition(q);const v=q.sub(p),d=v.length();if(d>dmax)continue;v.y=0;if(v.lengthSq()&&fw.dot(v.normalize())<-.2)continue;dmax=d;best=h}const e=$('#prompt');if(best){active=best;e.textContent=(touch?'':'E · ')+best.label;e.classList.add('on')}else e.classList.remove('on')}
function doInteract(){if(inspector?.active)return;if(!activities.paused&&$('#directory').classList.contains('hidden')){interaction();active?.fn?.();}}
function environmentBlocked(x,z,r=PLAYER_RADIUS){const bounds=current?roomBoundsBlocked(x,z,r):townBoundsBlocked(x,z,r);if(bounds)return true;const list=current?roomColliders:world.colliders;return list.some(c=>circleHitsRect(x,z,r,c));}
function residentBlocked(x,z){return !current&&world.people.some(p=>circleHitsCircle(x,z,PLAYER_RADIUS,p.g.position.x,p.g.position.z,NPC_RADIUS));}
function collides(x,z){return environmentBlocked(x,z,PLAYER_RADIUS)||residentBlocked(x,z);}
function resolveCamera(target,desired){const safe=sweepFraction(target,desired,(x,z)=>environmentBlocked(x,z,CAMERA_RADIUS),.12);const t=Math.max(0,safe-.025);camResolved.lerpVectors(target,desired,t);return camResolved;}
function updatePlayer(dt){let f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),s=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0);if(moveTouch.id!==null){s+=THREE.MathUtils.clamp((moveTouch.x-moveTouch.cx)/48,-1,1);f+=THREE.MathUtils.clamp(-(moveTouch.y-moveTouch.cy)/48,-1,1);}move2.set(s,f);if(move2.lengthSq()>1)move2.normalize();fwVec.set(-Math.sin(yaw),0,-Math.cos(yaw));rtVec.set(Math.cos(yaw),0,-Math.sin(yaw));moveVec.copy(fwVec).multiplyScalar(move2.y).addScaledVector(rtVec,move2.x);if(moveVec.lengthSq()>.02){const speed=(keys.ShiftLeft||activities.state.sprintUntil>performance.now()?5.2:3)*dt,nx=player.position.x+moveVec.x*speed,nz=player.position.z+moveVec.z*speed;if(!collides(nx,player.position.z))player.position.x=nx;if(!collides(player.position.x,nz))player.position.z=nz;turnQ.setFromAxisAngle(yAxis,Math.atan2(-moveVec.x,-moveVec.z));player.quaternion.slerp(turnQ,1-Math.pow(.001,dt));}if(cam===3){player.visible=false;camera.position.copy(player.position).add(fwVec.set(0,1.7,0));camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);return;}const dist=[4.8,6.7,2.6][cam],h=Math.cos(pitch)*dist;camTarget.copy(player.position).add(fwVec.set(0,1.3,0));camDesired.set(camTarget.x+Math.sin(yaw)*h,camTarget.y+1+Math.sin(-pitch)*dist,camTarget.z+Math.cos(yaw)*h);const resolved=resolveCamera(camTarget,camDesired);camera.position.lerp(resolved,1-Math.pow(.00005,dt));camera.lookAt(camTarget);player.visible=camera.position.distanceTo(camTarget)>1.05;}

const fmt=m=>`${String(Math.floor((m%1440)/60)).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;
const daylight=m=>{const h=(m/60)%24;return h>=7&&h<17?1:h>=17&&h<20?1-(h-17)/3:h>=5&&h<7?(h-5)/2:0};
function setTime(){const h=(minutes/60)%24,day=daylight(minutes);sun.intensity=(.22+day*3.25)*(weather?.62:1);ambient.intensity=.55+day*.95;sun.color.set(h>=17&&h<20?0xffad72:0xffddb0);sun.position.set(-30,12+day*25,12);scene.background.set(weather?0x667985:day>.7?0x9fb5bc:day>.1?0x9a786f:0x14283e);scene.fog.color.copy(scene.background);scene.fog.near=weather?28:58;scene.fog.far=weather?118:155;renderer.toneMappingExposure=.84+day*.13;$('.timecard small').textContent=h<7?'EARLY MORNING':h<17?'AFTERNOON':h<20?'EVENING':'NIGHT';return day;}
function toggleDir(open){if(inspector?.active)return;if(open){updateDirectory();document.exitPointerLock?.();Object.keys(keys).forEach(k=>keys[k]=false);moveTouch.id=null;}$('#directory').classList.toggle('hidden',!open);if(open)$('#closeDirectory').focus();}
$('#directoryGrid').innerHTML=SITES.map(s=>`<button class="dir-item" data-id="${s.id}"><b>${s.title}</b><span>${s.sub}</span></button>`).join('');document.querySelectorAll('.dir-item').forEach(b=>b.onclick=()=>{if(current)leaveRoom();const s=SITES.find(x=>x.id===b.dataset.id);player.position.copy(doors.get(s.id));player.position.z+=.5;yaw=-s.side*Math.PI/2;toggleDir(false);say(s.title,1.4)});$('#directoryButton').onclick=()=>toggleDir(true);$('#closeDirectory').onclick=()=>toggleDir(false);
function updateDirectory(){
 const grid=$('#directoryGrid');grid.replaceChildren();
 const section=t=>{const h=document.createElement('h3');h.className='directory-section';h.textContent=t;grid.append(h);};
 const row=(title,sub,fn)=>{const b=document.createElement('button');b.className='dir-item';const strong=document.createElement('b'),small=document.createElement('span');strong.textContent=title;small.textContent=sub;b.append(strong,small);b.onclick=fn;grid.append(b);};
 const go=(x,z)=>{if(current)leaveRoom();player.position.set(x,0,z);yaw=0;toggleDir(false);};
 section('Street');SITES.forEach(s=>row(s.title,s.sub,()=>{const p=doors.get(s.id);go(p.x,p.z+.7);yaw=-s.side*Math.PI/2;}));
 section('Residents');world.people.filter(p=>p.g.visible).forEach(p=>row(p.g.userData.name,p.g.userData.activity||'On the street',()=>{activities.note(p.g.userData.name+' · '+(p.g.userData.activity||'on the street'));toggleDir(false);}));
 section('Office of Nils Johansson');content.items.forEach(i=>row(i.title,i.place,()=>{activities.note(i.title+' — '+i.place);toggleDir(false);say(i.place,4);}));
 section('Signals');[['82.1 Harbour Service','Harbour notices'],['89.4 JOJO','Journal requests'],['95.7 Sports','Prefectural baseball'],['Payphone','Near the bookshop'],['Harbour Line','Southern bus stop']].forEach(([a,b])=>row(a,b,()=>{toggleDir(false);say(a+' · '+b,4);}));
}
function runStabilityChecks(){const failures=[];if(!townBoundsBlocked(7,0,PLAYER_RADIUS))failures.push('town edge');if(!roomBoundsBlocked(5.5,0,PLAYER_RADIUS))failures.push('room edge');if(world.colliders.length<20)failures.push('world collider coverage');if((world.quality?.streetInteractions||0)<8)failures.push('street interaction coverage');for(const [id,p] of doors)if(environmentBlocked(p.x,p.z,.16))failures.push(`door spawn ${id}`);window.__JOHANSSON_STABILITY__={ok:failures.length===0,failures,colliders:world.colliders.length,characterCount:world.people.length+1,streetInteractions:world.quality?.streetInteractions||0,renderDpr:renderer.getPixelRatio(),toneMapping:'AgX',shadows};if(failures.length)console.error('Johansson Town stability checks failed',failures);else console.info('Johansson Town stability checks passed',window.__JOHANSSON_STABILITY__)}

started=true;$('#start').classList.add('hidden');$('#hud').classList.remove('hidden');window.__JOHANSSON_RUNNING__=true;camera.position.set(0,3.5,50);say('Aiko is by the book display ahead. The harbour office keeps a blue-taped folio towards the water.',5);runStabilityChecks();
canvas.onclick=()=>{if(inspector?.active)return;if(started&&!touch&&$('#directory').classList.contains('hidden'))canvas.requestPointerLock?.()?.catch?.(()=>{})};document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==canvas||activities.paused||inspector?.active)return;yaw-=e.movementX*.0023;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0018,-.42,.34)});document.addEventListener('keydown',e=>{if(activities.paused)return;if(e.code==='Escape'){toggleDir(false);return;}if(!$('#directory').classList.contains('hidden')){if(e.code==='KeyQ')toggleDir(false);return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(!started)return;if(e.code==='KeyE'&&!e.repeat)doInteract();if(e.code==='KeyQ'&&!e.repeat)toggleDir(true);if(e.code==='KeyB'&&!e.repeat)activities.inventory();if(e.code==='KeyV'&&!e.repeat)$('#cameraButton').click();if(e.code==='KeyN'&&!e.repeat)$('#timeButton').click();});document.addEventListener('keyup',e=>keys[e.code]=false);$('#act').onpointerdown=e=>{e.preventDefault();doInteract()};

const stick=$('#stick'),knob=$('#knob');canvas.addEventListener('touchstart',e=>{if(!started||activities.paused||!$('#directory').classList.contains('hidden')||!$('#qte').classList.contains('hidden'))return;const r=stick.getBoundingClientRect();for(const t of e.changedTouches){if(t.clientX<innerWidth*.48&&moveTouch.id===null){moveTouch.id=t.identifier;moveTouch.cx=r.left+r.width/2;moveTouch.cy=r.top+r.height/2;moveTouch.x=t.clientX;moveTouch.y=t.clientY}else if(lookTouch.id===null){lookTouch.id=t.identifier;lookTouch.x=t.clientX;lookTouch.y=t.clientY}}e.preventDefault()},{passive:false});canvas.addEventListener('touchmove',e=>{for(const t of e.changedTouches){if(t.identifier===moveTouch.id){moveTouch.x=t.clientX;moveTouch.y=t.clientY;knob.style.transform=`translate(${THREE.MathUtils.clamp(t.clientX-moveTouch.cx,-42,42)}px,${THREE.MathUtils.clamp(t.clientY-moveTouch.cy,-42,42)}px)`}else if(t.identifier===lookTouch.id){yaw-=(t.clientX-lookTouch.x)*.005;pitch=THREE.MathUtils.clamp(pitch-(t.clientY-lookTouch.y)*.0037,-.42,.34);lookTouch.x=t.clientX;lookTouch.y=t.clientY}}e.preventDefault()},{passive:false});function endTouch(e){for(const t of e.changedTouches){if(t.identifier===moveTouch.id){moveTouch.id=null;knob.style.transform='translate(0,0)'}if(t.identifier===lookTouch.id)lookTouch.id=null}}canvas.addEventListener('touchend',endTouch,{passive:false});canvas.addEventListener('touchcancel',endTouch,{passive:false});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();started=false;const d=$('#fatal');if(d){d.classList.remove('hidden');d.querySelector('p').textContent='Graphics paused safely. Reload Johansson Town to continue.'}});canvas.addEventListener('webglcontextrestored',()=>location.reload());function resizeRenderer(){renderer.setPixelRatio(renderDpr());renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resizeRenderer);window.visualViewport?.addEventListener('resize',resizeRenderer);function resetInput(){Object.keys(keys).forEach(k=>keys[k]=false);moveTouch.id=null;lookTouch.id=null;knob.style.transform='translate(0,0)';}addEventListener('blur',resetInput);document.addEventListener('visibilitychange',()=>{resetInput();if(!document.hidden)clock.getDelta();});

const mapCanvas=$('#minimap'),mapCtx=mapCanvas.getContext('2d');function drawMap(){const ctx=mapCtx,w=mapCanvas.width,h=mapCanvas.height;ctx.fillStyle='#172b35';ctx.fillRect(0,0,w,h);const px=x=>w/2+x*3,pz=z=>(z+66)/130*h;ctx.fillStyle='#58686a';ctx.fillRect(px(-7),0,42,h);ctx.fillStyle='#527e8a';ctx.fillRect(0,0,w,11);for(const s of SITES){ctx.fillStyle=activities.state.visited.includes(s.id)?'#dfb971':'#b9baab';ctx.fillRect(px(s.side<0?-13:8),pz(s.z)-4,15,8);}ctx.fillStyle='#df8a63';world.people.forEach(p=>{ctx.beginPath();ctx.arc(px(p.g.position.x),pz(p.g.position.z),2,0,Math.PI*2);ctx.fill();});const pos=current?doors.get(current.id):player.position;ctx.save();ctx.translate(px(pos.x),pz(pos.z));ctx.rotate(-yaw);ctx.fillStyle='#fff4ce';ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(4,4);ctx.lineTo(-4,4);ctx.fill();ctx.restore();ctx.font='8px monospace';ctx.fillStyle='#f7e8bc';for(const [label,z] of [['BOOKSHOP',35],['NOTICE BOARD',-47],['HARBOUR OFFICE',-53],['WORKSHOP',-58]])ctx.fillText(label,2,(z+82)/144*h);}
let elapsed=0,mapTick=0,stepTick=0;function simulate(frameDt){let remaining=Math.min(frameDt,MAX_FRAME_DT);while(remaining>.0001){const dt=Math.min(SIM_STEP,remaining);minutes+=dt*.16;elapsed+=dt;updatePlayer(dt);if(!current){world.update(dt,elapsed,daylight(minutes));castAI?.update(dt,minutes,weather);world.beats?.update(dt,elapsed,minutes);}remaining-=dt;}}
function loop(){requestAnimationFrame(loop);const frameDt=Math.min(clock.getDelta(),MAX_FRAME_DT);if(started&&!document.hidden){const paused=inspector?.active||activities.paused||!$('#directory').classList.contains('hidden');if(!paused){const before=player.position.clone();simulate(frameDt);if(player.position.distanceTo(before)>.01&&(stepTick+=frameDt)>.42){activities.footstep(current?'wood':player.position.z<-64?'timber':'asphalt');stepTick=0;}interaction();}else{resetInput();$('#prompt').classList.remove('on');}$('#clock').textContent=fmt(minutes);setTime();if(!inspector?.active){characters?.update(frameDt);castAI?.pose(frameDt);}if((mapTick+=frameDt)>.15){drawMap();mapTick=0;}if(subtitleTimer>0&&(subtitleTimer-=frameDt)<=0)$('#subtitle').classList.remove('on');if(inspector?.active)inspector.render(frameDt);else renderer.render(scene,camera)}}renderer.render(scene,camera);loop();
