// Swedish teaching manuscript. slides refer to Multimeter_Sjoskolan_v7_SV.pptx.
// Spoken text spells out numbers deliberately; on-screen notation stays technical.
export const chapters = [
 'Välkommen ombord', 'U, I och R', 'Lär känna instrumentet', 'Spänning',
 'Ström', 'Resistans och kontinuitet', 'CAT och instrumentval',
 'Upplösning och felgräns', 'Tolerans och protokoll', 'Belastningsfel',
 'Strömmätarens påverkan', 'Din egen mätning'
];
const s = (id, chapter, title, visual, slides, key, say, extra={}) => ({id,chapter,title,visual,slides,key,say,...extra});
export const scenes = [
s('ombord',0,'Varför lyser inte hyttlampan?','intro',[1,2],'En bra mätning börjar med en fråga.',
 'En mörk hyttlampa. Ska vi gissa, eller mäta? Följ kadetten Saga och Måsen genom Sjöskolans multimeterlabb. Vi tränar koppling, instrumentval och beräkningar. Till sist skriver vi ett resultat som nästa vakt kan förstå.'),
s('voltbegrepp',1,'Spänning jämför två punkter','quantity',[3,4],'U mäts i volt, V.',
 'Spänning är skillnaden i elektrisk potential mellan två punkter. Symbolen är U och enheten volt. Mätaren jämför den röda spetsens punkt med den svarta. Därför behöver en spänningsmätning alltid två mätpunkter.',{quantity:'U'}),
s('amperebegrepp',1,'Ström passerar genom en gren','quantity',[3,4],'I mäts i ampere, A.',
 'Ström beskriver hur mycket elektrisk laddning som passerar per sekund. Symbolen är I och enheten ampere. För att mäta ström måste grenens ström gå genom instrumentet. De rörliga markeringarna visar strömriktningen i vår modell, inte laddningarnas verkliga hastighet.',{quantity:'I'}),
s('ohmbegrepp',1,'Resistans begränsar strömmen','quantity',[3,4],'R mäts i ohm, Ω.  U = R · I',
 'Resistans beskriver motstånd mot ström. Symbolen är R och enheten ohm. För en resistiv last gäller Ohms lag. Tolv volt över hundratjugo ohm ger noll komma ett ampere. Lampan behandlas här som ett konstant motstånd. En verklig lampa kan ändra resistans med temperaturen.',{quantity:'R'}),
s('rigg',2,'Vår strömbegränsade 12 V-rigg','rig',[5,6],'F1: säkring   S1: brytare   H1: lampa',
 'Här finns en tolvvoltskälla med skyddande avskiljning och strömbegränsning. F ett är säkringen, S ett brytaren och H ett hyttlampan. P ett och P två är lampans anslutningar. Returen går tillbaka till källan. Praktisk inkoppling görs vid handledd laboration.'),
s('instrument',2,'Vred, display och uttag','meter',[7,8],'Funktion och uttag måste stämma överens.',
 'Vredet väljer funktionen. Displayen visar tal, enhet och mätläge. Likspänning heter D C, växelspänning A C. Svart ledning sitter i COM. Röd sitter i volt och ohm, eller i rätt strömingång. Autorange väljer mätområde, men du väljer fortfarande funktion och uttag.'),
s('forkontroll',2,'Kontroll före anslutning','check',[9],'Fråga → kontroll → koppling → avläsning',
 'Vad ska mätas, mellan vilka punkter och ungefär hur mycket? Kontrollera hela sladdar, mätspetsar och instrument. Välj rätt funktion, uttag och område. Kontrollera kopplingen innan matningen slås på. I vår rigg sker omkoppling alltid med matningen frånkopplad.'),
s('voltforkoppling',3,'Spänning: koppla med matningen av','voltage',[10,11,12,13],'Svart: COM till P2. Röd: VΩ till P1.',
 'Vi vill mäta över lampan. Med matningen frånkopplad väljer Saga volt likspänning. Svart går från COM till P två. Röd går från voltuttaget till P ett. Lampans strömväg är obruten. Mätaren ligger parallellt med lampan. COM betyder inte automatiskt jord.',{powered:false}),
s('voltavlasning',3,'Spänning: läs tal, enhet och läge','voltage',[14,16],'12,00 V DC. Mätaren ligger parallellt.',
 'När kopplingen är kontrollerad slår vi på riggens matning. Modellen visar tolv komma noll noll volt likspänning. Voltmeterns höga ingångsresistans gör att bara en liten ström går genom mätaren. Vi återkommer till varför även den lilla strömmen kan påverka resultatet.',{powered:true}),
s('polaritet',3,'Omvänd polaritet ger minustecken','voltage',[15],'−12,00 V: samma belopp, omvänd jämförelse.',
 'Vi bryter först matningen och byter plats på spetsarna. Efter kontroll slås matningen på igen. Nu visar instrumentet minus tolv volt. Spänningens belopp är detsamma. Minustecknet visar att den röda punkten ligger på lägre potential än den svarta.',{powered:true,reversed:true}),
s('stromkoppling',4,'Ström: öppna och fyll strömvägen','current',[17,18,19],'Matning AV. Mätaren kopplas i serie.',
 'Nu vill vi mäta lampans ström. Bryt matningen och öppna länken mellan K ett och K två. Välj ampere likström och en strömingång med rätt gränser enligt manualen. Röd ansluts till K ett och svart COM till K två. Mätaren fyller öppningen.',{powered:false}),
s('stromavlasning',4,'All lampström går genom mätaren','current',[20],'I = 12 V / 120 Ω = 0,10 A',
 'Efter handledarens kontroll slås matningen på. All ström i lampgrenen går nu genom mätaren. Vår förenklade modell visar noll komma ett ampere, alltså hundra milliampere. Anteckna den verkliga avläsningen med enhet. Instrumentets säkring, tidsgräns och strömgräns måste följas.',{powered:true}),
s('aterstall',4,'Tillbaka till en säker grundinställning','restore',[21],'Bryt matningen. Röd ledning tillbaka till VΩ.',
 'Efter strömmätningen bryter vi matningen. Ta bort mätaren och återställ länken i kretsen. Flytta den röda ledningen tillbaka till volt och ohm. Den vanan minskar risken att nästa spänningsmätning börjar med en farlig felkoppling.'),
s('feluttag',4,'Pausa: vad är fel på mätaren?','wrong',[22,23],'V-läge + röd i A-uttaget = fel inför spänningsmätning.',
 'Måsen vill mäta spänning. Vredet står rätt, men den röda sladden sitter kvar i ampereuttaget. Vad måste ändras? Pausa gärna filmen. Strömingången har låg resistans och kan kortsluta en källa. Att bara vrida till volt gör inte det felaktiga uttaget säkert. Prova inte felkopplingen.',{pause:true}),
s('resistans',5,'Ohm: instrumentet skickar en testsignal','ohm',[24,25,26],'Frånskild, kontrollerad och urladdad krets.',
 'Vid resistansmätning skickar mätaren själv en liten testsignal. Koppla bort matningen, kontrollera att spänningen är borta och hantera lagrad energi säkert. Isolera komponenten genom att lossa minst en anslutning. Med COM, volt och ohm, och vredet på ohm mäter vi tusen ohm, alltså ett kiloohm.'),
s('kontinuitet',5,'Summern hittar en ledande väg','continuity',[27,28,29],'Låg resistans kan ge pip. Avbrott kan ge OL.',
 'Med frånskild och kontrollerad utrustning väljer vi summer. Testa först spetsarna mot varandra. Låg resistans ger normalt ett pip. En hel uttagen säkring ger också låg resistans. En bruten väg kan visa O L. Det kan även betyda för hög resistans. Ett pip bevisar aldrig spänningslöshet.'),
s('parallellohm',5,'Två vägar ändrar resistansvärdet','parallel',[30,31,32],'1 kΩ parallellt med 1 kΩ = 500 Ω',
 'Två tusenohmsmotstånd sitter parallellt utan yttre matning. Mätarens testström får två vägar och instrumentet visar femhundra ohm. När en gren lossas återstår en väg och värdet blir tusen ohm. Därför kan en komponent mätas fel om andra strömvägar sitter kvar.'),
s('transient',6,'CAT handlar om mätmiljöns påfrestningar','transient',[33],'En kort spänningstopp kan starta ett farligt fel.',
 'En transient är en mycket kort spänningstopp, till exempel när en motor kopplas från. Om isoleringen bryts igenom kan matningen fortsätta driva en kortslutning och en farlig ljusbåge. CAT beskriver den mätmiljö som instrumentets skydd har provats för. Samma driftspänning kan kräva olika kategori.'),
s('katkarta',6,'Från apparat till inkommande matning','categories',[34],'CAT II: apparat. CAT III: fast installation. CAT IV: servis.',
 'CAT två gäller exempelvis stickproppsanslutna apparater på förbrukarsidan. CAT tre gäller fast installation, centraler och fast anslutna motorer, även enfas. CAT fyra gäller lågspänningsinstallationens matningspunkt. Det betyder inte alla ledningar utomhus. Äldre CAT ett avser kretsar utan direkt nätanslutning. Kontrollera deras särskilda gränser i manualen.'),
s('katvolt',6,'Läs både kategori och märkspänning','ratings',[35],'CAT III 1 000 V / CAT IV 600 V kan stå på samma mätare.',
 'Kan en CAT två-mätare ha högre voltal än en CAT fyra-mätare? Ja. Men ett högre voltal ersätter aldrig rätt kategori. Samma instrument kan ha flera märkningar. Högre kategori kräver inte automatiskt lägre märkspänning. Kontrollera spänningen till jord, mellan uttagen och gränserna för den valda funktionen.'),
s('katimpuls',6,'Provimpuls är inte tillåten mätspänning','impulse',[36],'Samma provspänning kan innebära olika provström.',
 'I tabellens exempel provas CAT två, tusen volt, och CAT tre, sexhundra volt, med sex tusen volts korta impulser. Men provkällans resistans är tolv respektive två ohm. Lägre resistans kan ge större ström. CAT fyra, sexhundra volt, provas här med åtta tusen volt. Detta är provvärden, aldrig tillåtna kontinuerliga mätspänningar.'),
s('katval',6,'Pausa: vilket instrument uppfyller kravet?','choose',[37,38,39],'Krav: CAT III 600 V. Kontrollera även sladdar och spetsar.',
 'Arbetsplanen kräver CAT tre, sexhundra volt. A är CAT två, tusen volt. B är CAT tre, sexhundra volt. Vilket väljer du? B uppfyller båda delarna. Hela mätutrustningen måste klara kravet. En CAT fyra-mätare med CAT två-spetsar räcker inte. Även borttagna spetsskydd kan ändra märkningen. Läs manualen.',{pause:true}),
s('upplosning',7,'Fler siffror är inte samma sak som mindre fel','resolution',[41,42],'12,00 → 12,01 V: ett steg är 0,01 V.',
 'Upplösning är det minsta steget på skärmen. Här är skillnaden mellan tolv komma noll noll och tolv komma noll ett volt en hundradels volt. Felgränsen beskriver instrumentets specificerade avvikelse under angivna villkor. Toleransen beskriver i stället vad utrustningen får ligga inom. Blanda inte ihop begreppen.'),
s('fel12',7,'Felgräns: procentdel plus sifferdel','accuracy',[43,44,45,46],'12,00 V ±0,08 V ger 11,92–12,08 V.',
 'Anta specifikationen plus minus noll komma fem procent av visningen, plus två siffror. Ett steg är noll komma noll ett volt. Vid tolv volt blir procentdelen noll komma noll sex volt och sifferdelen noll komma noll två. Summan ger plus minus noll komma noll åtta volt. Intervallet gäller bara denna instrumentfelgräns.',{example:12}),
s('fel24',7,'Pausa och beräkna vid 24,00 V','accuracy',[47,48],'24,00 V ±0,14 V ger 23,86–24,14 V.',
 'Samma specifikation och upplösning, men nu visar skärmen tjugofyra volt. Pausa och räkna först. Procentdelen blir noll komma tolv volt. Två steg ger fortfarande noll komma noll två volt. Felgränsen blir plus minus noll komma fjorton volt. Intervallet går från tjugotre komma åttiosex till tjugofyra komma fjorton volt.',{example:24,pause:true}),
s('fel8',7,'Ett annat instrument ger andra bidrag','accuracy',[67],'8,00 V ±0,11 V ger 7,89–8,11 V.',
 'I fördjupningsexemplet visar instrumentet åtta volt. Specifikationen är plus minus en procent, plus tre siffror, och upplösningen en hundradels volt. Bidragen blir noll komma noll åtta och noll komma noll tre volt. Summan är noll komma elva volt. Använd alltid specifikationen för det aktuella området.',{example:8}),
s('tolerans',8,'Ryms hela mätintervallet inom kravet?','tolerance',[49,50,51,52],'Krav 11,40–12,60 V. Mätintervall 11,40–11,60 V.',
 'Utrustningen kräver tolv volt plus minus fem procent. Fem procent är noll komma sex volt. Tillåtet område blir elva komma fyrtio till tolv komma sextio volt. Mätningen är elva komma femtio plus minus noll komma tio volt. Hela intervallet ryms. Här räknas gränsvärdena som tillåtna. Verkliga acceptansregler måste vara bestämda i förväg.'),
s('protokoll',8,'Nästa vakt behöver mer än en siffra','protocol',[53,54],'Mätpunkter, drifttillstånd, instrument, resultat och slutsats.',
 'Anteckningen spänningen är elva komma åtta räcker inte. Skriv enhet, mätpunkter och drifttillstånd. Ange instrument, funktion, område, upplösning och relevant specifikation. Redovisa felgräns, krav och slutsats samt datum och utförare. Här visar vi fiktiva undervisningsdata. Verkliga uppgifter ska dokumenteras, aldrig gissas.'),
s('delare',9,'Två lika motstånd delar 10 V lika','divider',[55],'Utan mätare: U över R₂ = 5,000 V.',
 'Nu lämnar vi lampan och undersöker en givarmodell. Två motstånd på vardera en megaohm delar tio volt lika. Utan ansluten mätare blir spänningen över det nedre motståndet fem volt. Vad händer när en verklig voltmeter kopplas in?',{rm:0}),
s('last10',9,'Mätaren skapar en extra strömväg','divider',[56,57,58,59],'Rₘ = 10 MΩ: beräknat 4,762 V, visning 4,76 V.',
 'Voltmeterns ingång på tio megaohm hamnar parallellt med det nedre motståndet. Parallellvärdet blir ungefär noll komma nio noll nio megaohm. Med spänningsdelarens formel får vi ungefär fyra komma sjuhundrasextiotvå volt. Med hundradels upplösning visas fyra komma sjuttiosex. Mätaren har ändrat spänningen som vi ville undersöka.',{rm:10}),
s('last1',9,'Lägre ingångsresistans belastar mer här','divider',[60,61],'Rₘ = 1 MΩ: beräknat 3,333 V, visning 3,33 V.',
 'Byt bara mätarens ingångsresistans till en megaohm. En megaohm parallellt med en megaohm blir en halv megaohm. Tio gånger en halv, delat med ett plus en halv, ger ungefär tre komma tre tre tre volt. Pausa gärna och kontrollera beräkningen.',{rm:1,pause:true}),
s('lastprocent',9,'Belastningsfelet jämförs med ursprungsvärdet','loadingError',[62,63],'(3,333 − 5,000) / 5,000 · 100 % ≈ −33,3 %',
 'Jämför med fem volt utan mätare. Skillnaden dividerad med ursprungsvärdet ger ungefär minus trettiotre komma tre procent. Minustecknet betyder lägre spänning. Stora resistanser i givarkretsen gör påverkan tydlig. Högre ingångsresistans belastar mindre i just denna modell. Belastningsfel är något annat än instrumentets egen felgräns.'),
s('last9',9,'Samma princip vid 9 V','divider',[68],'R₁ = R₂ = Rₘ = 2 MΩ. 4,5 V blir 3,0 V.',
 'Fördjupning: källan är nio volt och alla tre resistanser är två megaohm. Utan mätare blir spänningen fyra komma fem volt. Den nedre parallellkopplingen blir en megaohm. Med mätaren ansluten får vi tre volt. Även här blir förändringen minus trettiotre komma tre procent.',{rm:2,source:9}),
s('burden',10,'Även amperemetern påverkar kretsen','burden',[66],'12 / 120 = 0,100 A. 12 / 121 ≈ 0,0992 A.',
 'Även strömmätaren förändrar kretsen. Med tolv volt och hundratjugo ohm blir strömmen noll komma ett ampere. Om mätaren tillför en ohm blir totalen hundratjugoen ohm och strömmen ungefär noll komma noll nio nio två ampere. Shunt och säkring orsakar spänningsfall. I manualer kallas detta ofta burden voltage.'),
s('repetition',11,'Förklara kopplingen innan du mäter','recap',[4,40,64],'V parallellt. A i serie. Ω och summer utan yttre matning.',
 'Varför mäts volt parallellt och ampere i serie? Varför måste resistans mätas i en frånskild krets? Förklara med ett schema. Skilj på upplösning, felgräns, tolerans och belastningsfel. Rätt kategori och spänning skyddar mätningen, men gör inte avläsningen mer noggrann.'),
s('egetarbete',11,'Din tur i Multimeterlabbet','outro',[2,64,65],'Förutsäg. Koppla. Läs av. Förklara. Dokumentera.',
 'Nu har Saga och Måsen ett arbetssätt i stället för en gissning. Öppna Multimeterlabbet, förutsäg värdet och välj funktion och uttag. Koppla, läs av och förklara. Rita sedan en korrekt mätkoppling och skriv ett kort protokoll. Följ kursens inlämningsanvisning och lärarens instruktioner vid praktisk laboration.'),
s('kallor',11,'Fortsätt med presentationen och manualen','credits',[69,70],'Sjöskolan · Multimeter och mätfel',
 'Filmen kompletterar presentationen Multimeter och mätfel. Källor och fler svenska filmer finns i presentationen och under filmspelaren. Instrumentet här är en förenklad undervisningsmodell. Vid praktiskt arbete gäller det verkliga instrumentets manual och arbetets säkerhetsrutiner. Tack för att du följde med ombord!')
];
