// Gemensamt undervisningsinnehåll för veckosida, genomgångar, stegfilmer och PowerPoint.
// Exempel är enfas och stationära. Komponenterna är ideala om inget annat anges.
export const REVISION = '20260925-ac2';
export const BASE = '/sjoskolan/vecka-40/aktuell/';
import {KONTROLLFRAGOR} from './kontrollfragor.gen.mjs';
const LEKTIONER = [
 {id:'sinus',number:1,title:'Sinus och mätvärden',deck:'v40_01_Sinusformad_vaxelspanning_elev.pptx',minutes:'90 min med läraren',goal:'Läsa periodtid och skilja på toppvärde, effektivvärde (RMS) och medelvärde.',
  deliver:'Instrumentkontroll, periodtid och toppvärde samt en förklaring till mätvärdena.',
  filmTitle:'Vad visar kurvan och multimetern?',film:['kurvan','period','topp','rms','matarna','protokoll'],
  slides:[
   {id:'mal',title:'Det här ska du kunna',body:['Hitta en hel period på kurvan och räkna periodtiden T ur frekvensen.','Skilja på toppvärde, effektivvärde (RMS) och medelvärde.','Förklara varför en multimeter och kurvans topp visar olika tal.'],note:'Måndag, 2 × 45 min. Pass 1: bild 3–7, film 1, övning 1–5 i par. Pass 2: kontrollfrågor, övning 6–10, eget försök, inlämning uppgift 1. Labben görs fredag.'},
   {id:'kurvan',title:'Spänning över tid',body:['Den vågräta axeln visar tid i millisekunder. Den lodräta visar spänning i volt.','Kurvan går över och under noll. Spänningens polaritet växlar.','En hel period går från en stigande nollpassage till nästa stigande nollpassage.'],visual:'wave',note:'Följ kurvan långsamt: noll, positiv topp, noll, negativ topp, noll. Kurvan visar spänningen vid olika tidpunkter, inte en partikels färd.'},
   {id:'period',title:'Periodtid och frekvens',body:['Frekvens f är antal perioder per sekund. Enheten är hertz, Hz.','Periodtiden T är tiden för en hel period. Ombord är frekvensen 60 Hz: T = 1/60 ≈ 0,0167 s = 16,7 ms (millisekunder, tusendels sekunder).','På kurvan är avståndet mellan motsvarande punkter 16,7 ms.'],formula:'T = 1/f     T i ms = 1 000/f',visual:'period',note:'Låt eleven peka på två stigande nollpassager innan formeln används. Vanligt fel: 0,0167 s skrivs som 0,0167 ms.'},
   {id:'topp',title:'Toppvärde och topp till topp',body:['Toppvärdet û (läses u-topp, u med hatt) mäts från noll till den positiva toppen.','Topp till topp, U_{pp} (pp: peak to peak), går från negativ topp till positiv topp.','Exempel, 440 V-nätet ombord: û ≈ 622 V och U_{pp} = 2 · û ≈ 1 245 V.'],formula:'U_{pp} = 2 · û',visual:'peak',note:'Peka ut nollnivån. Eleven ska inte använda hela höjden när frågan gäller toppvärde.'},
   {id:'rms',title:'Effektivvärdet beskriver värmeeffekten',body:['Effektivvärdet 230 V i vägguttaget värmer en vattenkokare lika mycket som 230 V likspänning (DC).','Effektivvärdet förkortas RMS (root mean square, engelska för kvadratiskt medelvärde). U utan index betyder alltid effektivvärdet. Multimetern i växelspänningsläget (AC eller V~) visar 230 V i vägguttaget och 440 V ombord.','Toppen är högre eftersom spänningen bara når toppen en kort stund.'],formula:'û = √2 · U = √2 · 440 ≈ 622 V',visual:'rms',note:'Förklara betydelsen innan förkortningen root mean square. Ett element på 23 Ω ger P = 230²/23 = 2 300 W med 230 V RMS och med 230 V DC.'},
   {id:'exempel',title:'Ett helt räkneexempel',body:['Givet: fartygets huvudnät, U = 440 V RMS och f = 60 Hz.','Period: T = 1 000/60 ≈ 16,7 ms.','Topp: û = 440 · √2 ≈ 622 V. Topp till topp: ≈ 1 245 V.','Räkna sedan själv med labbens källa. Skriv förväntat värde före avläsningen.'],note:'Exemplet har samma metod men andra värden än labbens källa, så att eleven själv räknar fram labbens svar.'},
   {id:'matarna',title:'Instrumentkontroll före mätningen',body:['I simulatorn väljer grunduppgiften en kalibrator på 10,00 V sinus.','Förutsäg visningen. Läs sedan av både true RMS-mätaren (räknar ut det verkliga effektivvärdet för alla kurvformer) och den sinuskalibrerade mätaren (visar rätt bara för ren sinus).','För en ren sinus visar båda mätartyperna kalibratorns effektivvärde. Skillnaden syns först vid andra kurvformer. Kontrollen dokumenteras för båda instrumenten.'],visual:'calibration',note:'Detta är en modell av instrumentkontroll, inte en utförd fysisk kalibrering. En verklig kontroll följer instrumentens och stationens instruktioner.'},
   {id:'protokoll',title:'En protokollrad',body:['Exempel från fartyget, 60 Hz. Förutsäg: T = 1 000/60 ≈ 16,7 ms.','Läs av och registrera 16,7 ms.','Jämför: avläst − förväntat = 0,0 ms.','Förklara: en hel period tar 16,7 ms. Frekvensen är 60 perioder per sekund. I labben gör du samma sak vid 50 Hz med din egen spänning, som räknas fram ur ditt namn.'],note:'Öppna guidad labb och visa en rad. Eleven ska kunna säga vad som jämförs och vilken enhet som används.'},
   {id:'medel',title:'Medelvärde och RMS är olika',body:['Den symmetriska sinusens positiva och negativa delar tar ut varandra. Vanligt medelvärde över en hel period är 0 V.','Resistorn blir ändå varm. Båda halvperioderna bidrar till u²/R.','För 440 V-nätet ombord: vanligt medelvärde 0 V, RMS 440 V och topp 622 V.'],visual:'wave',note:'Stanna här om eleven fortfarande blandar medelvärde och effektivvärde.'},
   {id:'eget',title:'Eget försök med andra värden',body:['En sinus har U = 48,00 V RMS och f = 120 Hz.','Beräkna T och û. Ange både tal och enhet.','Förklara vilken avläsning en true RMS-multimeter visar.'],note:'Detta kontrollerar överföring till nya värden. Godkänn inte endast att grundexemplet har kopierats.'},
   {id:'moment',title:'Fördjupning: momentanvärde',advanced:true,body:['Momentanvärdet u(t) är spänningen vid en bestämd tidpunkt t. Liten bokstav u betyder ett värde som ändras med tiden.','Exempel, fartygets 440 V-nät: U = 440 V RMS, f = 60 Hz, t = 2,0 ms = 0,002 s.','û = 440√2 ≈ 622 V. Vinkeln 2πft ≈ 0,754 rad (radianer; 2π radianer är ett helt varv, 360°).','u = 622 · sin(0,754) ≈ 426 V. Räknaren ska stå i RAD (radianer), inte DEG (grader).'],formula:'u(t) = û · sin(2πft)',note:'Sinusformeln använder toppvärdet som amplitud. Momentanvärdet får ett negativt tecken under den negativa halvperioden.'},
   {id:'fas',title:'Fördjupning: tid och fas',advanced:true,body:['En hel period motsvarar 360°. Fasvinkeln φ (fi) anger hur långt två kurvor är förskjutna, och Δt (delta t) är tidsskillnaden mellan dem.','Ombord, vid 60 Hz, är T ≈ 16,7 ms. Ett tidsavstånd på 2,5 ms ger 360 · 2,5/16,67 ≈ 54°.','Kurvan som når motsvarande punkt först leder. Den andra släpar.'],formula:'|φ| = 360° · Δt/T',note:'Beloppet räcker inte för att avgöra vem som leder. Eleven måste läsa kurvornas ordning.'},
   {id:'likriktat',title:'Fördjupning: likriktat medelvärde',advanced:true,body:['Vid likriktning speglas den negativa halvperioden uppåt. |u| betyder spänningen utan tecken (beloppet), så medelvärdet av |u| blir positivt.','För sinus: medel(|u|) = 2û/π. Vid 12,00 V RMS blir det cirka 10,80 V.','En medelvärdesmätande, sinuskalibrerad mätare multiplicerar detta med cirka 1,11072 och visar 12,00 V.'],formula:'Visning = π/(2√2) · medel(|u|)',note:'Källa: Fluke, True measurements of non-linear loads require a true-RMS measurement tool. Vanligt medelvärde, likriktat medelvärde och RMS måste hållas isär.'},
   {id:'kurvformer',title:'Fördjupning: samma RMS, olika visning',advanced:true,body:['Alla tre signalerna har effektivvärdet 10,00 V och ingen likspänningsdel (DC-innehåll).','Sinus: topp 14,14 V. Den sinuskalibrerade mätaren visar 10,00 V.','Fyrkant: topp 10,00 V. Medel(|u|) = 10,00 V. Visning ≈ 11,11 V.','Triangel: topp = √3 · 10 ≈ 17,32 V. Medel(|u|) = û/2. Visning ≈ 9,62 V.'],visual:'meters',note:'Här hålls RMS konstant. Vid jämförelse med samma toppvärde blir RMS i stället olika. True RMS visar 10,00 V för alla tre i idealmodellen. Verkliga instrument har frekvens-, bandbredds- och crestfaktorgränser.'},
   {id:'station',title:'Fördjupning: Station B',advanced:true,body:['Stationsmodellen är märkt 12 V ±0,5 V och ger 12,35 V RMS vid 50 Hz.','Använd avlästa 12,35 V när du förutsäger toppen: cirka 17,47 V.','Fyrkant ger cirka 13,72 V på den sinuskalibrerade mätaren, trots att RMS är 12,35 V.','Att visningen stämmer med mätarmodellen betyder inte att den visar korrekt RMS.'],note:'Skilj källans avvikelse från instrumentets visningsprincip. Stationsprotokollet har egna kontroller och används efter mätaravsnittet.'},
   {id:'klart',title:'Inför nästa del',body:['Genomför grunduppgifterna och spara protokollet.','Förklara med egna ord skillnaden mellan effektivvärde (RMS), toppvärde och vanligt medelvärde.','Fysisk anslutning, oscilloskopets inställningar och godkända mätpunkter övas på den verkliga stationen.'],note:'Säkerheten i verklig mätning kan inte godkännas genom ett klick i simulatorn. Läraren behöver riggens dokumenterade mätpunkter och instrumentmanualer.'}
  ]},
 {id:'impedans',number:2,title:'Spole, motstånd och ström',deck:'v40_02_Reaktans_och_impedans_elev.pptx',minutes:'90 min med läraren',goal:'Beräkna reaktans och ström i en krets med resistor och spole (RL-krets) och tolka vilken signal som släpar.',deliver:'Reaktans, impedans och ström samt en förklaring av spolens inverkan.',filmTitle:'Vad händer när vi lägger till en spole?',film:['resistor','spole','xl','z','strom','labb'],
  slides:[
   {id:'mal',title:'Det här ska du kunna',body:['Räkna strömmen genom en resistor med Ohms lag.','Omvandla mH (millihenry) till H (henry, enheten för induktans) och räkna spolens reaktans X_{L}.','Räkna impedansen |Z| och strömmen när en spole sitter i serie med en resistor.'],note:'Tisdag, 2 × 45 min. Pass 1: bild 3–8, film 2, övning 1–4. Pass 2: övning 5–10, eget försök, inlämning uppgift 2. Snabba elever: bild 12–15. Labben görs fredag.'},
   {id:'resistor',title:'En resistor',body:['Ett värmeelement på 50 Ω ligger på 230 V RMS.','I = U/R = 230/50 = 4,6 A RMS.','Spänning och ström har toppar och nollpassager samtidigt. De är i fas.'],visual:'resistor',note:'Kurvorna har egna amplitudskalor. Jämför tiden, inte höjden i volt och ampere.'},
   {id:'spole',title:'En spole i serie',body:['En ideal spole lagrar energi i ett magnetfält och motverkar ändringar i strömmen.','Resistor (R) och spole (L) i serie kallas RL-krets. I RL-kretsen kommer strömmens topp efter källspänningens topp. Strömmen släpar.','Spolen tillför reaktans, ett motstånd mot växelström som mäts i ohm. Den påverkar strömmen utöver resistorn.'],visual:'rl',note:'En ideal spole ensam har 90° fasförskjutning. En RL-krets har en vinkel mellan 0° och 90°.'},
   {id:'xl',title:'Reaktans och enheter',body:['Spolens reaktans skrivs X_{L} (X för reaktans, L för spole). L är spolens induktans i henry. Exempel: en fläktmotors lindning har L = 382 mH = 0,382 H och f = 50 Hz.','X_{L} = 2π · 50 · 0,382 ≈ 120 Ω. Ombord, vid 60 Hz, blir X_{L} ≈ 144 Ω.','Vid dubbla frekvensen blir X_{L} dubbelt så stor om L är oförändrad.'],formula:'X_{L} = 2πfL',note:'Låt eleven skriva enhetsomvandlingen som en egen rad. X_{L} är reaktans, inte spoltrådens resistans.'},
   {id:'z',title:'Impedansen i RL-kretsen',body:['Impedansen Z är kretsens totala motstånd mot växelström. Fläktmotorns lindning: R = 50 Ω och X_{L} ≈ 120 Ω är vinkelräta delar i impedansdiagrammet.','|Z| = √(50² + 120²) = √16 900 = 130 Ω.','Beloppen 50 och 120 ska inte adderas direkt. Diagonalen ger impedansens belopp |Z|; strecken betyder belopp (storlek).'],formula:'|Z| = √(R² + X_{L}²)',visual:'triangle',note:'Visa först de vinkelräta sidorna och sedan diagonalen. Komplexa tal behövs inte för denna beräkning.'},
   {id:'strom',title:'Strömmen med spolen inkopplad',body:['Fläktmotorn ligger på 230 V RMS.','I = U/|Z| ≈ 230/130 ≈ 1,77 A RMS.','Med bara resistansen 50 Ω skulle strömmen vara 4,6 A. Med R och L blir den mindre och släpar efter spänningen.'],formula:'I = U/|Z|',visual:'rl',note:'Med X_{L} = 2π · 50 · 0,382 = 120,0 Ω blir I ≈ 1,769 A. Två decimaler är 1,77 A. Labbens krets räknas på samma sätt med andra värden.'},
   {id:'exempel',title:'Ett genomräknat exempel',body:['En annan RL-krets har R = 12 Ω, X_{L} = 16 Ω och U = 60 V RMS.','|Z| = √(12² + 16²) = 20 Ω.','I = 60/20 = 3 A.','Spänningen över resistorn: U_{R} = I · R = 3 · 12 = 36 V. Spänningen över spolen: U_{L} = I · X_{L} = 3 · 16 = 48 V. De adderas vinkelrätt: √(36² + 48²) = 60 V, källans spänning.'],note:'Spänningarnas belopp summeras inte direkt eftersom de är fasförskjutna.'},
   {id:'labb',title:'Arbetsgång i den guidade labben',body:['Du får egna värden på R och L ur ditt namn. Förutsäg X_{L}, läs av och kontrollera enheten Ω.','Använd R och X_{L} för att beräkna |Z|.','Beräkna strömmen och jämför med kretsen som bara innehåller R.','Skriv varför strömmen ändras och vilken kurva som kommer först.'],note:'Uppgifterna ställer in samma krets automatiskt. Eleven gör beräkningen före avläsningen.'},
   {id:'fas',title:'Fasvinkel med tecken',body:['Fasvinkeln φ (fi) mellan spänning och ström: φ = arctan(X/R). Räknaren ska stå i DEG (grader).','För RL: X = +X_{L}. Fläktmotorn med R = 50 Ω och X_{L} = 120 Ω får φ ≈ +67,38°.','Positiv impedansvinkel innebär att källspänningen leder strömmen. Strömmen släpar.'],formula:'φ = arctan(X/R)',visual:'rl',note:'Skilj vinkelns tecken från den vardagliga formuleringen strömmen släpar.'},
   {id:'eget',title:'Eget försök med andra värden',body:['R = 90 Ω, X_{L} = 120 Ω och U = 230 V RMS.','Beräkna |Z| och I. Ange om strömmen leder eller släpar.'],note:'Be eleven rita de vinkelräta delarna om svaret bygger på 90 + 120.'},
   {id:'xc',title:'Fördjupning: kondensatorn',advanced:true,body:['En ideal kondensator lagrar energi i ett elektriskt fält. Strömmen leder dess spänning med 90°.','Kondensatorns reaktans skrivs X_{C}. C är kapacitansen i farad (F). C = 47 µF (mikrofarad) = 0,000047 F vid 50 Hz.','X_{C} = 1/(2π · 50 · 0,000047) ≈ 67,7 Ω.','När frekvensen fördubblas halveras X_{C}.'],formula:'X_{C} = 1/(2πfC)',note:'X_{C} anges här som ett positivt belopp. Den kapacitiva nettoreaktansen har negativt tecken.'},
   {id:'rc',title:'Fördjupning: RC-krets',advanced:true,body:['Resistor och kondensator i serie kallas RC-krets. R = 60 Ω och X_{C} = 80 Ω. Nettoreaktansen är X = −80 Ω.','|Z| = √(60² + (−80)²) = 100 Ω.','φ = arctan(−80/60) ≈ −53,13°. Strömmen leder källspänningen.','Vid U = 230 V RMS blir I = 230/100 = 2,30 A.'],note:'Minus ingår i fasvinkeln. Kvadreringen gör impedansens belopp positivt.'},
   {id:'rlc',title:'Fördjupning: RLC och komplex form',advanced:true,body:['Resistor, spole och kondensator i serie kallas RLC-krets. I serie: X = X_{L} − X_{C}. Därefter |Z| = √(R² + X²).','Den komplexa skrivformen är Z = R + jX. Bokstaven j markerar att den reaktiva delen X ligger vinkelrätt mot R.','Exempel: R = 45 Ω, X_{L} = 80 Ω, X_{C} = 20 Ω. X = 60 Ω och |Z| = 75 Ω.'],note:'Komplex form introduceras efter att eleven förstått den geometriska betydelsen.'},
   {id:'resonans',title:'Fördjupning: resonansfrekvens',advanced:true,body:['Vid serieresonans är X_{L} = X_{C}. Nettoreaktansen blir noll och |Z| = R. Frekvensen där det händer kallas resonansfrekvens, f_{0}.','L = 100 mH = 0,100 H. C = 47 µF = 0,000047 F.','√(L · C) = √0,0000047 ≈ 0,0021679.','f_{0} = 1/(2π · 0,0021679) ≈ 73,4 Hz.'],formula:'f_{0} = 1/(2π√(L · C))',note:'Härledd ur 2πfL = 1/(2πfC). Vid R = 25 Ω och U = 100 V blir I = 4 A och φ = 0°. Verkliga komponenter har förluster och begränsningar.'},
   {id:'klart',title:'Kontroll före nästa del',body:['Kan du gå från mH till H och från X_{L} till ström?','Kan du förklara varför R och X_{L} ligger vinkelrätt?','Kan du visa att strömmen släpar i RL-kretsen?','Spara dina guidade mätningar och din förklaring.'],note:'Återgå till resistor- och spolkurvorna om ledande/släpande fortfarande är oklart.'}
  ]},
 {id:'effekt',number:3,title:'Effekt och effektfaktor',deck:'v40_03_Effekt_i_vaxelstromskretsar_elev.pptx',minutes:'90 min med läraren',goal:'Skilja på aktiv effekt P, reaktiv effekt Q och skenbar effekt S och förklara hur effektfaktorn påverkar matningsströmmen.',deliver:'Ström vid två effektfaktorer och en förklaring av vad som ändras.',filmTitle:'Samma aktiva effekt, olika ström',film:['resistiv','pf','strom','s','q','labb'],
  slides:[
   {id:'mal',title:'Det här ska du kunna',body:['Skilja på aktiv effekt P, reaktiv effekt Q och skenbar effekt S.','Räkna strömmen när U, P och effektfaktorn PF är givna.','Förklara varför lägre effektfaktor ger större ström vid samma P och U.'],note:'Fredag, 2 × 45 min. Pass 1: bild 3–8, film 3, övning 1–6. Pass 2: guidad labb, alla åtta uppgifter, protokoll som PDF, genomgång av inlämningen. Modellen är sinusformad enfas, inte trefas.'},
   {id:'resistiv',title:'Resistiv last och aktiv effekt',body:['Aktiv effekt P är den medeleffekt som omvandlas till arbete och värme. Enheten är watt, W.','Exempel: ett värmeelement på 1 380 W vid 230 V har effektfaktorn 1,00: I = P/U = 1 380/230 = 6,00 A.','Spänning och ström är i fas i den rent resistiva modellen.'],visual:'power',note:'Börja med ett bekant resistivt exempel innan reaktiv effekt introduceras.'},
   {id:'pf',title:'Effektfaktorn',body:['Effektfaktorn förkortas PF (power factor). PF = P/S, där S är den skenbara effekten (se nedan). PF saknar enhet och ligger mellan 0 och 1.','För rena sinussignaler är PF = cos φ, cosinus för fasvinkeln φ mellan spänning och ström. Lägre PF innebär större ström för samma U och P.','Vi jämför 1,00 och 0,50 utan att ändra lastens aktiva effekt.'],formula:'P = U · I · PF',visual:'power',note:'PF är inte motorns verkningsgrad. Undvik att säga att hälften av energin förbrukas i onödan vid PF = 0,5.'},
   {id:'strom',title:'Strömmen vid lägre effektfaktor',body:['Lös ut I genom att dividera båda sidor med U · PF.','Exempel: en pumpmotor på 1 380 W vid 230 V.','Vid PF = 1,00: I = 1 380/(230 · 1) = 6,00 A.','Vid PF = 0,50: I = 1 380/(230 · 0,50) = 12,00 A. Strömmen fördubblas, men den aktiva effekten är fortfarande 1 380 W.'],formula:'I = P/(U · PF)',visual:'power',note:'Skriv hela nämnaren inom parentes i räknaren.'},
   {id:'s',title:'Skenbar effekt',body:['Skenbar effekt S = U · I. Enheten är voltampere, VA.','Ur PF = P/S får vi PF · S = P och sedan S = P/PF.','Pumpmotorn vid PF = 0,50: S = 1 380/0,50 = 2 760 VA.','Kontroll: 230 V · 12 A = 2 760 VA.'],formula:'S = P/PF = U · I',note:'Skilj VA från W även när talen råkar vara lika vid PF = 1.'},
   {id:'q',title:'Reaktiv effekt',body:['Reaktiv effekt Q beskriver energi som går fram och tillbaka mellan källan och spolar eller kondensatorer. Den förbrukas inte, men ger ändå ström i ledningarna.','För sinus: S² = P² + Q². Därför |Q| = √(S² − P²).','Exempel: S = 2 760 VA och P = 1 380 W ger |Q| ≈ 2 390,23 var. Enheten var betyder voltampere reaktiv.','I kursens teckenkonvention är induktiv Q positiv och kapacitiv Q negativ.'],formula:'|Q| = √(S² − P²)',visual:'powerTriangle',note:'Q är inte i sig en förbrukad energi. Den större strömmen kan däremot öka resistiva förluster.'},
   {id:'exempel',title:'Ett genomräknat exempel',body:['P = 1 200 W, PF = 0,75 och U = 230 V RMS. Lasten är induktiv och sinusformad.','S = 1 200/0,75 = 1 600 VA.','Q = √(1 600² − 1 200²) ≈ 1 058,30 var.','I = S/U = 1 600/230 ≈ 6,96 A.'],note:'Detta stänger luckan mellan given effektfaktor och reaktiv effekt i räkna-först-uppgifterna.'},
   {id:'labb',title:'Arbetsgång i den guidade labben',body:['Du får en egen effekt P ur ditt namn. Förutsäg strömmen vid PF = 1,00, läs av och registrera värdet.','Förutsäg strömmen vid PF = 0,50. U och P hålls oförändrade.','Jämför de båda värdena och förklara orsaken.','Redovisa vilka storheter som ändrades och vilka som var konstanta.'],note:'Ingen kompensering eller kabelresistans behöver justeras för dessa två grunduppgifter.'},
   {id:'energi',title:'Effekt och energi',body:['Energi beror både på aktiv effekt och på tid.','E = P · t. Med kW (kilowatt) och timmar blir enheten kWh (kilowattimme).','1,60 kW under 3 h ger 4,80 kWh aktiv energi.','Använd P för aktiv energi, även om S är större.'],formula:'E = P · t',note:'Skilj anläggningens effektbehov från ackumulerad energianvändning.'},
   {id:'eget',title:'Eget försök med andra värden',body:['En enfaslast tar P = 4 140 W vid U = 230 V och PF = 0,60.','Beräkna I och S. Förklara om P skulle ändras bara för att PF förbättras i vår modell.'],note:'Be eleven ange vad som hålls konstant innan formeln används.'},
   {id:'kompensering',title:'Fördjupning: kompensation',advanced:true,body:['Att kompensera betyder att en kondensator tillför kapacitiv reaktiv effekt som tar ut en del av lastens induktiva Q.','Exempel: pumpmotorn P = 1 380 W och PF = 0,80. S = 1 380/0,80 = 1 725 VA.','Q = √(1 725² − 1 380²) = +1 035 var.','För full kompensation behövs Q_{kondensator} = −1 035 var. Behovets belopp är 1 035 var.'],formula:'Q_{total} = Q_{last} + Q_{kondensator}',note:'Skilj kompensationsbehovets positiva belopp från kondensatorns negativa bidrag. Detta är en undervisningsmodell, ingen dimensioneringsanvisning.'},
   {id:'forlust',title:'Fördjupning: ledningsförlust',advanced:true,body:['Samma kabel har samma resistans R. Förlusten är I²R.','När strömmen minskar från 12 A till 6 A återstår (6/12)² = 0,25 av ledningsförlusten.','Ledningsförlusten minskar med 75 %. Lastens aktiva effekt behöver inte minska.'],formula:'P_{förlust} = I²R',note:'Procentsatsen gäller kabelns förlust. Den är inte en besparing på 75 % av hela lastens energibehov.'},
   {id:'overtoner',title:'Fördjupning: PF och cos φ',advanced:true,body:['PF = P/S gäller även när strömmen är förvrängd av övertoner (strömmar med 2, 3, 5 … gånger nätfrekvensen, till exempel från elektronik).','PF = cos φ förutsätter sinusformad spänning och ström.','Exempel: P = 800 W och S = 1 000 VA ger PF = 0,80, även om grundtonens cos φ är 0,95.','Den enkla effekttriangeln beskriver inte alla effekter vid övertoner.'],note:'Behåll detta som en uttrycklig begränsning av modellen. Verklig kompensation kräver bedömning av bland annat övertoner och resonans.'},
   {id:'klart',title:'Kontroll före redovisning',body:['Kan du förklara skillnaden mellan W (watt, aktiv effekt), var (voltampere reaktiv, reaktiv effekt) och VA (voltampere, skenbar effekt)?','Kan du räkna I när U, P och PF är givna?','Kan du förklara vad som ändras när PF sjunker vid samma P och U?','Spara ditt grundprotokoll. Läraren bedömer metoden och förklaringen.'],note:'Ifyllda rutor eller rätt antal ord visar inte ensamma att eleven förstår.'}
  ]}
];
export const lessonById=id=>LESSONS.find(l=>l.id===id)||LESSONS[0];

// Prova själv-frågorna kommer ur innehållsdatabasen (kontrollfragor.gen.mjs).
export const LESSONS = LEKTIONER.map((l) => ({ ...l, slides: l.slides.map((s) => { const k = KONTROLLFRAGOR.find((q) => q.del === l.id && q.bild === s.id); return k ? { ...s, check: k.check, answer: k.answer } : s; }) }));
