// Gemensamt undervisningsinnehåll för veckosida, genomgångar, stegfilmer och PowerPoint.
// Exempel är enfas och stationära. Komponenterna är ideala om inget annat anges.
export const REVISION = '20260925-ac2';
export const BASE = '/sjoskolan/vecka-40/aktuell/';
import {KONTROLLFRAGOR} from './kontrollfragor.gen.mjs';
const LEKTIONER = [
 {id:'sinus',number:1,title:'Sinus och mätvärden',deck:'v40_01_Sinusformad_vaxelspanning_elev.pptx',minutes:'90 min med läraren',goal:'Läsa periodtid och skilja på toppvärde, effektivvärde (RMS) och medelvärde.',
  deliver:'Instrumentkontroll, periodtid och toppvärde samt en förklaring till mätvärdena.',
  filmTitle:'Vad visar kurvan och multimetern?',film:['kurvan','period','topp','rms','matarna','protokoll'],
  slides:[
   {id:'mal',title:'Det här behövs i labben',body:['Du ska kunna hitta en hel period och kurvans högsta värde.','Du ska kunna förklara varför en multimeter och kurvans topp visar olika tal.','Basdelen använder en sinusspänning med effektivvärdet 12,00 V (skrivs 12,00 V RMS) och frekvensen 50 hertz (Hz). Station B är ett senare, utökat försök.'],note:'Förslag: 30 min genomgång inklusive stegfilm, 15 min gemensam räkning, 30 min guidad labb, 15 min återkoppling. Delarna kan delas på två 45-minuterspass.'},
   {id:'kurvan',title:'Spänning över tid',body:['Den vågräta axeln visar tid i millisekunder. Den lodräta visar spänning i volt.','Kurvan går över och under noll. Spänningens polaritet växlar.','En hel period går från en stigande nollpassage till nästa stigande nollpassage.'],visual:'wave',note:'Följ kurvan långsamt: noll, positiv topp, noll, negativ topp, noll. Kurvan visar spänningen vid olika tidpunkter, inte en partikels färd.'},
   {id:'period',title:'Periodtid och frekvens',body:['Frekvens f är antal perioder per sekund. Enheten är hertz, Hz.','Periodtiden T är tiden för en hel period. Vid 50 Hz: T = 1/50 = 0,020 s = 20,00 ms (millisekunder, tusendels sekunder).','På kurvan är avståndet mellan motsvarande punkter 20 ms.'],formula:'T = 1/f     T i ms = 1 000/f',visual:'period',note:'Låt eleven peka på två stigande nollpassager innan formeln används. Vanligt fel: 0,020 s skrivs som 0,020 ms.'},
   {id:'topp',title:'Toppvärde och topp till topp',body:['Toppvärdet û (läses u-topp, u med hatt) mäts från noll till den positiva toppen.','Topp till topp, U_{pp} (pp: peak to peak), går från negativ topp till positiv topp.','För vår sinus: û ≈ 16,97 V och U_{pp} ≈ 33,94 V.'],formula:'U_{pp} = 2 · û',visual:'peak',note:'Peka ut nollnivån. Eleven ska inte använda hela höjden när frågan gäller toppvärde.'},
   {id:'rms',title:'Effektivvärdet beskriver värmeeffekten',body:['Effektivvärdet 12,00 V över en resistor ger samma medeleffekt (värme) som 12,00 V likspänning (DC) över samma resistor.','Effektivvärdet förkortas RMS (root mean square, engelska för kvadratiskt medelvärde). U utan index betyder alltid effektivvärdet. Multimetern i växelspänningsläget (AC eller V~) visar här 12,00 V.','Sinusens topp är högre eftersom spänningen bara når toppen under en kort del av perioden.'],formula:'û = √2 · U = √2 · 12,00 ≈ 16,97 V',visual:'rms',note:'Förklara betydelsen innan förkortningen root mean square. Samma resistor 24 Ω ger P = 12²/24 = 6 W i båda fallen.'},
   {id:'exempel',title:'Ett helt räkneexempel',body:['Givet: sinus, U = 10,00 V RMS och f = 50 Hz.','Period: T = 1 000/50 = 20,00 ms.','Topp: û = 10,00 · √2 ≈ 14,14 V. Topp till topp: 28,28 V.','Pröva sedan själv med 12,00 V RMS. Skriv förväntat värde före avläsningen.'],note:'Exemplet har samma metod men ett annat spänningsvärde än elevens grundkälla.'},
   {id:'matarna',title:'Instrumentkontroll före mätningen',body:['I simulatorn väljer grunduppgiften en kalibrator på 10,00 V sinus.','Förutsäg visningen. Läs sedan av både true RMS-mätaren (räknar ut det verkliga effektivvärdet för alla kurvformer) och den sinuskalibrerade mätaren (visar rätt bara för ren sinus).','Båda visar 10,00 V för denna ideala sinus. Kontrollen dokumenteras för båda instrumenten.'],visual:'calibration',note:'Detta är en modell av instrumentkontroll, inte en utförd fysisk kalibrering. En verklig kontroll följer instrumentens och stationens instruktioner.'},
   {id:'protokoll',title:'En protokollrad',body:['Förutsäg periodtiden vid 50 Hz: 20,00 ms.','Läs av simulatorn och registrera 20,00 ms.','Jämför: avläst − förväntat = 0,00 ms.','Förklara: en hel period tar 20 ms. Frekvensen är 50 perioder per sekund.'],note:'Öppna guidad labb och visa en rad. Eleven ska kunna säga vad som jämförs och vilken enhet som används.'},
   {id:'medel',title:'Medelvärde och RMS är olika',body:['Den symmetriska sinusens positiva och negativa delar tar ut varandra. Vanligt medelvärde över en hel period är 0 V.','Resistorn blir ändå varm. Båda halvperioderna bidrar till u²/R.','För vår källa: vanligt medelvärde 0 V, RMS 12,00 V och topp 16,97 V.'],visual:'wave',note:'Stanna här om eleven fortfarande blandar medelvärde och effektivvärde.'},
   {id:'eget',title:'Eget försök med andra värden',body:['En sinus har U = 24,00 V RMS och f = 100 Hz.','Beräkna T och û. Ange både tal och enhet.','Förklara vilken avläsning en true RMS-multimeter visar.'],note:'Detta kontrollerar överföring till nya värden. Godkänn inte endast att grundexemplet har kopierats.'},
   {id:'moment',title:'Fördjupning: momentanvärde',advanced:true,body:['Momentanvärdet u(t) är spänningen vid en bestämd tidpunkt t. Liten bokstav u betyder ett värde som ändras med tiden.','Exempel: U = 10 V RMS, f = 50 Hz, t = 3 ms = 0,003 s.','û = 10√2 ≈ 14,14 V. Vinkeln 2πft ≈ 0,9425 rad (radianer; 2π radianer är ett helt varv, 360°).','u = 14,14 · sin(0,9425) ≈ 11,44 V. Räknaren ska stå i RAD (radianer), inte DEG (grader).'],formula:'u(t) = û · sin(2πft)',note:'Sinusformeln använder toppvärdet som amplitud. Momentanvärdet får ett negativt tecken under den negativa halvperioden.'},
   {id:'fas',title:'Fördjupning: tid och fas',advanced:true,body:['En hel period motsvarar 360°. Fasvinkeln φ (fi) anger hur långt två kurvor är förskjutna, och Δt (delta t) är tidsskillnaden mellan dem.','Vid 50 Hz är T = 20 ms. Ett tidsavstånd på 2,5 ms ger 360 · 2,5/20 = 45°.','Kurvan som når motsvarande punkt först leder. Den andra släpar.'],formula:'|φ| = 360° · Δt/T',note:'Beloppet räcker inte för att avgöra vem som leder. Eleven måste läsa kurvornas ordning.'},
   {id:'likriktat',title:'Fördjupning: likriktat medelvärde',advanced:true,body:['Vid likriktning speglas den negativa halvperioden uppåt. |u| betyder spänningen utan tecken (beloppet), så medelvärdet av |u| blir positivt.','För sinus: medel(|u|) = 2û/π. Vid 12,00 V RMS blir det cirka 10,80 V.','En medelvärdesmätande, sinuskalibrerad mätare multiplicerar detta med cirka 1,11072 och visar 12,00 V.'],formula:'Visning = π/(2√2) · medel(|u|)',note:'Källa: Fluke, True measurements of non-linear loads require a true-RMS measurement tool. Vanligt medelvärde, likriktat medelvärde och RMS måste hållas isär.'},
   {id:'kurvformer',title:'Fördjupning: samma RMS, olika visning',advanced:true,body:['Alla tre signalerna har effektivvärdet 12,00 V och ingen likspänningsdel (DC-innehåll).','Sinus: topp 16,97 V. Den sinuskalibrerade mätaren visar 12,00 V.','Fyrkant: topp 12,00 V. Medel(|u|) = 12,00 V. Visning ≈ 13,33 V.','Triangel: topp = √3 · 12 ≈ 20,78 V. Medel(|u|) = û/2. Visning ≈ 11,54 V.'],visual:'meters',note:'Här hålls RMS konstant. Vid jämförelse med samma toppvärde blir RMS i stället olika. True RMS visar 12,00 V för alla tre i idealmodellen. Verkliga instrument har frekvens-, bandbredds- och crestfaktorgränser.'},
   {id:'station',title:'Fördjupning: Station B',advanced:true,body:['Stationsmodellen är märkt 12 V ±0,5 V och ger 12,35 V RMS vid 50 Hz.','Använd avlästa 12,35 V när du förutsäger toppen: cirka 17,47 V.','Fyrkant ger cirka 13,72 V på den sinuskalibrerade mätaren, trots att RMS är 12,35 V.','Att visningen stämmer med mätarmodellen betyder inte att den visar korrekt RMS.'],note:'Skilj källans avvikelse från instrumentets visningsprincip. Stationsprotokollet har egna kontroller och används efter mätaravsnittet.'},
   {id:'klart',title:'Inför nästa del',body:['Genomför grunduppgifterna och spara protokollet.','Förklara med egna ord skillnaden mellan effektivvärde (RMS), toppvärde och vanligt medelvärde.','Fysisk anslutning, oscilloskopets inställningar och godkända mätpunkter övas på den verkliga stationen.'],note:'Säkerheten i verklig mätning kan inte godkännas genom ett klick i simulatorn. Läraren behöver riggens dokumenterade mätpunkter och instrumentmanualer.'}
  ]},
 {id:'impedans',number:2,title:'Spole, motstånd och ström',deck:'v40_02_Reaktans_och_impedans_elev.pptx',minutes:'90 min med läraren',goal:'Beräkna reaktans och ström i en krets med resistor och spole (RL-krets) och tolka vilken signal som släpar.',deliver:'Reaktans, impedans och ström samt en förklaring av spolens inverkan.',filmTitle:'Vad händer när vi lägger till en spole?',film:['resistor','spole','xl','z','strom','labb'],
  slides:[
   {id:'mal',title:'Det här behövs i labben',body:['Börja med en resistor och Ohms lag. Lägg sedan till en spole.','Du ska kunna omvandla mH (millihenry) till H (henry, enheten för induktans), beräkna reaktans och därefter ström.','Basexemplet använder U = 12,00 V RMS, f = 50 Hz och R = 40 Ω.'],note:'Förslag: 30 min genomgång och film, 15 min gemensamt exempel, 30 min guidad labb, 15 min återkoppling. Fördjupning fördelas efter elevgruppens behov.'},
   {id:'resistor',title:'En resistor',body:['En resistor på 40 Ω ligger över 12,00 V RMS.','I = U/R = 12/40 = 0,30 A RMS.','Spänning och ström har toppar och nollpassager samtidigt. De är i fas.'],visual:'resistor',note:'Kurvorna har egna amplitudskalor. Jämför tiden, inte höjden i volt och ampere.'},
   {id:'spole',title:'En spole i serie',body:['En ideal spole lagrar energi i ett magnetfält och motverkar ändringar i strömmen.','Resistor (R) och spole (L) i serie kallas RL-krets. I RL-kretsen kommer strömmens topp efter källspänningens topp. Strömmen släpar.','Spolen tillför reaktans, ett motstånd mot växelström som mäts i ohm. Den påverkar strömmen utöver resistorn.'],visual:'rl',note:'En ideal spole ensam har 90° fasförskjutning. En RL-krets har en vinkel mellan 0° och 90°.'},
   {id:'xl',title:'Reaktans och enheter',body:['Spolens reaktans skrivs X_{L} (X för reaktans, L för spole). L är spolens induktans i henry. Givet: L = 95,5 mH = 0,0955 H och f = 50 Hz.','X_{L} = 2π · 50 · 0,0955 ≈ 30,00 Ω.','Vid dubbla frekvensen blir X_{L} dubbelt så stor om L är oförändrad.'],formula:'X_{L} = 2πfL',note:'Låt eleven skriva enhetsomvandlingen som en egen rad. XL är reaktans, inte spoltrådens resistans.'},
   {id:'z',title:'Impedansen i RL-kretsen',body:['Impedansen Z är kretsens totala motstånd mot växelström. R = 40 Ω och X_{L} ≈ 30 Ω är vinkelräta delar i impedansdiagrammet.','|Z| = √(40² + 30²) = √2 500 = 50 Ω.','Beloppen 40 och 30 ska inte adderas direkt. Diagonalen ger impedansens belopp |Z|; strecken betyder belopp (storlek).'],formula:'|Z| = √(R² + X_{L}²)',visual:'triangle',note:'Visa först de vinkelräta sidorna och sedan diagonalen. Komplexa tal behövs inte för denna beräkning.'},
   {id:'strom',title:'Strömmen med spolen inkopplad',body:['Källspänningen är fortfarande 12,00 V RMS.','I = U/|Z| ≈ 12/50 = 0,24 A RMS.','Med bara R var strömmen 0,30 A. Med R och L blir den mindre och släpar efter spänningen.'],formula:'I = U/|Z|',visual:'rl',note:'Modellen använder XL = 30,0022 Ω, varför fler decimaler ger I ≈ 0,239994 A. Två decimaler är 0,24 A.'},
   {id:'exempel',title:'Ett genomräknat exempel',body:['En annan RL-krets har R = 12 Ω, X_{L} = 16 Ω och U = 60 V RMS.','|Z| = √(12² + 16²) = 20 Ω.','I = 60/20 = 3 A.','Spänningen över resistorn: U_{R} = I · R = 3 · 12 = 36 V. Spänningen över spolen: U_{L} = I · X_{L} = 3 · 16 = 48 V. De adderas vinkelrätt: √(36² + 48²) = 60 V, källans spänning.'],note:'Spänningarnas belopp summeras inte direkt eftersom de är fasförskjutna.'},
   {id:'labb',title:'Arbetsgång i den guidade labben',body:['Förutsäg X_{L}. Läs av och kontrollera enheten Ω.','Använd R och X_{L} för att beräkna |Z|.','Beräkna strömmen och jämför med kretsen som bara innehåller R.','Skriv varför strömmen ändras och vilken kurva som kommer först.'],note:'Uppgifterna ställer in samma krets automatiskt. Eleven gör beräkningen före avläsningen.'},
   {id:'fas',title:'Fasvinkel med tecken',body:['Fasvinkeln φ (fi) mellan spänning och ström: φ = arctan(X/R). Räknaren ska stå i DEG (grader).','För RL: X = +X_{L}. Med R = 40 Ω och X_{L} = 30 Ω blir φ ≈ +36,87°.','Positiv impedansvinkel innebär att källspänningen leder strömmen. Strömmen släpar.'],formula:'φ = arctan(X/R)',visual:'rl',note:'Skilj vinkelns tecken från den vardagliga formuleringen strömmen släpar.'},
   {id:'eget',title:'Eget försök med andra värden',body:['R = 30 Ω, X_{L} = 40 Ω och U = 100 V RMS.','Beräkna |Z| och I. Ange om strömmen leder eller släpar.'],note:'Be eleven rita de vinkelräta delarna om svaret bygger på 30 + 40.'},
   {id:'xc',title:'Fördjupning: kondensatorn',advanced:true,body:['En ideal kondensator lagrar energi i ett elektriskt fält. Strömmen leder dess spänning med 90°.','Kondensatorns reaktans skrivs X_{C}. C är kapacitansen i farad (F). C = 100 µF (mikrofarad) = 0,000100 F vid 50 Hz.','X_{C} = 1/(2π · 50 · 0,000100) ≈ 31,83 Ω.','När frekvensen fördubblas halveras X_{C}.'],formula:'X_{C} = 1/(2πfC)',note:'XC anges här som ett positivt belopp. Den kapacitiva nettoreaktansen har negativt tecken.'},
   {id:'rc',title:'Fördjupning: RC-krets',advanced:true,body:['Resistor och kondensator i serie kallas RC-krets. R = 40 Ω och X_{C} = 30 Ω. Nettoreaktansen är X = −30 Ω.','|Z| = √(40² + (−30)²) = 50 Ω.','φ = arctan(−30/40) ≈ −36,87°. Strömmen leder källspänningen.','Vid U = 100 V RMS blir I = 100/50 = 2,00 A.'],note:'Minus ingår i fasvinkeln. Kvadreringen gör impedansens belopp positivt.'},
   {id:'rlc',title:'Fördjupning: RLC och komplex form',advanced:true,body:['Resistor, spole och kondensator i serie kallas RLC-krets. I serie: X = X_{L} − X_{C}. Därefter |Z| = √(R² + X²).','Den komplexa skrivformen är Z = R + jX. Bokstaven j markerar att den reaktiva delen X ligger vinkelrätt mot R.','Exempel: R = 30 Ω, X_{L} = 50 Ω, X_{C} = 10 Ω. X = 40 Ω och |Z| = 50 Ω.'],note:'Komplex form introduceras efter att eleven förstått den geometriska betydelsen.'},
   {id:'resonans',title:'Fördjupning: resonansfrekvens',advanced:true,body:['Vid serieresonans är X_{L} = X_{C}. Nettoreaktansen blir noll och |Z| = R. Frekvensen där det händer kallas resonansfrekvens, f_{0}.','L = 50 mH = 0,050 H. C = 150 µF = 0,000150 F.','√(L · C) = √0,0000075 ≈ 0,0027386.','f_{0} = 1/(2π · 0,0027386) ≈ 58,12 Hz.'],formula:'f_{0} = 1/(2π√(L · C))',note:'Härledd ur 2πfL = 1/(2πfC). Vid R = 20 Ω och U = 100 V blir I = 5 A och φ = 0°. Verkliga komponenter har förluster och begränsningar.'},
   {id:'klart',title:'Kontroll före nästa del',body:['Kan du gå från mH till H och från X_{L} till ström?','Kan du förklara varför R och X_{L} ligger vinkelrätt?','Kan du visa att strömmen släpar i RL-kretsen?','Spara dina guidade mätningar och din förklaring.'],note:'Återgå till resistor- och spolkurvorna om ledande/släpande fortfarande är oklart.'}
  ]},
 {id:'effekt',number:3,title:'Effekt och effektfaktor',deck:'v40_03_Effekt_i_vaxelstromskretsar_elev.pptx',minutes:'90 min med läraren',goal:'Skilja på aktiv effekt P, reaktiv effekt Q och skenbar effekt S och förklara hur effektfaktorn påverkar matningsströmmen.',deliver:'Ström vid två effektfaktorer och en förklaring av vad som ändras.',filmTitle:'Samma aktiva effekt, olika ström',film:['resistiv','pf','strom','s','q','labb'],
  slides:[
   {id:'mal',title:'Det här behövs i labben',body:['En enfaslast arbetar vid spänningen U = 230 V (effektivvärde) och den aktiva effekten P = 1 150 W.','Jämför effektfaktorn 1,00 med 0,50. Behåll samma U och P.','Förklara vad som händer med strömmen och vad som är oförändrat.'],note:'Förslag: 30 min genomgång och film, 15 min räkning tillsammans, 30 min guidad labb, 15 min återkoppling. Modellen är sinusformad enfas, inte trefas.'},
   {id:'resistiv',title:'Resistiv last och aktiv effekt',body:['Aktiv effekt P är den medeleffekt som omvandlas till arbete och värme. Enheten är watt, W.','Vid effektfaktorn 1,00: I = P/U = 1 150/230 = 5,00 A.','Spänning och ström är i fas i den rent resistiva modellen.'],visual:'power',note:'Börja med ett bekant resistivt exempel innan reaktiv effekt introduceras.'},
   {id:'pf',title:'Effektfaktorn',body:['Effektfaktorn förkortas PF (power factor). PF = P/S, där S är den skenbara effekten (se nedan). PF saknar enhet och ligger mellan 0 och 1.','För rena sinussignaler är PF = cos φ, cosinus för fasvinkeln φ mellan spänning och ström. Lägre PF innebär större ström för samma U och P.','Vi jämför 1,00 och 0,50 utan att ändra lastens aktiva effekt.'],formula:'P = U · I · PF',visual:'power',note:'PF är inte motorns verkningsgrad. Undvik att säga att hälften av energin förbrukas i onödan vid PF = 0,5.'},
   {id:'strom',title:'Strömmen vid lägre effektfaktor',body:['Lös ut I genom att dividera båda sidor med U · PF.','Vid PF = 1,00: I = 1 150/(230 · 1) = 5,00 A.','Vid PF = 0,50: I = 1 150/(230 · 0,50) = 10,00 A.','Strömmen fördubblas. Lastens aktiva effekt är fortfarande 1 150 W.'],formula:'I = P/(U · PF)',visual:'power',note:'Skriv hela nämnaren inom parentes i räknaren.'},
   {id:'s',title:'Skenbar effekt',body:['Skenbar effekt S = U · I. Enheten är voltampere, VA.','Ur PF = P/S får vi PF · S = P och sedan S = P/PF.','Vid PF = 0,50: S = 1 150/0,50 = 2 300 VA.','Kontroll: 230 V · 10 A = 2 300 VA.'],formula:'S = P/PF = U · I',note:'Skilj VA från W även när talen råkar vara lika vid PF = 1.'},
   {id:'q',title:'Reaktiv effekt',body:['Reaktiv effekt Q beskriver energi som går fram och tillbaka mellan källan och spolar eller kondensatorer. Den förbrukas inte, men ger ändå ström i ledningarna.','För sinus: S² = P² + Q². Därför |Q| = √(S² − P²).','Exempel: S = 2 300 VA och P = 1 150 W ger |Q| ≈ 1 991,86 var. Enheten var betyder voltampere reaktiv.','I kursens teckenkonvention är induktiv Q positiv och kapacitiv Q negativ.'],formula:'|Q| = √(S² − P²)',visual:'powerTriangle',note:'Q är inte i sig en förbrukad energi. Den större strömmen kan däremot öka resistiva förluster.'},
   {id:'exempel',title:'Ett genomräknat exempel',body:['P = 1 200 W, PF = 0,75 och U = 230 V RMS. Lasten är induktiv och sinusformad.','S = 1 200/0,75 = 1 600 VA.','Q = √(1 600² − 1 200²) ≈ 1 058,30 var.','I = S/U = 1 600/230 ≈ 6,96 A.'],note:'Detta stänger luckan mellan given effektfaktor och reaktiv effekt i räkna-först-uppgifterna.'},
   {id:'labb',title:'Arbetsgång i den guidade labben',body:['Förutsäg strömmen vid PF = 1,00. Läs av och registrera värdet.','Förutsäg strömmen vid PF = 0,50. U och P hålls oförändrade.','Jämför de båda värdena och förklara orsaken.','Redovisa vilka storheter som ändrades och vilka som var konstanta.'],note:'Ingen kompensering eller kabelresistans behöver justeras för dessa två grunduppgifter.'},
   {id:'energi',title:'Effekt och energi',body:['Energi beror både på aktiv effekt och på tid.','E = P · t. Med kW (kilowatt) och timmar blir enheten kWh (kilowattimme).','1,60 kW under 3 h ger 4,80 kWh aktiv energi.','Använd P för aktiv energi, även om S är större.'],formula:'E = P · t',note:'Skilj anläggningens effektbehov från ackumulerad energianvändning.'},
   {id:'eget',title:'Eget försök med andra värden',body:['En enfaslast tar P = 2 300 W vid U = 230 V och PF = 0,50.','Beräkna I och S. Förklara om P skulle ändras bara för att PF förbättras i vår modell.'],note:'Be eleven ange vad som hålls konstant innan formeln används.'},
   {id:'kompensering',title:'Fördjupning: kompensation',advanced:true,body:['Att kompensera betyder att en kondensator tillför kapacitiv reaktiv effekt som tar ut en del av lastens induktiva Q.','Exempel: P = 2 000 W och PF = 0,80. S = 2 000/0,80 = 2 500 VA.','Q = √(2 500² − 2 000²) = +1 500 var.','För full kompensation behövs Q_{kondensator} = −1 500 var. Behovets belopp är 1 500 var.'],formula:'Q_{total} = Q_{last} + Q_{kondensator}',note:'Skilj kompensationsbehovets positiva belopp från kondensatorns negativa bidrag. Detta är en undervisningsmodell, ingen dimensioneringsanvisning.'},
   {id:'forlust',title:'Fördjupning: ledningsförlust',advanced:true,body:['Samma kabel har samma resistans R. Förlusten är I²R.','När strömmen minskar från 10 A till 5 A återstår (5/10)² = 0,25 av ledningsförlusten.','Ledningsförlusten minskar med 75 %. Lastens aktiva effekt behöver inte minska.'],formula:'P_{förlust} = I²R',note:'Procentsatsen gäller kabelns förlust. Den är inte en besparing på 75 % av hela lastens energibehov.'},
   {id:'overtoner',title:'Fördjupning: PF och cos φ',advanced:true,body:['PF = P/S gäller även när strömmen är förvrängd av övertoner (strömmar med 2, 3, 5 … gånger nätfrekvensen, till exempel från elektronik).','PF = cos φ förutsätter sinusformad spänning och ström.','Exempel: P = 800 W och S = 1 000 VA ger PF = 0,80, även om grundtonens cos φ är 0,95.','Den enkla effekttriangeln beskriver inte alla effekter vid övertoner.'],note:'Behåll detta som en uttrycklig begränsning av modellen. Verklig kompensation kräver bedömning av bland annat övertoner och resonans.'},
   {id:'klart',title:'Kontroll före redovisning',body:['Kan du förklara skillnaden mellan W (watt, aktiv effekt), var (voltampere reaktiv, reaktiv effekt) och VA (voltampere, skenbar effekt)?','Kan du räkna I när U, P och PF är givna?','Kan du förklara vad som ändras när PF sjunker vid samma P och U?','Spara ditt grundprotokoll. Läraren bedömer metoden och förklaringen.'],note:'Ifyllda rutor eller rätt antal ord visar inte ensamma att eleven förstår.'}
  ]}
];
export const lessonById=id=>LESSONS.find(l=>l.id===id)||LESSONS[0];

// Prova själv-frågorna kommer ur innehållsdatabasen (kontrollfragor.gen.mjs).
export const LESSONS = LEKTIONER.map((l) => ({ ...l, slides: l.slides.map((s) => { const k = KONTROLLFRAGOR.find((q) => q.del === l.id && q.bild === s.id); return k ? { ...s, check: k.check, answer: k.answer } : s; }) }));
