// Gemensamt undervisningsinnehåll för veckosida, genomgångar, stegfilmer och PowerPoint.
// Exempel är enfas och stationära. Komponenterna är ideala om inget annat anges.
export const REVISION = '20260925-ac2';
export const BASE = '/sjoskolan/vecka-40/aktuell/';
import {KONTROLLFRAGOR} from './kontrollfragor.gen.mjs';
const LEKTIONER = [
 {id:'sinus',number:1,title:'Sinus och mätvärden',deck:'v40_01_Sinusformad_vaxelspanning_elev.pptx',minutes:'Måndag: 45 min med läraren, sedan cirka 1 h 15 min hemma',goal:'Läsa periodtid och skilja på toppvärde, effektivvärde (RMS) och medelvärde.',
  deliver:'Instrumentkontroll, periodtid och toppvärde samt en förklaring till mätvärdena.',
  filmTitle:'Vad visar kurvan och multimetern?',film:['kurvan','period','topp','rms','matarna','protokoll'],
  slides:[
   {id:'mal',title:'Det här ska du kunna',body:['Hitta en hel period på kurvan och räkna periodtiden T ur frekvensen.','Skilja på toppvärde, effektivvärde (RMS) och medelvärde.','Förklara varför en multimeter och kurvans topp visar olika tal.'],note:'Säg: ”Idag lär ni er läsa en växelspänning: hur lång en period är, hur hög toppen är och varför multimetern visar ett annat tal än toppen.”\nLäs målen högt.\nMåndag 09.00–11.00. Pass 1: Frånskiljning och mätteknik (bildspelet från vecka-38-mappen, 19 bilder), film Fem steg, elevuppgift V2-1 och V2-2 i par. Pass 2: bild 3–8 (bild 8 Din tur), film 1, övning 1–3 tillsammans. Hemma måndag eftermiddag och tisdag förmiddag: resten av genomgången (från Medelvärde och RMS till Din tur: momentanvärde i vägguttaget), övning 4–10, V2-3 och V2-4. Sista 3 min: Skicka resultat, namn och QR-kod. Labben görs fredag.'},
   {id:'kurvan',title:'Spänning över tid',body:['Den vågräta axeln visar tid i millisekunder. Den lodräta visar spänning i volt.','Kurvan går över och under noll. Spänningens polaritet växlar.','En hel period går från en stigande nollpassage till nästa stigande nollpassage.'],visual:'wave',note:'Säg: ”Den vågräta axeln är tid, den lodräta är spänning. Följ kurvan med mig: noll, topp, noll, botten, noll.”\nPeka längs kurvan medan du säger det.\nFråga: ”Var börjar nästa period?” Låt någon peka.\nTänk på: kurvan visar spänningen vid olika tidpunkter, inte en partikel som åker upp och ner.'},
   {id:'period',title:'Periodtid och frekvens',body:['Frekvens f är antal perioder per sekund. Enheten är hertz, Hz.','Periodtiden T är tiden för en hel period. Ombord är frekvensen 60 Hz: T = 1/60 ≈ 0,0167 s = 16,7 ms (millisekunder, tusendels sekunder).','På kurvan är avståndet mellan motsvarande punkter 16,7 ms.'],formula:'T = 1/f     T i ms = 1 000/f',visual:'period',note:'Säg: ”Frekvensen säger hur många perioder som går på en sekund. Ombord är det 60. Då tar en period en sextiondels sekund, 16,7 millisekunder.”\nSkriv T = 1/f på tavlan.\nFråga (alla på tavlan, 30 s): kontrollfrågan på bilden. Säg ”Visa!” och läs svaret.\nTänk på: vanligt fel är att 0,0167 s skrivs som 0,0167 ms.'},
   {id:'topp',title:'Toppvärde och topp till topp',body:['Toppvärdet û (läses u-topp, u med hatt) mäts från noll till den positiva toppen.','Topp till topp, U_{pp} (pp: peak to peak), går från negativ topp till positiv topp.','Exempel, 440 V-nätet ombord: û ≈ 622 V och U_{pp} = 2 · û ≈ 1 245 V.'],formula:'U_{pp} = 2 · û',visual:'peak',note:'Säg: ”Toppvärdet mäts från noll upp till toppen. Topp till topp är hela höjden, från botten till toppen, alltså dubbelt så mycket.”\nPeka ut nollnivån på kurvan.\nFråga (alla på tavlan, 30 s): kontrollfrågan på bilden. Säg ”Visa!” och läs svaret.'},
   {id:'rms',title:'Effektivvärdet beskriver värmeeffekten',body:['Effektivvärdet 230 V i vägguttaget värmer en vattenkokare lika mycket som 230 V likspänning (DC).','Effektivvärdet förkortas RMS (root mean square, engelska för kvadratiskt medelvärde). U utan index betyder alltid effektivvärdet. Multimetern i växelspänningsläget (AC eller V~) visar 230 V i vägguttaget och 440 V ombord.','Toppen är högre eftersom spänningen bara når toppen en kort stund.'],formula:'û = √2 · U = √2 · 440 ≈ 622 V',visual:'rms',note:'Säg: ”230 volt växelspänning värmer en vattenkokare lika mycket som 230 volt likspänning. Det talet kallas effektivvärdet, och det är det multimetern visar. Toppen är högre, ungefär 1,4 gånger.”\nFråga: ”Nätet ombord är 440 V. Varför måste kablarna klara 622 V?” Svar: toppen är √2 · 440 ≈ 622 V.\nTänk på: förklara betydelsen innan förkortningen RMS.'},
   {id:'exempel',title:'Så räknar du: period och topp',example:true,body:['Givet: fartygets huvudnät, U = 440 V RMS och f = 60 Hz. RMS betyder effektivvärde.','Sökt: periodtid i millisekunder, toppvärde och topp till topp.','Välj samband: T = 1/f eftersom en sekund delas mellan f perioder. För en sinus är û = √2 · U och U_{pp} = 2 · û.','Räkna tiden: 1/60 ≈ 0,0167 s. Multiplicera med 1 000 för millisekunder: cirka 16,7 ms.','Räkna toppen: 440 · √2 ≈ 622 V. Dubbla toppvärdet för topp till topp: cirka 1 245 V.','Kontroll: 60 perioder på cirka 0,0167 s blir en sekund. Effektivvärdet är mindre än toppen, som är hälften av topp till topp.'],note:'Säg: ”Så räknar du. Vi gör fartygets nät tillsammans: 440 volt, 60 hertz.”\nLäs raderna i ordning: givet, sökt, samband, räkning, kontroll. Låt klassen säga nästa steg innan du läser det.\nSäg: ”Nästa bild är er tur, med andra tal.”\nTänk på: exemplet har samma metod men andra värden än labbens källa.'},
   {id:'tur-topp',title:'Din tur: belysningsnätet ombord',tur:true,body:['Räkna på papper eller miniwhiteboard. Titta på svaret först när du har ett eget.'],note:'Säg: ”Din tur. Skriv på tavlan. Ni har en minut.”\nLäs frågan högt. Vänta en minut.\nSäg: ”Visa!” Alla håller upp tavlan samtidigt. Hur många har rätt?\nKlicka: svaret visas. Läs det.\nOm många har fel: gå tillbaka en bild och visa var √2 kommer in.'},
   {id:'matarna',title:'Instrumentkontroll före mätningen',body:['I simulatorn väljer grunduppgiften en kalibrator på 10,00 V sinus.','Förutsäg visningen. Läs sedan av både true RMS-mätaren (räknar ut det verkliga effektivvärdet för alla kurvformer) och den sinuskalibrerade mätaren (visar rätt bara för ren sinus).','För en ren sinus visar båda mätartyperna kalibratorns effektivvärde. Skillnaden syns först vid andra kurvformer. Kontrollen dokumenteras för båda instrumenten.'],visual:'calibration',note:'Säg: ”I labben börjar ni med att kontrollera båda mätarna mot en kalibrator på 10 volt.”\nFråga: ”Vad tror ni att mätarna visar?” Låt dem gissa innan du läser vidare.\nTänk på: detta är en modell av instrumentkontroll, inte en fysisk kalibrering.'},
   {id:'protokoll',title:'En protokollrad',body:['Exempel från fartyget, 60 Hz. Förutsäg: T = 1 000/60 ≈ 16,7 ms.','Läs av och registrera 16,7 ms.','Jämför: avläst − förväntat = 0,0 ms.','Förklara: en hel period tar 16,7 ms. Frekvensen är 60 perioder per sekund. I labben gör du samma sak vid 50 Hz med din egen spänning, som räknas fram ur ditt D.'],note:'Säg: ”Så här ser en rad i protokollet ut: först förutsäger ni, sedan läser ni av, sedan jämför ni och förklarar.”\nVisa gärna guidad labb och en rad.\nFråga: ”Vad jämförs, och vilken enhet används?”'},
   {id:'medel',title:'Medelvärde och RMS är olika',body:['Den symmetriska sinusens positiva och negativa delar tar ut varandra. Vanligt medelvärde över en hel period är 0 V.','Resistorn blir ändå varm. Båda halvperioderna bidrar till u²/R.','För 440 V-nätet ombord: vanligt medelvärde 0 V, RMS 440 V och topp 622 V.'],visual:'wave',note:'Säg: ”Medelvärdet över en hel period är noll, eftersom plus och minus tar ut varandra. Men resistorn blir ändå varm: båda halvorna värmer.”\nFråga (alla på tavlan, 30 s): kontrollfrågan på bilden. Säg ”Visa!” och läs svaret.\nStanna här om eleverna blandar ihop medelvärde och effektivvärde.'},
   {id:'eget',title:'Eget försök med andra värden',body:['En sinus har U = 48,00 V RMS och f = 120 Hz.','Beräkna T och û. Ange både tal och enhet.','Förklara vilken avläsning en true RMS-multimeter visar.'],note:'Säg: ”Eget försök. Räkna innan ni tittar på facit.”\nLäs uppgiften högt. Ge två minuter.\nTänk på: godkänn inte att grundexemplet har kopierats; talen är andra.'},
   {id:'radianer',title:'Radianer och grader',body:['En vinkel kan mätas i grader eller i radianer, som en längd i meter eller i fot. Ett helt varv är 360° eller 2π radianer (cirka 6,28). 1 radian är cirka 57°.','Radianer mäter sträckan som kanten på ett hjul med radien 1 har rullat. Ett halvt varv är π och ett kvarts varv π/2.','Generatorn vrids ett varv per period, alltså 2π · f · t radianer efter tiden t. Därför står räknaren i RAD när du räknar u(t) = û · sin(2π · f · t).','Fasvinklar i grader, som 90° eller φ = arctan(X/R), räknas i DEG. Snabbkoll: blir sin(90) = 1 står räknaren i DEG.'],formula:'1 varv = 360° = 2π rad     1 rad ≈ 57°',visual:'radianer',note:'Säg: ”En vinkel kan mätas i grader eller i radianer, som en längd i meter eller i fot. Ett varv är 360 grader eller två pi radianer.”\nVisa hjulet: kanten rullar 2π ≈ 6,28 gånger radien på ett varv.\nSäg: ”Alla skriver sin(90) på räknaren.” 1 betyder DEG, 0,894 betyder RAD.\nSäg: ”Står det π eller 2πft i vinkeln: RAD. Grader och fasvinkel: DEG.”\nFilmen Radianer och grader visar samma sak (2 min).'},
   {id:'moment',title:'Fördjupning: momentanvärde',advanced:true,body:['Momentanvärdet u(t) är spänningen vid en bestämd tidpunkt t. Liten bokstav u betyder ett värde som ändras med tiden.','Exempel, fartygets 440 V-nät: U = 440 V RMS, f = 60 Hz, t = 2,0 ms = 0,002 s.','û = 440√2 ≈ 622 V. Vinkeln 2πft ≈ 0,754 rad (radianer; 2π radianer är ett helt varv, 360°).','u = 622 · sin(0,754) ≈ 426 V. Räknaren ska stå i RAD (radianer), inte DEG (grader).'],formula:'u(t) = û · sin(2πft)',note:'Säg: ”Momentanvärdet är spänningen just vid en viss tidpunkt. Vi räknar tillsammans, och räknaren ska stå i RAD.”\nRäkna på tavlan steg för steg: först û, sedan vinkeln 2πft, sedan u. Låt alla trycka samtidigt.\nFråga: ”Vad blir svaret om räknaren står i DEG?” Mycket för litet, alltså fel.\nTänk på: under den negativa halvperioden blir momentanvärdet negativt.'},
   {id:'tur-moment',title:'Din tur: momentanvärde i vägguttaget',advanced:true,tur:true,body:['Räkna på papper eller miniwhiteboard. Titta på svaret först när du har ett eget.'],note:'Säg: ”Din tur. Räknaren i RAD. Ni har två minuter.”\nLäs frågan högt. Vänta.\nSäg: ”Visa!” Svar kring 5 V betyder att räknaren står i DEG.\nKlicka: svaret visas. Läs det.'},
   {id:'fas',title:'Fördjupning: tid och fas',advanced:true,body:['En hel period motsvarar 360°. Fasvinkeln φ (fi) anger hur långt två kurvor är förskjutna, och Δt (delta t) är tidsskillnaden mellan dem.','Ombord, vid 60 Hz, är T ≈ 16,7 ms. Ett tidsavstånd på 2,5 ms ger 360 · 2,5/16,67 ≈ 54°.','Kurvan som når motsvarande punkt först leder. Den andra släpar.'],formula:'|φ| = 360° · Δt/T',note:'Eleverna läser bilden själva vid övning 8.\nOm du visar den: Säg: ”En hel period är 360 grader. Tidsskillnaden mellan två kurvor ger fasvinkeln.”\nTänk på: beloppet räcker inte för att avgöra vem som leder; läs kurvornas ordning.'},
   {id:'likriktat',title:'Fördjupning: likriktat medelvärde',advanced:true,body:['Vid likriktning speglas den negativa halvperioden uppåt. |u| betyder spänningen utan tecken (beloppet), så medelvärdet av |u| blir positivt.','För sinus: medel(|u|) = 2û/π. Vid 12,00 V RMS blir det cirka 10,80 V.','En medelvärdesmätande, sinuskalibrerad mätare multiplicerar detta med cirka 1,11072 och visar 12,00 V.'],formula:'Visning = π/(2√2) · medel(|u|)',note:'Fördjupning för snabba elever. Säg: ”En likriktare speglar den negativa halvan uppåt. Då blir medelvärdet inte noll.”\nKälla: Fluke, True measurements of non-linear loads require a true-RMS measurement tool. Håll isär vanligt medelvärde, likriktat medelvärde och RMS.'},
   {id:'kurvformer',title:'Fördjupning: samma RMS, olika visning',advanced:true,body:['Alla tre signalerna har effektivvärdet 10,00 V och ingen likspänningsdel (DC-innehåll).','Sinus: topp 14,14 V. Den sinuskalibrerade mätaren visar 10,00 V.','Fyrkant: topp 10,00 V. Medel(|u|) = 10,00 V. Visning ≈ 11,11 V.','Triangel: topp = √3 · 10 ≈ 17,32 V. Medel(|u|) = û/2. Visning ≈ 9,62 V.'],visual:'meters',note:'Fördjupning. Säg: ”Tre kurvor med samma effektivvärde. En true RMS-mätare visar 10 volt på alla tre. Den sinuskalibrerade visar fel på fyrkant och triangel.”\nTänk på: här hålls RMS konstant. Verkliga instrument har frekvens-, bandbredds- och crestfaktorgränser.'},
   {id:'station',title:'Fördjupning: Station B',advanced:true,body:['Stationsmodellen är märkt 12 V ±0,5 V och ger 12,35 V RMS vid 50 Hz.','Använd avlästa 12,35 V när du förutsäger toppen: cirka 17,47 V.','Fyrkant ger cirka 13,72 V på den sinuskalibrerade mätaren, trots att RMS är 12,35 V.','Att visningen stämmer med mätarmodellen betyder inte att den visar korrekt RMS.'],note:'Fördjupning inför Station B. Säg: ”Källan är märkt 12 volt men ger 12,35. Använd det avlästa värdet när ni förutsäger toppen.”\nTänk på: skilj källans avvikelse från instrumentets visningsprincip.'},
   {id:'klart',title:'Inför nästa del',body:['Genomför grunduppgifterna och spara protokollet.','Förklara med egna ord skillnaden mellan effektivvärde (RMS), toppvärde och vanligt medelvärde.','Fysisk anslutning, oscilloskopets inställningar och godkända mätpunkter övas på den verkliga stationen.'],note:'Säg: ”Innan vi slutar: förklara för din granne skillnaden mellan toppvärde, effektivvärde och medelvärde.” Ge en minut.\nSäg: ”Skicka era resultat nu: sidan Skicka resultat, skriv namnet och ta en skärmbild av QR-koden.”\nTänk på: säkerheten i verklig mätning godkänns inte genom ett klick i simulatorn.'}
  ]},
 {id:'impedans',number:2,title:'Spole, motstånd och ström',deck:'v40_02_Reaktans_och_impedans_elev.pptx',minutes:'Tisdag: 90 min med läraren, sedan cirka 1 h hemma',goal:'Beräkna reaktans och ström i en krets med resistor och spole (RL-krets) och tolka vilken signal som släpar.',deliver:'Reaktans, impedans och ström samt en förklaring av spolens inverkan.',filmTitle:'Vad händer när vi lägger till en spole?',film:['resistor','spole','xl','z','strom','labb'],
  slides:[
   {id:'mal',title:'Det här ska du kunna',body:['Räkna strömmen genom en resistor med Ohms lag.','Omvandla mH (millihenry) till H (henry, enheten för induktans) och räkna spolens reaktans X_{L}.','Räkna impedansen |Z| och strömmen när en spole sitter i serie med en resistor.'],note:'Säg: ”Idag: vad händer med strömmen när vi sätter en spole i serie med ett motstånd?”\nLäs målen högt.\nTisdag 15.00–17.00. Pass 1: frågor från del 1 och övning 4–10, sedan bild 3–9 (bild 8 Din tur) och film 2. Pass 2: övning 1–4, påbörja inlämning uppgift 1. Hemma onsdag: resten av genomgången (från Fasvinkel med tecken, bild 11, med Din tur på bild 12), övning 5–10 och Frånskiljningens inlämning uppgift 1–3. Snabba elever: bild 14–17. Sista 3 min: Skicka resultat (QR-kod). Labben görs fredag.'},
   {id:'resistor',title:'En resistor',body:['Ett värmeelement på 50 Ω ligger på 230 V RMS.','I = U/R = 230/50 = 4,6 A RMS.','Spänning och ström har toppar och nollpassager samtidigt. De är i fas.'],visual:'resistor',note:'Säg: ”Ett värmeelement på 50 ohm i vägguttaget. Ohms lag: 230 delat med 50 är 4,6 ampere. Spänning och ström når toppen samtidigt. De är i fas.”\nTänk på: kurvorna har egna skalor. Jämför tiden, inte höjden.'},
   {id:'spole',title:'En spole i serie',body:['En ideal spole lagrar energi i ett magnetfält och motverkar ändringar i strömmen.','Resistor (R) och spole (L) i serie kallas RL-krets. I RL-kretsen kommer strömmens topp efter källspänningens topp. Strömmen släpar.','Spolen tillför reaktans, ett motstånd mot växelström som mäts i ohm. Den påverkar strömmen utöver resistorn.'],visual:'rl',note:'Säg: ”En spole motverkar ändringar i strömmen. Därför kommer strömmens topp lite efter spänningens. Vi säger att strömmen släpar.”\nFråga: ”Vilken kurva når toppen först?” Låt någon peka.\nTänk på: en ideal spole ensam ger 90°; med motstånd blir vinkeln mellan 0° och 90°.'},
   {id:'xl',title:'Reaktans och enheter',body:['Spolens reaktans skrivs X_{L} (X för reaktans, L för spole). L är spolens induktans i henry. Exempel: en fläktmotors lindning har L = 382 mH = 0,382 H och f = 50 Hz.','X_{L} = 2π · 50 · 0,382 ≈ 120 Ω. Ombord, vid 60 Hz, blir X_{L} ≈ 144 Ω.','Vid dubbla frekvensen blir X_{L} dubbelt så stor om L är oförändrad.'],formula:'X_{L} = 2πfL',note:'Säg: ”Spolens motstånd mot växelström heter reaktans, X_{L}. Formeln är 2π gånger f gånger L, och L ska stå i henry.”\nSkriv omvandlingen på en egen rad: 382 mH = 0,382 H.\nFråga (alla på tavlan, 30 s): kontrollfrågan på bilden. Säg ”Visa!” och läs svaret.\nTänk på: X_{L} är reaktans, inte trådens resistans.'},
   {id:'z',title:'Impedansen i RL-kretsen',body:['Impedansen Z är kretsens totala motstånd mot växelström. Fläktmotorns lindning: R = 50 Ω och X_{L} ≈ 120 Ω är vinkelräta delar i impedansdiagrammet.','|Z| = √(50² + 120²) = √16 900 = 130 Ω.','Beloppen 50 och 120 ska inte adderas direkt. Diagonalen ger impedansens belopp |Z|; strecken betyder belopp (storlek).'],formula:'|Z| = √(R² + X_{L}²)',visual:'triangle',note:'Säg: ”Motståndet och reaktansen ligger vinkelrätt, som två sidor i en rätvinklig triangel. Impedansen är diagonalen: Pythagoras.”\nRita sidorna först, sedan diagonalen.\nFråga: ”Varför blir det inte 50 plus 120?” De ligger vinkelrätt.'},
   {id:'strom',title:'Strömmen med spolen inkopplad',body:['Fläktmotorn ligger på 230 V RMS.','I = U/|Z| ≈ 230/130 ≈ 1,77 A RMS.','Med bara resistansen 50 Ω skulle strömmen vara 4,6 A. Med R och L blir den mindre och släpar efter spänningen.'],formula:'I = U/|Z|',visual:'rl',note:'Säg: ”Strömmen är spänningen delat med impedansen. 230 delat med 130 ger 1,77 ampere. Utan spolen var det 4,6.”\nFråga (alla på tavlan, 30 s): kontrollfrågan på bilden. Säg ”Visa!” och läs svaret.\nSäg: ”Nästa bild är er tur.”'},
   {id:'tur-z',title:'Din tur: ventilationsfläkten',tur:true,body:['Räkna på papper eller miniwhiteboard. Titta på svaret först när du har ett eget.'],note:'Säg: ”Din tur. Skriv på tavlan. Ni har två minuter.”\nLäs frågan högt. Vänta.\nSäg: ”Visa!” Svaret 155 Ω betyder att någon har adderat 110 + 45 i stället för att använda Pythagoras.\nKlicka: svaret visas. Läs det.'},
   {id:'exempel',title:'Så räknar du: impedans och ström',example:true,body:['Givet: en RL-krets med R = 12 Ω, X_{L} = 16 Ω och U = 60 V RMS.','Sökt: först impedansen, sedan strömmen och spänningen över varje komponent.','Välj samband: R och X_{L} ligger vinkelrätt. Därför används |Z| = √(R² + X_{L}²), följt av I = U/|Z|.','Räkna i ordning: 12² = 144, 16² = 256, summan är 400. Roten ur 400 är 20 Ω. Därefter I = 60/20 = 3 A.','Använd strömmen i båda komponenterna: U_{R} = 3 · 12 = 36 V. U_{L} = 3 · 16 = 48 V.','Kontroll: spänningarna är vinkelräta. √(36² + 48²) = 60 V, samma som källan. De ska inte adderas direkt.'],note:'Säg: ”Så räknar du. Följ med: givet, sökt, samband, sedan impedansen, strömmen och spänningen över varje del.”\nFråga innan kontrollraden: ”Blir 36 plus 48 lika med 60?” Nej, spänningarna adderas vinkelrätt.\nTänk på: spänningarnas belopp summeras inte direkt eftersom de är fasförskjutna.'},
   {id:'labb',title:'Arbetsgång i den guidade labben',body:['Du får egna värden på R och L ur ditt D. Förutsäg X_{L}, läs av och kontrollera enheten Ω.','Använd R och X_{L} för att beräkna |Z|.','Beräkna strömmen och jämför med kretsen som bara innehåller R.','Skriv varför strömmen ändras och vilken kurva som kommer först.'],note:'Säg: ”I labben får ni egna värden ur ert D. Förutsäg först, läs sedan av.”\nVisa gärna en uppgift i guidad labb.\nTänk på: labben ställer in kretsen automatiskt; eleven räknar före avläsningen.'},
   {id:'fas',title:'Fasvinkel med tecken',body:['Fasvinkeln φ (fi) mellan spänning och ström: φ = arctan(X/R). Räknaren ska stå i DEG (grader).','För RL: X = +X_{L}. Fläktmotorn med R = 50 Ω och X_{L} = 120 Ω får φ ≈ +67,38°.','Positiv impedansvinkel innebär att källspänningen leder strömmen. Strömmen släpar.'],formula:'φ = arctan(X/R)',visual:'rl',note:'Säg: ”Fasvinkeln räknas med arctan av X delat med R. Nu ska räknaren stå i DEG, grader. I måndags var det RAD.”\nSäg: ”Alla kontrollerar att sin(90) blir 1.”\nRäkna fläktmotorns vinkel tillsammans.\nTänk på: skilj vinkelns tecken från orden strömmen släpar.'},
   {id:'tur-fas',title:'Din tur: fläktens fasvinkel',tur:true,body:['Räkna på papper eller miniwhiteboard. Titta på svaret först när du har ett eget.'],note:'Säg: ”Din tur. Räknaren i DEG. Ni har en minut.”\nLäs frågan högt. Vänta.\nSäg: ”Visa!” Svaret 0,39 betyder att räknaren står i RAD.\nKlicka: svaret visas. Läs det.'},
   {id:'eget',title:'Eget försök med andra värden',body:['R = 90 Ω, X_{L} = 120 Ω och U = 230 V RMS.','Beräkna |Z| och I. Ange om strömmen leder eller släpar.'],note:'Säg: ”Eget försök med andra värden. Räkna innan facit visas.”\nGe två minuter.\nTänk på: be eleven rita de vinkelräta delarna om svaret bygger på 90 + 120.'},
   {id:'xc',title:'Fördjupning: kondensatorn',advanced:true,body:['En ideal kondensator lagrar energi i ett elektriskt fält. Strömmen leder dess spänning med 90°.','Kondensatorns reaktans skrivs X_{C}. C är kapacitansen i farad (F). C = 47 µF (mikrofarad) = 0,000047 F vid 50 Hz.','X_{C} = 1/(2π · 50 · 0,000047) ≈ 67,7 Ω.','När frekvensen fördubblas halveras X_{C}.'],formula:'X_{C} = 1/(2πfC)',note:'Fördjupning. Säg: ”En kondensator gör tvärtom mot spolen: strömmen leder. Reaktansen minskar när frekvensen ökar.”\nTänk på: X_{C} anges här som ett positivt belopp; nettoreaktansen har negativt tecken.'},
   {id:'rc',title:'Fördjupning: RC-krets',advanced:true,body:['Resistor och kondensator i serie kallas RC-krets. R = 60 Ω och X_{C} = 80 Ω. Nettoreaktansen är X = −80 Ω.','|Z| = √(60² + (−80)²) = 100 Ω.','φ = arctan(−80/60) ≈ −53,13°. Strömmen leder källspänningen.','Vid U = 230 V RMS blir I = 230/100 = 2,30 A.'],note:'Fördjupning. Säg: ”Med en kondensator blir X negativ. Kvadraten gör impedansen positiv, men fasvinkeln blir negativ: strömmen leder.”\nTänk på: minus ingår i fasvinkeln.'},
   {id:'rlc',title:'Fördjupning: RLC och komplex form',advanced:true,body:['Resistor, spole och kondensator i serie kallas RLC-krets. I serie: X = X_{L} − X_{C}. Därefter |Z| = √(R² + X²).','Den komplexa skrivformen är Z = R + jX. Bokstaven j markerar att den reaktiva delen X ligger vinkelrätt mot R.','Exempel: R = 45 Ω, X_{L} = 80 Ω, X_{C} = 20 Ω. X = 60 Ω och |Z| = 75 Ω.'],note:'Fördjupning. Säg: ”Med både spole och kondensator drar man X_{C} från X_{L} och räknar sedan som vanligt.”\nTänk på: introducera komplex form först när den geometriska bilden sitter.'},
   {id:'resonans',title:'Fördjupning: resonansfrekvens',advanced:true,body:['Vid serieresonans är X_{L} = X_{C}. Nettoreaktansen blir noll och |Z| = R. Frekvensen där det händer kallas resonansfrekvens, f_{0}.','L = 100 mH = 0,100 H. C = 47 µF = 0,000047 F.','√(L · C) = √0,0000047 ≈ 0,0021679.','f_{0} = 1/(2π · 0,0021679) ≈ 73,4 Hz.'],formula:'f_{0} = 1/(2π√(L · C))',note:'Fördjupning. Säg: ”Vid en viss frekvens tar spolen och kondensatorn ut varandra. Då är impedansen bara R.”\nTänk på: härledd ur 2πfL = 1/(2πfC). Vid R = 25 Ω och U = 100 V blir I = 4 A och φ = 0°.'},
   {id:'klart',title:'Kontroll före nästa del',body:['Kan du gå från mH till H och från X_{L} till ström?','Kan du förklara varför R och X_{L} ligger vinkelrätt?','Kan du visa att strömmen släpar i RL-kretsen?','Spara dina guidade mätningar och din förklaring.'],note:'Säg: ”Visa för din granne hur du går från mH till ström.” Ge en minut.\nSäg: ”Skicka era resultat nu: Skicka resultat, namn, QR-kod.”\nTänk på: gå tillbaka till kurvorna på bild 3 och 4 om ledande och släpande fortfarande är oklart.'}
  ]},
 {id:'effekt',number:3,title:'Effekt och effektfaktor',deck:'v40_03_Effekt_i_vaxelstromskretsar_elev.pptx',minutes:'Torsdag: cirka 1 h 15 min hemma, fredag med läraren',goal:'Skilja på aktiv effekt P, reaktiv effekt Q och skenbar effekt S och förklara hur effektfaktorn påverkar matningsströmmen.',deliver:'Ström vid två effektfaktorer och en förklaring av vad som ändras.',filmTitle:'Samma aktiva effekt, olika ström',film:['resistiv','pf','strom','s','q','labb'],
  slides:[
   {id:'mal',title:'Det här ska du kunna',body:['Skilja på aktiv effekt P, reaktiv effekt Q och skenbar effekt S.','Räkna strömmen när U, P och effektfaktorn PF är givna.','Förklara varför lägre effektfaktor ger större ström vid samma P och U.'],note:'Säg: ”Idag: varför drar en motor mer ström när effektfaktorn är låg, fast den gör samma arbete?”\nLäs målen högt.\nDel 3 läser eleverna hemma torsdag: genomgången (med Din tur på bild 9), film 3 och övning 1–6, sedan inlämning uppgift 1–2. Fredag 09.00–11.00. Pass 1: elevernas frågor från del 3, övning 7–10 tillsammans (med kompensering inför inlämning uppgift 3, bild 13–14). Pass 2: guidad labb, alla åtta uppgifter, veckans sista steg. Sista 3 min: Skicka resultat (QR-kod) med labbprotokollet. Fredag eftermiddag och helgen: labbet klart, inlämning uppgift 3–4, båda inlämningarna senast söndag 4 oktober. Modellen är sinusformad enfas, inte trefas.'},
   {id:'resistiv',title:'Resistiv last och aktiv effekt',body:['Aktiv effekt P är den medeleffekt som omvandlas till arbete och värme. Enheten är watt, W.','Exempel: ett värmeelement på 1 380 W vid 230 V har effektfaktorn 1,00: I = P/U = 1 380/230 = 6,00 A.','Spänning och ström är i fas i den rent resistiva modellen.'],visual:'power',note:'Säg: ”Vi börjar med något bekant: ett värmeelement. Effekten delat med spänningen ger strömmen: 1 380 watt delat med 230 volt är 6 ampere.”\nTänk på: börja resistivt innan reaktiv effekt introduceras.'},
   {id:'pf',title:'Effektfaktorn',body:['Effektfaktorn förkortas PF (power factor). PF = P/S, där S är den skenbara effekten (se nedan). PF saknar enhet och ligger mellan 0 och 1.','För rena sinussignaler är PF = cos φ, cosinus för fasvinkeln φ mellan spänning och ström. Lägre PF innebär större ström för samma U och P.','Vi jämför 1,00 och 0,50 utan att ändra lastens aktiva effekt.'],formula:'P = U · I · PF',visual:'power',note:'Säg: ”Effektfaktorn säger hur stor del av strömmen som gör nytta. 1 är bäst. Lägre effektfaktor betyder mer ström för samma arbete.”\nFråga: ”Är effektfaktor samma sak som verkningsgrad?” Nej.\nTänk på: säg inte att hälften av energin förbrukas i onödan vid PF = 0,5.'},
   {id:'strom',title:'Strömmen vid lägre effektfaktor',body:['Lös ut I genom att dividera båda sidor med U · PF.','Exempel: en pumpmotor på 1 380 W vid 230 V.','Vid PF = 1,00: I = 1 380/(230 · 1) = 6,00 A.','Vid PF = 0,50: I = 1 380/(230 · 0,50) = 12,00 A. Strömmen fördubblas, men den aktiva effekten är fortfarande 1 380 W.'],formula:'I = P/(U · PF)',visual:'power',note:'Fråga först: ”Gissa: blir strömmen större eller mindre när effektfaktorn sjunker till 0,5?”\nSäg: ”Samma pumpmotor, samma effekt. Vid effektfaktor 1 blir strömmen 6 ampere. Vid 0,5 blir den 12. Dubbelt så mycket ström.”\nTänk på: skriv hela nämnaren inom parentes i räknaren.'},
   {id:'s',title:'Skenbar effekt',body:['Skenbar effekt S = U · I. Enheten är voltampere, VA.','Ur PF = P/S får vi PF · S = P och sedan S = P/PF.','Pumpmotorn vid PF = 0,50: S = 1 380/0,50 = 2 760 VA.','Kontroll: 230 V · 12 A = 2 760 VA.'],formula:'S = P/PF = U · I',note:'Säg: ”Skenbar effekt är spänning gånger ström, i voltampere. Den är större än den aktiva effekten när effektfaktorn är under 1.”\nTänk på: skilj VA från W även när talen är lika vid PF = 1.'},
   {id:'q',title:'Reaktiv effekt',body:['Reaktiv effekt Q beskriver energi som går fram och tillbaka mellan källan och spolar eller kondensatorer. Den förbrukas inte, men ger ändå ström i ledningarna.','För sinus: S² = P² + Q². Därför |Q| = √(S² − P²).','Exempel: S = 2 760 VA och P = 1 380 W ger |Q| ≈ 2 390,23 var. Enheten var betyder voltampere reaktiv.','I kursens teckenkonvention är induktiv Q positiv och kapacitiv Q negativ.'],formula:'|Q| = √(S² − P²)',visual:'powerTriangle',note:'Säg: ”Reaktiv effekt är energi som pendlar fram och tillbaka. Den förbrukas inte, men den ger ström i ledningarna. P, Q och S bildar en rätvinklig triangel.”\nTänk på: Q är inte i sig förbrukad energi, men den större strömmen ökar förlusterna i kablarna.'},
   {id:'exempel',title:'Så räknar du: effekt och ström',example:true,body:['Givet: P = 1 200 W, PF = 0,75 och U = 230 V RMS. Lasten är induktiv och sinusformad.','Sökt: skenbar effekt S, reaktiv effekt Q och ström I.','Välj ordning: PF = P/S ger S = P/PF. När S är känd kan Q och I räknas.','S = 1 200/0,75 = 1 600 VA. Eftersom S² = P² + Q² får vi Q = √(1 600² − 1 200²) ≈ 1 058 var.','S = U · I ger I = S/U. Alltså I = 1 600/230 ≈ 6,96 A. Skriv hela uttrycket innan du räknar.','Kontroll: U · I · PF ≈ 230 · 6,96 · 0,75 ≈ 1 200 W. Avrundningen förklarar den lilla skillnaden.'],note:'Säg: ”Så räknar du. Följ med: givet, sökt, ordning, sedan S, Q och strömmen, och till sist kontrollen.”\nLåt klassen säga nästa steg innan du läser det.\nSäg: ”Nästa bild är er tur.”'},
   {id:'tur-effekt',title:'Din tur: kylskåpets kompressor',tur:true,body:['Räkna på papper eller miniwhiteboard. Titta på svaret först när du har ett eget.'],note:'Säg: ”Din tur. Skriv på tavlan. Ni har två minuter.”\nLäs frågan högt. Vänta.\nSäg: ”Visa!” Svaret 0,65 A betyder att någon har räknat P/U och glömt effektfaktorn.\nKlicka: svaret visas. Läs det.'},
   {id:'labb',title:'Arbetsgång i den guidade labben',body:['Du får en egen effekt P ur ditt D. Förutsäg strömmen vid PF = 1,00, läs av och registrera värdet.','Förutsäg strömmen vid PF = 0,50. U och P hålls oförändrade.','Jämför de båda värdena och förklara orsaken.','Redovisa vilka storheter som ändrades och vilka som var konstanta.'],note:'Säg: ”I labben får ni en egen effekt ur ert D. Förutsäg strömmen vid effektfaktor 1 och vid 0,5.”\nTänk på: ingen kompensering eller kabelresistans behöver justeras i grunduppgifterna.'},
   {id:'energi',title:'Effekt och energi',body:['Energi beror både på aktiv effekt och på tid.','E = P · t. Med kW (kilowatt) och timmar blir enheten kWh (kilowattimme).','1,60 kW under 3 h ger 4,80 kWh aktiv energi.','Använd P för aktiv energi, även om S är större.'],formula:'E = P · t',note:'Säg: ”Energi är effekt gånger tid. 1,6 kilowatt i tre timmar är 4,8 kilowattimmar.”\nTänk på: använd P för aktiv energi, även om S är större.'},
   {id:'eget',title:'Eget försök med andra värden',body:['En enfaslast tar P = 4 140 W vid U = 230 V och PF = 0,60.','Beräkna I och S. Förklara om P skulle ändras bara för att PF förbättras i vår modell.'],note:'Säg: ”Eget försök. Räkna innan facit visas.”\nGe två minuter.\nTänk på: be eleven säga vad som hålls konstant innan formeln används.'},
   {id:'kompensering',title:'Fördjupning: kompensation',advanced:true,body:['Att kompensera betyder att en kondensator tillför kapacitiv reaktiv effekt som tar ut en del av lastens induktiva Q.','Exempel: pumpmotorn P = 1 380 W och PF = 0,80. S = 1 380/0,80 = 1 725 VA.','Q = √(1 725² − 1 380²) = +1 035 var.','För full kompensation behövs Q_{kondensator} = −1 035 var. Behovets belopp är 1 035 var.'],formula:'Q_{total} = Q_{last} + Q_{kondensator}',note:'Fördjupning och inför inlämning uppgift 3. Säg: ”En kondensator ger kapacitiv reaktiv effekt som tar ut en del av motorns induktiva. Då minskar strömmen.”\nTänk på: skilj behovets positiva belopp från kondensatorns negativa bidrag. Undervisningsmodell, ingen dimensioneringsanvisning.'},
   {id:'forlust',title:'Fördjupning: ledningsförlust',advanced:true,body:['Samma kabel har samma resistans R. Förlusten är I²R.','När strömmen minskar från 12 A till 6 A återstår (6/12)² = 0,25 av ledningsförlusten.','Ledningsförlusten minskar med 75 %. Lastens aktiva effekt behöver inte minska.'],formula:'P_{förlust} = I²R',note:'Fördjupning. Säg: ”Förlusten i kabeln är strömmen i kvadrat gånger resistansen. Halverad ström ger en fjärdedel av förlusten.”\nTänk på: procenten gäller kabelns förlust, inte hela lastens energi.'},
   {id:'overtoner',title:'Fördjupning: PF och cos φ',advanced:true,body:['PF = P/S gäller även när strömmen är förvrängd av övertoner (strömmar med 2, 3, 5 … gånger nätfrekvensen, till exempel från elektronik).','PF = cos φ förutsätter sinusformad spänning och ström.','Exempel: P = 800 W och S = 1 000 VA ger PF = 0,80, även om grundtonens cos φ är 0,95.','Den enkla effekttriangeln beskriver inte alla effekter vid övertoner.'],note:'Fördjupning. Säg: ”Med elektronik blir strömmen förvrängd. Då gäller PF = P/S fortfarande, men inte cos φ.”\nTänk på: verklig kompensering kräver bedömning av övertoner och resonans.'},
   {id:'klart',title:'Kontroll före redovisning',body:['Kan du förklara skillnaden mellan W (watt, aktiv effekt), var (voltampere reaktiv, reaktiv effekt) och VA (voltampere, skenbar effekt)?','Kan du räkna I när U, P och PF är givna?','Kan du förklara vad som ändras när PF sjunker vid samma P och U?','Spara ditt grundprotokoll. Läraren bedömer metoden och förklaringen.'],note:'Säg: ”Förklara för din granne skillnaden mellan watt, var och voltampere.” Ge en minut.\nSäg: ”Skicka era resultat nu, med labbprotokollet: Skicka resultat, namn, QR-kod.”\nTänk på: ifyllda rutor visar inte ensamma att eleven förstår.'}
  ]}
];
export const lessonById=id=>LESSONS.find(l=>l.id===id)||LESSONS[0];

// Prova själv-frågorna kommer ur innehållsdatabasen (kontrollfragor.gen.mjs).
export const LESSONS = LEKTIONER.map((l) => ({ ...l, slides: l.slides.map((s) => { const k = KONTROLLFRAGOR.find((q) => q.del === l.id && q.bild === s.id); return k ? { ...s, check: k.check, answer: k.answer } : s; }) }));
