import {publishEquipment} from './equipment-state.mjs';
import {markHtml as m,markText} from '../gemensamt/markering.mjs?v=20260928';
import {GUIDE_TASKS,GUIDE_VERSION,guideValues,parseGuideNumber,personligUppgift,elevtal} from './guided-lessons.mjs?v=20260930';
import {mittD,sattMittD,harMittD,sparatNamn} from '../gemensamt/elevtal.mjs?v=20260930';
import {hjalpHtml} from '../gemensamt/raknehjalp.mjs?v=20260929c';
import {LESSONS} from '../vecka-40/aktuell/lektioner.mjs?v=20260930u';
import {visual} from '../vecka-40/aktuell/visuals.mjs?v=20260928fg';
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const n=v=>v.toLocaleString('sv-SE',{minimumFractionDigits:2,maximumFractionDigits:2});
const KEY='sjoskolan-ac-grund-utkast';   // UTKAST: egen nyckel. Tillbaka till 'sjoskolan-ac-grund-v3' när utkastet ersätter labben.
const tid=iso=>iso?new Date(iso).toLocaleString('sv-SE',{dateStyle:'short',timeStyle:'short'}):'';
// Läshänvisning: den bild i genomgången som förklarar metoden (del och bildnummer räknas ur lektionerna).
// Läshänvisning till delsidan (vecka-40/aktuell/Del_N.html): teoriavsnittets nummer räknas som på delsidan
// (innehall/export/delsidor.py). Delens nummer i veckan är number + 1: frånskiljningen är del 1.
const EJ_TEORI=['mal','exempel','eget','klart','labb','matarna','protokoll'];
function las(task){const l=LESSONS.find(x=>x.id===task.lesson);if(!l)return '';const s=l.slides.find(x=>x.id===task.theory),d=l.number+1,sida=`../vecka-40/aktuell/Del_${l.number}.html`;
 const teori=l.slides.filter(x=>!EJ_TEORI.includes(x.id)&&!x.example&&!x.tur),j=teori.findIndex(x=>x.id===task.theory);
 const [href,text]=!s?[sida,`del ${d}`]:j>=0?[`${sida}#teori-${s.id}`,`del ${d}, teori ${j+1}: ${m(s.title)}`]:s.example||s.id==='exempel'?[`${sida}#exempel-${s.id}`,`del ${d}, exemplet: ${m(s.title)}`]:[`${sida}#labb-${s.id}`,`del ${d}: ${m(s.title)}`];
 return `Kan du inte metoden? Läs <a href="${href}" target="_blank" rel="noopener">${text}</a> (öppnas i ny flik) och gör sedan uppgiften.`;}
export function mountGuide(root){
 // D slumpas en gång per enhet (gemensamt/elevtal.mjs). Namnet skrivs först i slutet, på sidan Skicka resultat.
 // Ett äldre protokoll med namn behåller sitt D (räknat ur namnet), så att påbörjat arbete inte går förlorat.
 let data={version:GUIDE_VERSION,D:null,rows:{}},storageOK=true;
 try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.version===GUIDE_VERSION&&s.rows&&typeof s.rows==='object'){const D=Number.isInteger(s.D)?s.D:(s.name?elevtal(s.name):null);if(D&&!harMittD())sattMittD(D);if(D===mittD())data={version:GUIDE_VERSION,D,rows:s.rows};}}catch{storageOK=false;}
 if(!data.D)data.D=mittD();
 let TASKS=GUIDE_TASKS.map(t=>personligUppgift(t,data.D));
 const params=new URLSearchParams(location.search);
 let task=TASKS.find(t=>t.id===params.get('steg'))||TASKS.find(t=>t.lesson===params.get('del'))||TASKS[0],phase=0;
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(data));}catch{storageOK=false;}const el=root.querySelector('#guide-storage');if(el)el.innerHTML=storageOK?'Svaren sparas bara i den här webbläsaren. Skicka dem till läraren med QR-koden på sidan <a href="../vecka-40/aktuell/Resultat.html">Skicka resultat</a>.':'Lagring är blockerad. Spara som PDF eller CSV innan du lämnar sidan.';};
 const row=()=>data.rows[task.id]||{};
 // Förutsägelsen stämmer inom 2 % (samma tolerans som kursens facit), eller inom 0,01 nära noll.
 const stammer=(v,p)=>Math.abs(v-p)<=Math.max(0.02*Math.abs(v),0.01);
 const ready=()=>task.fields.every(([k])=>Number.isFinite(row().predicted?.[k]));
 // Återuppta den sparade uppgiften utan att skriva över en tidigare förklaring.
 phase=row().measured&&ready()?2:0;
 // Vilket instrument och vilken rad på bänken som visar varje storhet (instrumentens id och radordning i equipment-state.mjs).
 const KALLA={trms:['trms',0],avg:['avg',0],T:['scope',0],peak:['scope',1],XL:['load',3],Z:['load',4],I:t=>t.lesson==='effekt'?['power',0]:['trms',0]};
 function kalla(eq,k){const s=typeof KALLA[k]==='function'?KALLA[k](task):KALLA[k],inst=s&&eq?.instruments?.find(i=>i.id===s[0]);return inst?{name:inst.name,label:inst.rows[s[1]]?.[1]||''}:{name:'Simulerad avläsning',label:''};}
 const forklarad=r=>Boolean(r?.explanation?.trim());
 // Dubbeltryck: efter varje stegbyte ignoreras tryck en kort stund, så att ett andra tryck inte träffar knappen som just dök upp under fingret.
 // Tangentbordet (click med detail 0) påverkas inte.
 let guardUntil=0;const now=()=>globalThis.performance?.now?.()??Date.now();
 root.addEventListener('click',e=>{if(e.detail>0&&now()<guardUntil&&e.target.closest?.('button,a,summary')){e.preventDefault();e.stopImmediatePropagation();}},true);
 // Ett statusfält som aldrig byggs om, så att skärmläsaren läser upp ”sparad”.
 let live=document.getElementById('guide-live');if(!live){live=document.createElement('p');live.id='guide-live';live.className='sr-only';live.setAttribute('role','status');root.after(live);}
 const announce=t=>{live.textContent='';setTimeout(()=>{live.textContent=t;},120);};
 const STEG=['Förutsäg','Läs av och jämför','Förklara'];
 // Fokus flyttas bara när eleven själv har gjort något (render(true)), aldrig vid laddning.
 function focusStep(){const el=root.querySelector('#guide-steg');if(!el)return;el.focus?.({preventScroll:true});
  const wide=window.matchMedia?.('(min-width:1100px)')?.matches;
  if(wide&&typeof window.innerHeight==='number'&&el.getBoundingClientRect){const top=el.getBoundingClientRect().top;if(top>=0&&top<=window.innerHeight*0.6)return;}
  el.scrollIntoView?.({block:'start',behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches?'auto':'smooth'});}
 function setTask(id,fromUser=true){task=TASKS.find(t=>t.id===id)||TASKS[0];phase=row().measured&&ready()?2:0;render(fromUser);}
 function nextInfo(){const next=TASKS[TASKS.indexOf(task)+1];if(!next)return {next:null,label:'Visa hela grundprotokollet'};
  if(next.lesson===task.lesson)return {next,label:`Nästa uppgift: ${m(next.title)}`};const L=LESSONS.find(l=>l.id===next.lesson);return {next,label:L?`Nästa del: ${L.number+1}. ${m(L.title)}`:`Nästa uppgift: ${m(next.title)}`};}
 function render(fromUser=false){
  guardUntil=now()+600;
  const eq=publishEquipment({tab:task.lesson,values:task.setup,locked:phase===0,editable:false,taskId:task.id});
  const lesson=LESSONS.find(l=>l.id===task.lesson),r=row(),items=TASKS.filter(t=>t.lesson===task.lesson),saved=phase===2&&forklarad(r);
  const suffix=t=>{const x=data.rows[t.id];return forklarad(x)?' · Förklarad':x?.measured?' · Avläst':'';};
  const klart=i=>i<phase||(i===2&&saved);
  root.innerHTML=`<p class="guide-elev guide-d">Ditt tal: <strong>D = ${data.D}</strong>, samma som på inlämningssidan. Labben räknar fram dina värden ur D och skriver dem i varje uppgift. Du sätter inte in D själv.</p><div class="guide-pickers"><label>Del<select id="guide-lesson">${LESSONS.map(l=>`<option value="${l.id}"${l.id===lesson.id?' selected':''}>Del ${l.number+1}: ${l.title}</option>`).join('')}</select></label><label>Uppgift<select id="guide-task">${items.map(t=>`<option value="${t.id}"${t.id===task.id?' selected':''}>${m(t.title)}${suffix(t)}</option>`).join('')}</select></label></div>
  <p class="guide-label">Uppgift ${items.indexOf(task)+1} av ${items.length} i del ${lesson.number+1}</p><h2>${m(task.title)}</h2><p class="guide-source">${m(task.source)}</p>
  <p class="guide-steg" id="guide-steg" tabindex="-1">Steg ${phase+1} av 3: ${STEG[phase]}</p>
  <ol class="guide-progress" aria-label="Arbetsgång">${STEG.map((t,i)=>`<li${i===phase?' aria-current="step"':''}${klart(i)?' class="klart"':''}>${i+1}. ${t}${klart(i)?' – klart':''}</li>`).join('')}</ol>
  <div id="guide-step"></div>
  <p class="guide-support">${las(task)}</p>
  <details id="guide-protocol"><summary>Mitt grundprotokoll · ${TASKS.filter(t=>forklarad(data.rows[t.id])).length} av ${TASKS.length} uppgifter antecknade</summary><p class="guide-elev">Ditt tal: <strong>D = ${data.D}</strong> · dina värden räknas ur D <button id="guide-byt" type="button">Jag har ett annat D</button></p><div class="guide-actions"><a class="guide-skicka" href="../vecka-40/aktuell/Resultat.html">Skicka resultat (QR-kod)</a><button id="guide-print" type="button">Skriv ut / spara som PDF</button><button id="guide-csv" type="button">Ladda ner CSV</button></div><p>Antecknade svar är underlag för lärarens bedömning. De är inte ett automatiskt godkännande.</p><div id="guide-records">${protocolHTML()}</div></details><p id="guide-storage" class="muted"></p>`;
  const step=root.querySelector('#guide-step');
  if(phase===0){
   step.innerHTML=`<p class="guide-prompt">${m(task.prompt)}</p><details><summary>Visa metod och exempel</summary><p>${m(task.method)}</p></details>${hjalpHtml([task.prompt,task.method,task.source].join(' '))}<form id="guide-predict" novalidate><div class="guide-inputs">${task.fields.map(([k,l,u])=>{const q=kalla(eq,k);return `<div class="guide-pair"><div class="guide-own"><p class="guide-pair-head">Min förutsägelse</p><label>${m(l)} (${u})<input name="${k}" inputmode="decimal" autocomplete="off" value="${Number.isFinite(r.predicted?.[k])?esc(n(r.predicted[k])):''}" aria-label="Min förutsägelse, ${esc(markText(l))}, i ${u}"></label></div><div class="guide-reading"><p>${/beräknat/.test(q.label)?'Simulatorns värde på':'Visas på'} <strong>${m(q.name)}</strong>${q.label?` · ${m(q.label)}`:''}</p><p class="guide-lcd" aria-label="Dolt">?</p><p class="guide-lock">Värdet visas när du har sparat.</p></div></div>`;}).join('')}</div><p id="guide-error" role="alert"></p><button class="primary" type="submit">Spara förutsägelsen och läs av</button></form>`;
   step.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const form=e.target,predicted={};const fel=(input,text)=>{const err=step.querySelector('#guide-error');err.textContent=text;input.closest('label')?.after(err);input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby','guide-error');input.focus?.();};
    for(const el of form.querySelectorAll('input')){el.removeAttribute('aria-invalid');el.removeAttribute('aria-describedby');}
    for(const [k,l,u]of task.fields){const input=form.elements[k],raw=String(input.value).trim();if(!raw){fel(input,`Skriv din förutsägelse i fältet ${markText(l)} (${u}).`);return;}
     predicted[k]=parseGuideNumber(raw);if(!Number.isFinite(predicted[k])||predicted[k]<0){fel(input,`${markText(l)}: Skriv ett positivt tal eller noll i den angivna enheten. Både komma och punkt går bra.`);return;}}
    const g=data.rows[task.id],nu=new Date().toISOString();data.rows[task.id]={first:g?.first||predicted,firstAt:g?.firstAt||nu,predicted,attempts:(g?.attempts||0)+1,measured:true,readAt:nu,explanation:''};save();phase=1;render(true);});
  }else if(phase===1){const values=guideValues(task);const alla=task.fields.every(([k])=>stammer(values[k],r.predicted[k]));
   step.innerHTML=`<p class="guide-verdict ${alla?'ok':'fel'}">${alla?(task.fields.length>1?'✓ Rätt! Alla dina förutsägelser stämmer med avläsningarna.':'✓ Rätt! Din förutsägelse stämmer med avläsningen.'):(task.fields.length>1?'! Minst en förutsägelse skiljer sig från värdet. Kontrollera metod och enheter, eller ändra din beräkning.':'! Din förutsägelse skiljer sig från värdet. Kontrollera metod och enheter, eller ändra din beräkning.')}</p><p>Avläsningarna är simulerade.</p><dl class="guide-measurements">${task.fields.map(([k,l,u])=>{const ok=stammer(values[k],r.predicted[k]),q=kalla(eq,k),calc=/beräknat/.test(q.label),ord=calc?'beräknat':'avläst';const same=markText(l).toLowerCase().startsWith(markText(q.name).toLowerCase());return `<div class="guide-pair"><dt>${m(l)}${same?'':` · ${m(q.name)}`}</dt><dd><div class="guide-reading"><span>${calc?'Beräknat av simulatorn':'Avläst'}</span><strong class="guide-lcd">${n(values[k])} ${u}</strong></div><div class="guide-own"><span>Din förutsägelse: ${n(r.predicted[k])} ${u}</span><span>Skillnad (${ord} − din): ${n(values[k]-r.predicted[k])} ${u}</span><span class="guide-dom ${ok?'ok':'fel'}">${ok?'Stämmer.':'Skiljer sig.'}</span></div></dd></div>`;}).join('')}</dl><div class="guide-visual"></div>${task.id==='grund-topp'?`<p>Multimetern visar samtidigt <strong>${n(task.setup.urms)} V RMS</strong>. Kurvan visar spänningen vid olika tidpunkter.</p>`:''}${r.attempts>1?`<p class="muted">Du har ändrat förutsägelsen ${r.attempts-1} gång${r.attempts>2?'er':''}. Protokollet visar både din första och din senaste förutsägelse.</p>`:''}<div class="guide-actions"><button id="guide-explain" class="primary" type="button">Förklara resultatet</button><button id="guide-revise" type="button">Ändra min beräkning</button></div><p class="guide-bench-link"><a class="guide-to-bench" href="#equipment-bench">Se värdet på labbänken</a></p>`;
   step.querySelector('#guide-revise').onclick=()=>{phase=0;render(true);root.querySelector('#guide-predict input')?.focus?.({preventScroll:true});};step.querySelector('#guide-explain').onclick=()=>{phase=2;render(true);};
   step.querySelector('.guide-to-bench').onclick=e=>{const b=document.getElementById('equipment-bench'),t=b?.querySelector('.equipment-title');if(!t)return;e.preventDefault();b.scrollIntoView?.({block:'start'});t.focus?.({preventScroll:true});};draw();
  }else{const nx=nextInfo();
   step.innerHTML=`<p class="guide-prompt">${m(task.explain)}</p><p class="muted">${m(task.hint)}</p><form id="guide-explanation" novalidate><label>Min förklaring<textarea name="explanation" rows="4">${esc(r.explanation)}</textarea></label><p id="guide-draft" class="muted" aria-live="polite"></p><p id="guide-error" role="alert"></p><div class="guide-actions"><button id="guide-save" type="submit"${saved?' hidden':' class="primary"'}>${saved?'Spara ändringen':'Spara förklaringen'}</button><button id="guide-measure-again" type="button">Se avläsningen igen</button></div></form><p id="guide-saved">${saved?'Klart. Förklaringen är sparad som underlag. Läraren bedömer din metod och förståelse.':''}</p><button id="guide-next" class="primary" type="button"${saved?'':' hidden'}>${nx.label}</button>`;
   step.querySelector('#guide-measure-again').onclick=()=>{phase=1;render(true);};const form=step.querySelector('form'),draft=step.querySelector('#guide-draft');let timer=0;
   form.elements.explanation.addEventListener('input',e=>{if(saved)step.querySelector('#guide-save').hidden=false;data.rows[task.id]={...row(),explanation:e.target.value};save();clearTimeout(timer);timer=setTimeout(()=>{draft.textContent='Utkast sparat i den här webbläsaren.';},600);});
   form.onsubmit=e=>{e.preventDefault();const box=form.elements.explanation,explanation=box.value.trim();if(!explanation){step.querySelector('#guide-error').textContent='Skriv din förklaring med egna ord.';box.setAttribute('aria-invalid','true');box.setAttribute('aria-describedby','guide-error');box.focus?.();return;}box.removeAttribute('aria-invalid');box.removeAttribute('aria-describedby');clearTimeout(timer);data.rows[task.id]={...row(),explanation,explainedAt:new Date().toISOString()};save();render(false);root.querySelector('#guide-next')?.focus?.();announce('Förklaringen är sparad.');};
   step.querySelector('#guide-next').onclick=()=>{if(nx.next){setTask(nx.next.id);return;}const d=root.querySelector('#guide-protocol');d.open=true;d.querySelector('summary')?.focus?.();};}
  root.querySelector('#guide-lesson').onchange=e=>{setTask(GUIDE_TASKS.find(t=>t.lesson===e.target.value).id,false);root.querySelector('#guide-lesson')?.focus?.({preventScroll:true});};root.querySelector('#guide-task').onchange=e=>{setTask(e.target.value,false);root.querySelector('#guide-task')?.focus?.({preventScroll:true});};root.querySelector('#guide-byt').onclick=()=>{const svar=prompt('Har du börjat på en annan dator eller telefon? Skriv D därifrån (1–31).',String(data.D));if(svar===null||Number(svar)===data.D)return;if(!sattMittD(svar)){alert('D ska vara ett heltal från 1 till 31.');return;}if(Object.keys(data.rows).length&&!confirm('Dina värden räknas ur D. Med ett nytt D töms protokollet på den här enheten och du börjar om. Fortsätta?')){sattMittD(data.D);return;}data={version:GUIDE_VERSION,D:Number(svar),rows:{}};TASKS=GUIDE_TASKS.map(t=>personligUppgift(t,data.D));task=TASKS.find(t=>t.id===task.id)||TASKS[0];phase=0;save();render();};
  root.querySelector('#guide-print').onclick=()=>{root.querySelector('#guide-protocol').open=true;document.body.dataset.printMode='guide';window.print();};root.querySelector('#guide-csv').onclick=downloadCSV;
  save();const url=new URL(location.href);url.searchParams.set('lage','guidad');url.searchParams.set('del',task.lesson);url.searchParams.set('steg',task.id);url.searchParams.delete('flik');url.searchParams.delete('uppgift');history.replaceState(null,'',url);
  if(fromUser)focusStep();
 }
 function protocolHTML(){return `<p class="guide-elev">Namn: <strong>${esc(sparatNamn())||'_______________________'}</strong> · D = ${data.D} · utskrivet ${tid(new Date().toISOString())}</p>`+TASKS.map(t=>{const r=data.rows[t.id]||{},v=guideValues(t),forsta=r.first||r.predicted;return `<section class="guide-record"><h3>${m(t.title)}</h3><p>${m(t.source)}</p>${t.fields.map(([k,l,u])=>`<dl><dt>${m(l)}</dt><dd>Första förutsägelse: ${Number.isFinite(forsta?.[k])?n(forsta[k])+' '+u+(r.firstAt?` (${tid(r.firstAt)})`:''):'Inte angivet'}</dd>${r.attempts>1&&Number.isFinite(r.predicted?.[k])?`<dd>Senaste förutsägelse: ${n(r.predicted[k])} ${u} (försök ${r.attempts})</dd>`:''}<dd>Simulerad avläsning: ${r.measured?n(v[k])+' '+u+(r.readAt?` (${tid(r.readAt)})`:''):'Inte avläst'}</dd>${r.measured&&Number.isFinite(forsta?.[k])?`<dd>Skillnad (avläst − första): ${n(v[k]-forsta[k])} ${u} · ${stammer(v[k],forsta[k])?'första förutsägelsen stämde':'första förutsägelsen skilde sig'}</dd>`:''}</dl>`).join('')}<p><strong>Min förklaring:</strong> ${esc(r.explanation||'Inte antecknad')}${r.explainedAt?` <span class="muted">(${tid(r.explainedAt)})</span>`:''}</p></section>`;}).join('');}
 function downloadCSV(){const cell=s=>'"'+String(s??'').replace(/^(\s*[=+@-])/g,"'$1").replaceAll('"','""')+'"';const lines=[['Namn',sparatNamn()],['D',data.D],['Typ','Guidad AC-labb, ideal simulering'],['Uppgift','Storhet','Enhet','Första förutsägelse','Tid första','Senaste förutsägelse','Antal försök','Avläst','Avläst minus första','Första stämde','Förklaring','Tid förklaring']];for(const t of TASKS){const r=data.rows[t.id]||{},v=guideValues(t),forsta=r.first||r.predicted;for(const[k,l,u]of t.fields)lines.push([markText(t.title),markText(l),u,Number.isFinite(forsta?.[k])?n(forsta[k]):'',tid(r.firstAt),Number.isFinite(r.predicted?.[k])?n(r.predicted[k]):'',r.attempts||'',r.measured?n(v[k]):'',r.measured&&Number.isFinite(forsta?.[k])?n(v[k]-forsta[k]):'',r.measured&&Number.isFinite(forsta?.[k])?(stammer(v[k],forsta[k])?'ja':'nej'):'',r.explanation||'',tid(r.explainedAt)]);}const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`V40_Grundprotokoll_AC_${(sparatNamn()||'D'+data.D).replace(/[^\wÅÄÖåäö]+/g,'_')}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function draw(){const el=root.querySelector('.guide-visual');if(el)el.innerHTML=visual(task.visual,el.clientWidth);}
 new ResizeObserver(draw).observe(root);render(false);return {refresh(){render(false);}};
}
