// Answer fields are separate from instrument state: a reading cannot pass a prediction.
export function numericAnswer(value) {
  const text=String(value??'').trim().replace(',', '.');
  return /^[-+]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(text) ? Number(text) : NaN;
}
export function acceptsAnswer(step, answer={}) {
  if(step.kind==='number') return Math.abs(numericAnswer(answer.value)-step.answer)<=step.tolerance;
  if(step.choices) return answer.choice===step.correct && (!step.comment || String(answer.comment||'').trim().split(/\s+/).filter(Boolean).length>=3 && String(answer.comment||'').trim().length>=12);
  return false;
}
const loadingReading=(input,expected)=>(s,m)=>s.circuit==='divider'&&s.mode==='dc'&&s.jack==='v'&&s.power&&!s.trip&&s.input===input&&
  ['M','G'].includes(s.red)&&['M','G'].includes(s.black)&&s.red!==s.black&&m.code==='reading'&&m.unit==='V ⎓'&&Math.abs(Math.abs(m.value)-expected)<.01;

export const LESSONS = [
  {id:'voltage',title:'Spänning',circuit:'lamp',slides:'10–16',goal:'Mät spänningen över hyttlampan.',steps:[
    {task:'Välj V ⎓ och uttaget V Ω. Anslut svart till P2 och röd till P1. Slå på 12 V och läs av.',hint:'En voltmeter kopplas parallellt med lasten. Svart spets är referensen. Förväntat värde är 12,00 V.',test:(s,m)=>s.mode==='dc'&&s.jack==='v'&&s.red==='P1'&&s.black==='P2'&&s.power&&s.link&&Math.abs(m.value-12)<.01,why:'Rätt: mätaren ligger parallellt med lampan. Dess höga ingångsresistans gör att nästan ingen extra ström tas från kretsen.'}]},
  {id:'polarity',title:'Polaritet',circuit:'lamp',slides:'15–16',goal:'Ta reda på vad ett minustecken betyder.',steps:[
    {task:'Mät över lampan med svart på P1 och röd på P2. Använd V ⎓ och slå på 12 V.',hint:'Displayen visar potentialen vid röd spets minus potentialen vid svart. Om spetsarna byter plats byter värdet tecken.',test:(s,m)=>s.mode==='dc'&&s.jack==='v'&&s.red==='P2'&&s.black==='P1'&&s.power&&Math.abs(m.value+12)<.01,why:'−12,00 V betyder omvänd polaritet. Spänningens belopp är fortfarande 12 V.'}]},
  {id:'current',title:'Ström i serie',circuit:'lamp',slides:'17–23, 66',goal:'Låt lampans ström gå genom multimetern.',steps:[
    {task:'Med matningen bruten: öppna länken K1–K2. Välj A ⎓ och A-uttaget. Anslut röd till K1 och svart till K2. Slå på och läs av.',hint:'Kretsen måste öppnas. Mätaren ersätter länken, så samma ström går genom mätare och lampa. Cirka 0,100 A förväntas.',test:(s,m)=>s.mode==='current'&&s.jack==='a'&&!s.link&&s.red==='K1'&&s.black==='K2'&&s.power&&m.value>.099&&m.value<.101,why:'Rätt: mätaren sitter i serie. I = 12 / (120 + 0,1) ≈ 0,100 A. Shunten ger ett litet extra spänningsfall.'},
    {task:'Avsluta mätningen: bryt matningen, lossa båda mätspetsarna och flytta röd sladd tillbaka till V Ω.',hint:'Ett kvarlämnat A-uttag kan orsaka kortslutning vid nästa spänningsmätning.',test:s=>!s.power&&!s.red&&!s.black&&s.jack==='v',why:'Rätt avslut: matningen är bruten, spetsarna lossade och röd sladd tillbaka i V Ω.'}]},
  {id:'resistance',title:'Resistans',circuit:'resistor',slides:'24–26',goal:'Mät en frikopplad resistors resistans.',setup:{parallel:false},steps:[
    {task:'Välj Ω och V Ω-uttaget. Anslut spetsarna till A och B på den frikopplade resistorn R1.',hint:'En ohmmeter skickar en liten testström. Komponenten ska vara spänningslös och utan andra parallella strömvägar.',test:(s,m)=>s.mode==='ohm'&&s.jack==='v'&&s.red!==s.black&&Math.abs(m.value-1)<.001&&!s.parallel,why:'1,000 kΩ = 1 000 Ω. Mätaren använder sin egen testström; någon extern matning behövs inte.'}]},
  {id:'parallel',title:'Parallella vägar',circuit:'resistor',slides:'30–32',goal:'Förklara varför en 1 kΩ-resistor kan ge 500 Ω.',steps:[
    {task:'Mät mellan A och B i Ω-läge med båda 1 kΩ-resistorerna inkopplade.',hint:'Mätaren ser båda strömvägarna: 1/R = 1/1000 + 1/1000.',test:(s,m)=>s.mode==='ohm'&&s.parallel&&m.value===500,why:'500 Ω är korrekt för två 1 kΩ-resistorer parallellt. Det betyder inte att R1 är trasig.'},
    {task:'Frikoppla R2 med knappen vid kretsen. Mät sedan R1 igen.',hint:'När den parallella vägen försvinner ska värdet stiga till 1,000 kΩ.',test:(s,m)=>s.mode==='ohm'&&!s.parallel&&m.value===1,why:'Nu mäter du bara R1: 1,000 kΩ. Frikoppla en komponent vid behov för att undvika parallella strömvägar.'}]},
  {id:'continuity',title:'Kontinuitet',circuit:'fuse',slides:'27–29',goal:'Skilj en hel säkring från ett avbrott.',steps:[
    {task:'Välj Summer och V Ω-uttaget. Anslut spetsarna till A och B på den urtagna, hela säkringen.',hint:'En hel säkring har mycket låg resistans. Summern ger en synlig signal; ljud kan slås på under displayen.',test:(s,m)=>s.mode==='continuity'&&!s.broken&&m.beep&&s.red!==s.black,why:'0,2 Ω och kontaktsignal visar en sammanhängande ledande väg. En summer är inte en provare för spänningslöshet.'},
    {task:'Välj ”Simulera avbrott” och kontrollera säkringen igen.',hint:'OL betyder här öppen krets, inte noll ohm.',test:(s,m)=>s.mode==='continuity'&&s.broken&&s.red!==s.black&&m.code==='open',why:'OL och ingen ton visar avbrott. Säkringen är bortkopplad från spänningskällor under hela övningen.'}]},
  {id:'loading',title:'Mätaren påverkar',revision:2,setup:{power:true},circuit:'divider',slides:'55–63',goal:'Upptäck varför en voltmeter kan sänka spänningen den mäter. Förutsäg → mät → förklara.',steps:[
    {key:'unloaded',kind:'number',label:'Förutsäg utan mätare',task:'R1 och R2 är båda 1 MΩ (en miljon ohm). De delar på källans 10 V. Hur stor är spänningen mellan M och G innan mätaren ansluts?',answer:5,tolerance:.01,unit:'V',hint:'R1 och R2 är lika stora. Varje resistor får hälften av källans 10 V.',why:'5,00 V. Det är det beräknade värdet utan ansluten mätare. Nu ska vi se om mätaren förändrar kretsen.'},
    {key:'predict10',kind:'choice',label:'Förutsäg med 10 MΩ',task:'Mätarens ingång är en extra strömväg mellan M och G. Vad tror du händer med spänningen när en mätare med 10 MΩ ansluts?',choices:['Den blir lite lägre än 5 V','Den blir högre än 5 V','Den blir exakt 5 V'],correct:0,hint:'Mätaren hamnar parallellt med R2. Den sammanlagda resistansen i den nedre delen blir lite mindre.',why:'Spänningen blir lite lägre. Även en voltmeter tar en liten ström. Mät nu och jämför med dina 5,00 V.'},
    {key:'measure10',kind:'measurement',label:'Mät med 10 MΩ',task:'Mät mellan M och G. Följ kopplingshjälpen och kontrollera sedan avläsningen.',input:10e6,hint:'Välj V ⎓ och V Ω. Sätt svart på G och röd på M. Välj 10 MΩ och slå på 10 V. Omvända spetsar går också bra: jämför beloppet.',test:loadingReading(10e6,100/21),why:'Cirka 4,76 V, alltså lite under 5,00 V. Den streckade grenen är mätarens ingångsresistans, parallellt med R2.'},
    {key:'predict1',kind:'choice',label:'Förutsäg med 1 MΩ',task:'Nästa mätare har lägre ingångsresistans: 1 MΩ. Vad händer med spänningens belopp om spetsarna sitter kvar?',choices:['Det blir lägre än med 10 MΩ','Det blir högre än med 10 MΩ','Det ändras inte'],correct:0,hint:'Lägre ingångsresistans ger mer ström i mätarens gren. R2 och mätaren är nu två lika stora resistanser parallellt.',why:'Beloppet blir ännu lägre. En lägre ingångsresistans påverkar den här kretsen mer.'},
    {key:'measure1',kind:'measurement',label:'Mät med 1 MΩ',task:'Låt spetsarna sitta kvar på M och G. Ändra simulerad ingångsresistans till 1 MΩ. Läs av och jämför.',input:1e6,hint:'Ändra endast väljaren ”Simulerad ingångsresistans” under schemat. Behåll V ⎓, V Ω och matningen till.',test:loadingReading(1e6,10/3),why:'Cirka 3,33 V. R2 och mätaren ger tillsammans 500 kΩ. Spänningen sjunker därför mer. Det är belastning från mätaren, inte en trasig resistor.'},
    {key:'kirchhoff',kind:'number',label:'Kontrollera summan',task:'Behåll mätaren över R2. Källan ger 10,00 V och den nedre delen har 3,33 V. Beräkna spänningsfallet över R1: 10,00 − 3,33 = ?',answer:20/3,tolerance:.02,unit:'V',hint:'Spänningsfallen i samma krets summeras till källspänningen. Flytta inte mätaren: då belastas en annan del av kretsen.',why:'6,67 V över R1 + 3,33 V över R2 = 10,00 V. Källans spänning är oförändrad. Värdet över R1 är beräknat för den här kopplingen, inte uppmätt med en flyttad mätare.'},
    {key:'explain',kind:'choice',label:'Förklara med egna ord',task:'Varför är 3,33 V inte ett tecken på att spänningsdelaren är trasig? Välj förklaring och skriv sedan en egen mening i protokollet.',choices:['Mätaren är en extra gren parallellt med R2 och ändrar spänningsdelningen','Mätaren sänker alltid källans spänning till 3,33 V','Minustecknet gör att spänningens belopp blir mindre'],correct:0,comment:true,hint:'Beskriv var mätaren kopplas och hur den extra strömvägen påverkar delaren. Använd gärna orden parallellt, resistans och spänning.',why:'Mätaren är en gren i kretsen. Lägre ingångsresistans ger större påverkan här. Båda mätvärdena och din egen förklaring finns i protokollet. Läraren kan följa upp din formulering.'}
  ]},
  {id:'category',title:'Välj CAT-klass',circuit:'category',slides:'33–39',goal:'Bedöm mätplats, spänning och hela mätutrustningen.',steps:[
    {task:'Du ska mäta i en fördelningscentral (CAT III). Högsta relevanta spänning är 400 V. Vilket alternativ uppfyller båda kraven?',choices:['CAT II 1 000 V','CAT III 600 V','CAT III 300 V'],correct:1,hint:'Ett högt volt-tal ersätter inte rätt kategori.',why:'CAT III 600 V uppfyller både kategori och spänning. CAT II 1 000 V har ett högre volt-tal, men fel kategori för denna mätplats.'},
    {task:'Nästa mätplats är vid en lågspänningsanläggnings servisintag (CAT IV), 230 V mot jord. Vilken märkning är tillräcklig?',choices:['CAT III 1 000 V','CAT II 1 000 V','CAT IV 600 V'],correct:2,hint:'Välj kategori för var du mäter, och kontrollera sedan spänningsmärkningen.',why:'CAT IV 600 V passar den angivna CAT IV-miljön och spänningen. CAT III 1 000 V räcker inte här.'},
    {task:'Mätaren är CAT III 1 000 V. Sladdar och spetsar är bara CAT III 300 V. Får kombinationen användas vid 400 V mot jord i CAT III?',choices:['Ja, mätarens märkning avgör','Nej, sladdarnas gräns är för låg'],correct:1,hint:'Den svagaste delen begränsar hela mätuppställningen.',why:'Nej. Mätare, sladdar, spetsar och tillbehör måste alla passa mätplatsen och spänningen. Kontrollera även tillåtna spänningar mellan uttag.'},
    {task:'Kan en CAT II-mätare ha högre märkspänning än en CAT IV-mätare?',choices:['Ja, kategori och spänningsmärkning är två skilda krav','Nej, högre CAT måste alltid ha högre volt-tal','Ja, därför kan CAT II ersätta CAT IV'],correct:0,hint:'Till exempel CAT II 1 000 V och CAT IV 600 V. Läs alltid hela märkningen.',why:'Ja. CAT II 1 000 V och CAT IV 600 V kan båda finnas. En högre CAT måste inte ha lägre märkspänning; konstruktion och provning avgör vilka kombinationer instrumentet är godkänt för.'}]}
];
