export const LESSONS = [
  {id:'voltage',title:'Spänning',circuit:'lamp',slides:'10–16',goal:'Mät spänningen över hyttlampan.',steps:[
    {task:'Välj V ⎓ och uttaget V Ω. Anslut svart till P2 och röd till P1. Slå på 12 V och läs av.',hint:'En voltmeter kopplas parallellt med lasten. Svart spets är referensen. Förväntat värde är 12,00 V.',test:(s,m)=>s.mode==='dc'&&s.jack==='v'&&s.red==='P1'&&s.black==='P2'&&s.power&&s.link&&Math.abs(m.value-12)<.01,why:'Rätt: mätaren ligger parallellt med lampan. Dess höga ingångsresistans gör att nästan ingen extra ström tas från kretsen.'}]},
  {id:'polarity',title:'Polaritet',circuit:'lamp',slides:'15–16',goal:'Ta reda på vad ett minustecken betyder.',steps:[
    {task:'Mät över lampan med svart på P1 och röd på P2. Använd V ⎓ och slå på 12 V.',hint:'Displayen visar potentialen vid röd spets minus potentialen vid svart. Om spetsarna byter plats byter värdet tecken.',test:(s,m)=>s.mode==='dc'&&s.jack==='v'&&s.red==='P2'&&s.black==='P1'&&s.power&&Math.abs(m.value+12)<.01,why:'−12,00 V betyder omvänd polaritet. Spänningens belopp är fortfarande 12 V.'}]},
  {id:'current',title:'Ström i serie',circuit:'lamp',slides:'17–23, 66',goal:'Låt lampans ström gå genom multimetern.',steps:[
    {task:'Med matningen bruten: öppna länken K1–K2. Välj A ⎓ och A-uttaget. Anslut röd till K1 och svart till K2. Slå på och läs av.',hint:'Kretsen måste öppnas. Mätaren ersätter länken, så samma ström går genom mätare och lampa. Cirka 0,100 A förväntas.',test:(s,m)=>s.mode==='current'&&s.jack==='a'&&!s.link&&s.red==='K1'&&s.black==='K2'&&s.power&&m.value>.099&&m.value<.101,why:'Rätt: mätaren sitter i serie. I = 12 / (120 + 0,1) ≈ 0,100 A. Shunten ger ett litet extra spänningsfall.'},
    {task:'Avsluta mätningen: bryt matningen, lossa båda mätspetsarna och flytta röd sladd tillbaka till V Ω.',hint:'Ett kvarlämnat A-uttag kan orsaka kortslutning vid nästa spänningsmätning.',test:s=>!s.power&&!s.red&&!s.black&&s.jack==='v',why:'Rätt avslut: matningen är bruten, spetsarna lossade och röd sladd tillbaka i V Ω.'}]},
  {id:'resistance',title:'Resistans',circuit:'resistor',slides:'24–26',goal:'Mät en frikopplad resistors resistans.',setup:{parallel:false},steps:[
    {task:'Välj Ω och V Ω-uttaget. Anslut spetsarna till A och B på den frikopplade resistorn R1.',hint:'En ohmmeter skickar en liten testström. Komponenten ska vara spänningslös och utan andra parallella strömvägar.',test:(s,m)=>s.mode==='ohm'&&s.jack==='v'&&s.red!==s.black&&Math.abs(m.value-1)<.001&&!s.parallel,why:'1,000 kΩ = 1 000 Ω. Mätaren använder sin egen testström; någon extern matning behövs inte.'}]},
  {id:'parallel',title:'Parallella vägar',circuit:'resistor',slides:'30–32',goal:'Förklara varför en 1 kΩ-resistor kan ge 500 Ω.',steps:[
    {task:'Mät mellan A och B i Ω-läge med båda 1 kΩ-resistorerna inkopplade.',hint:'Mätaren ser båda strömvägarna: 1/R = 1/1000 + 1/1000.',test:(s,m)=>s.mode==='ohm'&&s.parallel&&m.value===500,why:'500 Ω är korrekt för två 1 kΩ-resistorer parallellt. Det betyder inte att R1 är trasig.'},
    {task:'Frikoppla R2 med knappen vid kretsen. Mät sedan R1 igen.',hint:'När den parallella vägen försvinner ska värdet stiga till 1,000 kΩ.',test:(s,m)=>s.mode==='ohm'&&!s.parallel&&m.value===1,why:'Nu mäter du bara R1: 1,000 kΩ. Frikoppla en komponent vid behov för att undvika parallella strömvägar.'}]},
  {id:'continuity',title:'Kontinuitet',circuit:'fuse',slides:'27–29',goal:'Skilj en hel säkring från ett avbrott.',steps:[
    {task:'Välj Summer och V Ω-uttaget. Anslut spetsarna till A och B på den urtagna, hela säkringen.',hint:'En hel säkring har mycket låg resistans. Summern ger en synlig signal; ljud kan slås på under displayen.',test:(s,m)=>s.mode==='continuity'&&!s.broken&&m.beep&&s.red!==s.black,why:'0,2 Ω och kontaktsignal visar en sammanhängande ledande väg. En summer är inte en provare för spänningslöshet.'},
    {task:'Välj ”Simulera avbrott” och kontrollera säkringen igen.',hint:'OL betyder här öppen krets, inte noll ohm.',test:(s,m)=>s.mode==='continuity'&&s.broken&&s.red!==s.black&&m.code==='open',why:'OL och ingen ton visar avbrott. Säkringen är bortkopplad från spänningskällor under hela övningen.'}]},
  {id:'loading',title:'Mätaren påverkar',circuit:'divider',slides:'55–63',goal:'Se hur ingångsresistansen ändrar spänningen.',steps:[
    {task:'Välj V ⎓ och 10 MΩ ingångsresistans. Anslut röd till M och svart till G. Slå på 10 V.',hint:'Utan mätare är mittpunktens spänning 5 V. Mätarens 10 MΩ ligger parallellt med R2.',test:(s,m)=>s.mode==='dc'&&s.red==='M'&&s.black==='G'&&s.power&&s.input===10e6&&Math.abs(m.value-100/21)<.001,why:'4,76 V: mätaren belastar spänningsdelaren. R2 parallellt med 10 MΩ blir cirka 909 kΩ.'},
    {task:'Byt ingångsresistans till 1 MΩ och jämför avläsningen.',hint:'R2 parallellt med 1 MΩ blir 500 kΩ. U = 10 × 0,5 / (1 + 0,5).',test:(s,m)=>s.mode==='dc'&&s.red==='M'&&s.black==='G'&&s.power&&s.input===1e6&&Math.abs(m.value-10/3)<.001,why:'3,33 V: lägre ingångsresistans ger större belastning. Avvikelsen från 5 V är cirka −33 %.'}]},
  {id:'category',title:'Välj CAT-klass',circuit:'category',slides:'33–39',goal:'Bedöm mätplats, spänning och hela mätutrustningen.',steps:[
    {task:'Du ska mäta i en fördelningscentral (CAT III). Högsta relevanta spänning är 400 V. Vilket alternativ uppfyller båda kraven?',choices:['CAT II 1 000 V','CAT III 600 V','CAT III 300 V'],correct:1,hint:'Ett högt volt-tal ersätter inte rätt kategori.',why:'CAT III 600 V uppfyller både kategori och spänning. CAT II 1 000 V har ett högre volt-tal, men fel kategori för denna mätplats.'},
    {task:'Nästa mätplats är vid en lågspänningsanläggnings servisintag (CAT IV), 230 V mot jord. Vilken märkning är tillräcklig?',choices:['CAT III 1 000 V','CAT II 1 000 V','CAT IV 600 V'],correct:2,hint:'Välj kategori för var du mäter, och kontrollera sedan spänningsmärkningen.',why:'CAT IV 600 V passar den angivna CAT IV-miljön och spänningen. CAT III 1 000 V räcker inte här.'},
    {task:'Mätaren är CAT III 1 000 V. Sladdar och spetsar är bara CAT III 300 V. Får kombinationen användas vid 400 V mot jord i CAT III?',choices:['Ja, mätarens märkning avgör','Nej, sladdarnas gräns är för låg'],correct:1,hint:'Den svagaste delen begränsar hela mätuppställningen.',why:'Nej. Mätare, sladdar, spetsar och tillbehör måste alla passa mätplatsen och spänningen. Kontrollera även tillåtna spänningar mellan uttag.'},
    {task:'Kan en CAT II-mätare ha högre märkspänning än en CAT IV-mätare?',choices:['Ja, kategori och spänningsmärkning är två skilda krav','Nej, högre CAT måste alltid ha högre volt-tal','Ja, därför kan CAT II ersätta CAT IV'],correct:0,hint:'Till exempel CAT II 1 000 V och CAT IV 600 V. Läs alltid hela märkningen.',why:'Ja. CAT II 1 000 V och CAT IV 600 V kan båda finnas. En högre CAT måste inte ha lägre märkspänning; konstruktion och provning avgör vilka kombinationer instrumentet är godkänt för.'}]}
];
