import {publishEquipment} from './equipment-state.mjs';
import {markHtml as m,markText} from '../gemensamt/markering.mjs?v=20260928';
import {GUIDE_TASKS,GUIDE_VERSION,guideValues,parseGuideNumber,personligUppgift,elevtal} from './guided-lessons.mjs?v=20260929b';
import {fulltNamn,sparatNamn,sparaNamn} from '../gemensamt/elevtal.mjs?v=20260929';
import {LESSONS} from '../vecka-40/aktuell/lektioner.mjs?v=20260929';
import {visual} from '../vecka-40/aktuell/visuals.mjs?v=20260929';
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const n=v=>v.toLocaleString('sv-SE',{minimumFractionDigits:2,maximumFractionDigits:2});
const KEY='sjoskolan-ac-grund-v3';
const tid=iso=>iso?new Date(iso).toLocaleString('sv-SE',{dateStyle:'short',timeStyle:'short'}):'';
// Läshänvisning: den bild i genomgången som förklarar metoden (del och bildnummer räknas ur lektionerna).
function las(task){const l=LESSONS.find(x=>x.id===task.lesson),i=l?l.slides.findIndex(x=>x.id===task.theory):-1;const href=`../vecka-40/aktuell/Genomgang.html?del=${task.lesson}&amp;avsnitt=${task.theory}`;
 return i<0?`<a href="${href}" target="_blank" rel="noopener">Läs motsvarande del av genomgången</a>`:`Kan du inte metoden? Läs genomgången <a href="${href}" target="_blank" rel="noopener">del ${l.number}, bild ${i+1}: ${m(l.slides[i].title)}</a> (öppnas i ny flik) och gör sedan uppgiften.`;}
export function mountGuide(root){
 let data={version:GUIDE_VERSION,name:'',D:null,rows:{}},storageOK=true;
 try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.version===GUIDE_VERSION&&s.rows&&typeof s.rows==='object'&&fulltNamn(s.name))data={version:GUIDE_VERSION,name:String(s.name),D:elevtal(s.name),rows:s.rows};}catch{storageOK=false;}
 // Uppgifterna med elevens egna värden (ur namnet). Utan namn visas bara namnrutan.
 let TASKS=GUIDE_TASKS.map(t=>personligUppgift(t,data.D));
 const params=new URLSearchParams(location.search);
 let task=TASKS.find(t=>t.id===params.get('steg'))||TASKS.find(t=>t.lesson===params.get('del'))||TASKS[0],phase=0;
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(data));}catch{storageOK=false;}const el=root.querySelector('#guide-storage');if(el)el.textContent=storageOK?'Svaren sparas bara i den här webbläsaren. Exportera protokollet före inlämning.':'Lagring är blockerad. Spara som PDF eller CSV innan du lämnar sidan.';};
 const row=()=>data.rows[task.id]||{};
 // Förutsägelsen stämmer inom 2 % (samma tolerans som kursens facit), eller inom 0,01 nära noll.
 const stammer=(v,p)=>Math.abs(v-p)<=Math.max(0.02*Math.abs(v),0.01);
 const ready=()=>task.fields.every(([k])=>Number.isFinite(row().predicted?.[k]));
 // Återuppta den sparade uppgiften utan att skriva över en tidigare förklaring.
 phase=row().measured&&ready()?2:0;
 function setTask(id){task=TASKS.find(t=>t.id===id)||TASKS[0];phase=row().measured&&ready()?2:0;render();}
 function namnruta(){
  publishEquipment({tab:task.lesson,values:GUIDE_TASKS.find(t=>t.id===task.id).setup,locked:true,editable:false,taskId:task.id});
  root.innerHTML=`<p class="guide-label">GUIDAD LABB</p><h2>Skriv ditt namn först</h2><p>Du får egna värden i labben. De räknas fram ur ditt namn, så skriv för- och efternamn på samma sätt som på inlämningen. Läraren räknar fram samma värden ur namnet och kan kontrollera dina svar.</p><form id="guide-namnform"><label>Förnamn och efternamn<input name="namn" autocomplete="name" required value="${esc(data.name||sparatNamn())}"></label><p id="guide-error" role="alert"></p><button class="primary" type="submit">Börja labben</button></form>`;
  root.querySelector('form').onsubmit=e=>{e.preventDefault();const namn=e.target.elements.namn.value.trim().replace(/\s+/g,' ');if(!fulltNamn(namn)){root.querySelector('#guide-error').textContent='Skriv både förnamn och efternamn.';return;}
   data={version:GUIDE_VERSION,name:namn,D:elevtal(namn),rows:{}};sparaNamn(namn);TASKS=GUIDE_TASKS.map(t=>personligUppgift(t,data.D));task=TASKS.find(t=>t.id===task.id)||TASKS[0];phase=0;save();render();};
 }
 function render(){
  if(!data.D)return namnruta();
  publishEquipment({tab:task.lesson,values:task.setup,locked:phase===0,editable:false,taskId:task.id});
  const lesson=LESSONS.find(l=>l.id===task.lesson),r=row(),items=TASKS.filter(t=>t.lesson===task.lesson);
  root.innerHTML=`<div class="guide-pickers"><label>Del<select id="guide-lesson">${LESSONS.map(l=>`<option value="${l.id}"${l.id===lesson.id?' selected':''}>${l.number}. ${l.title}</option>`).join('')}</select></label><label>Uppgift<select id="guide-task">${items.map(t=>`<option value="${t.id}"${t.id===task.id?' selected':''}>${m(t.title)}${data.rows[t.id]?.explanation?' · antecknad':''}</option>`).join('')}</select></label></div>
  <p class="guide-label">GUIDAD LABB · ${items.indexOf(task)+1} AV ${items.length} I DENNA DEL</p><h2>${m(task.title)}</h2><p class="guide-source">${m(task.source)}</p>
  <ol class="guide-progress" aria-label="Arbetsgång">${['Förutsäg','Läs av och jämför','Förklara'].map((t,i)=>`<li${i===phase?' aria-current="step"':''}>${i+1}. ${t}</li>`).join('')}</ol>
  <div id="guide-step"></div>
  <p class="guide-support">${las(task)}</p>
  <details id="guide-protocol"><summary>Mitt grundprotokoll · ${TASKS.filter(t=>data.rows[t.id]?.explanation).length} av ${TASKS.length} uppgifter antecknade</summary><p class="guide-elev">Namn: <strong>${esc(data.name)}</strong> · värdena räknade ur namnet (tal ${data.D}) <button id="guide-byt" type="button">Byt namn</button></p><div class="guide-actions"><button id="guide-print" type="button">Skriv ut / spara som PDF</button><button id="guide-csv" type="button">Ladda ner CSV</button></div><p>Antecknade svar är underlag för lärarens bedömning. De är inte ett automatiskt godkännande.</p><div id="guide-records">${protocolHTML()}</div></details><p id="guide-storage" class="muted"></p>`;
  const step=root.querySelector('#guide-step');
  if(phase===0){step.innerHTML=`<p class="guide-prompt">${m(task.prompt)}</p><details><summary>Visa metod och exempel</summary><p>${m(task.method)}</p></details><form id="guide-predict"><div class="guide-inputs">${task.fields.map(([k,l,u])=>`<label>${m(l)} (${u})<input name="${k}" inputmode="decimal" autocomplete="off" value="${Number.isFinite(r.predicted?.[k])?esc(n(r.predicted[k])):''}" required aria-label="Min förutsägelse, ${l}, i ${u}"></label>`).join('')}</div><p id="guide-error" role="alert"></p><button class="primary" type="submit">Spara förutsägelsen och läs av</button></form>`;
   step.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const predicted={};for(const [k]of task.fields){predicted[k]=parseGuideNumber(e.target.elements[k].value);if(!Number.isFinite(predicted[k])||predicted[k]<0){step.querySelector('#guide-error').textContent='Skriv ett positivt tal eller noll i den angivna enheten. Både komma och punkt går bra.';return;}}const g=data.rows[task.id],nu=new Date().toISOString();data.rows[task.id]={first:g?.first||predicted,firstAt:g?.firstAt||nu,predicted,attempts:(g?.attempts||0)+1,measured:true,readAt:nu,explanation:''};save();phase=1;render();});
  }else if(phase===1){const values=guideValues(task);step.innerHTML=`${(()=>{const alla=task.fields.every(([k])=>stammer(values[k],r.predicted[k]));return `<p class="guide-verdict ${alla?'ok':'fel'}">${alla?(task.fields.length>1?'Rätt! Alla dina förutsägelser stämmer med avläsningarna.':'Rätt! Din förutsägelse stämmer med avläsningen.'):'Minst en förutsägelse skiljer sig från avläsningen. Kontrollera metod och enheter, eller ändra din beräkning.'}</p>`;})()}<p>Avläsningarna är simulerade.</p><div class="guide-visual"></div><dl class="guide-measurements">${task.fields.map(([k,l,u])=>{const ok=stammer(values[k],r.predicted[k]);return `<div><dt>${m(l)}</dt><dd><span>Avläst</span><strong>${n(values[k])} ${u}</strong><span>Din förutsägelse: ${n(r.predicted[k])} ${u}</span><span>Skillnad (avläst − din): ${n(values[k]-r.predicted[k])} ${u}</span><span class="guide-dom ${ok?'ok':'fel'}">${ok?'Stämmer.':'Skiljer sig.'}</span></dd></div>`;}).join('')}</dl>${task.id==='grund-topp'?`<p>Multimetern visar samtidigt <strong>${n(task.setup.urms)} V RMS</strong>. Kurvan visar spänningen vid olika tidpunkter.</p>`:''}${r.attempts>1?`<p class="muted">Du har ändrat förutsägelsen ${r.attempts-1} gång${r.attempts>2?'er':''}. Protokollet visar både din första och din senaste förutsägelse.</p>`:''}<div class="guide-actions"><button id="guide-revise" type="button">Ändra min beräkning</button><button id="guide-explain" class="primary" type="button">Förklara resultatet</button></div>`;step.querySelector('#guide-revise').onclick=()=>{phase=0;render();};step.querySelector('#guide-explain').onclick=()=>{phase=2;render();};draw();
  }else{step.innerHTML=`<p class="guide-prompt">${m(task.explain)}</p><p class="muted">${m(task.hint)}</p><form id="guide-explanation"><label>Min förklaring<textarea name="explanation" rows="4" required>${esc(r.explanation)}</textarea></label><p id="guide-error" role="alert"></p><div class="guide-actions"><button id="guide-measure-again" type="button">Se avläsningen igen</button><button class="primary" type="submit">Spara förklaringen</button></div></form><p id="guide-saved" role="status" aria-live="polite"></p><button id="guide-next" type="button" hidden>Nästa uppgift</button>`;step.querySelector('#guide-measure-again').onclick=()=>{phase=1;render();};const form=step.querySelector('form');form.elements.explanation.addEventListener('input',e=>{data.rows[task.id]={...row(),explanation:e.target.value};save();});form.onsubmit=e=>{e.preventDefault();const explanation=form.elements.explanation.value.trim();if(!explanation){step.querySelector('#guide-error').textContent='Skriv din förklaring med egna ord.';return;}data.rows[task.id]={...row(),explanation,explainedAt:new Date().toISOString()};save();step.querySelector('#guide-saved').textContent='Förklaringen är sparad som underlag. Läraren bedömer din metod och förståelse.';root.querySelector('#guide-records').innerHTML=protocolHTML();root.querySelector('#guide-protocol summary').textContent=`Mitt grundprotokoll · ${TASKS.filter(t=>data.rows[t.id]?.explanation?.trim()).length} av ${TASKS.length} uppgifter antecknade`;const next=TASKS[TASKS.indexOf(task)+1];const b=step.querySelector('#guide-next');b.hidden=false;b.textContent=next?'Nästa uppgift':'Visa hela grundprotokollet';b.onclick=()=>next?setTask(next.id):(root.querySelector('#guide-protocol').open=true);};}
  root.querySelector('#guide-lesson').onchange=e=>setTask(GUIDE_TASKS.find(t=>t.lesson===e.target.value).id);root.querySelector('#guide-task').onchange=e=>setTask(e.target.value);root.querySelector('#guide-byt').onclick=()=>{if(Object.keys(data.rows).length&&!confirm('Värdena räknas ur namnet. Om du byter namn töms protokollet och du börjar om. Fortsätta?'))return;data={version:GUIDE_VERSION,name:'',D:null,rows:{}};save();render();};
  root.querySelector('#guide-print').onclick=()=>{root.querySelector('#guide-protocol').open=true;document.body.dataset.printMode='guide';window.print();};root.querySelector('#guide-csv').onclick=downloadCSV;
  save();const url=new URL(location.href);url.searchParams.set('lage','guidad');url.searchParams.set('del',task.lesson);url.searchParams.set('steg',task.id);url.searchParams.delete('flik');url.searchParams.delete('uppgift');history.replaceState(null,'',url);
 }
 function protocolHTML(){return `<p class="guide-elev">Namn: <strong>${esc(data.name)}</strong> · tal ${data.D} · utskrivet ${tid(new Date().toISOString())}</p>`+TASKS.map(t=>{const r=data.rows[t.id]||{},v=guideValues(t),forsta=r.first||r.predicted;return `<section class="guide-record"><h3>${m(t.title)}</h3><p>${m(t.source)}</p>${t.fields.map(([k,l,u])=>`<dl><dt>${m(l)}</dt><dd>Första förutsägelse: ${Number.isFinite(forsta?.[k])?n(forsta[k])+' '+u+(r.firstAt?` (${tid(r.firstAt)})`:''):'Inte angivet'}</dd>${r.attempts>1&&Number.isFinite(r.predicted?.[k])?`<dd>Senaste förutsägelse: ${n(r.predicted[k])} ${u} (försök ${r.attempts})</dd>`:''}<dd>Simulerad avläsning: ${r.measured?n(v[k])+' '+u+(r.readAt?` (${tid(r.readAt)})`:''):'Inte avläst'}</dd>${r.measured&&Number.isFinite(forsta?.[k])?`<dd>Skillnad (avläst − första): ${n(v[k]-forsta[k])} ${u} · ${stammer(v[k],forsta[k])?'första förutsägelsen stämde':'första förutsägelsen skilde sig'}</dd>`:''}</dl>`).join('')}<p><strong>Min förklaring:</strong> ${esc(r.explanation||'Inte antecknad')}${r.explainedAt?` <span class="muted">(${tid(r.explainedAt)})</span>`:''}</p></section>`;}).join('');}
 function downloadCSV(){const cell=s=>'"'+String(s??'').replace(/^(\s*[=+@-])/g,"'$1").replaceAll('"','""')+'"';const lines=[['Namn',data.name],['Tal ur namnet',data.D],['Typ','Guidad AC-labb, ideal simulering'],['Uppgift','Storhet','Enhet','Första förutsägelse','Tid första','Senaste förutsägelse','Antal försök','Avläst','Avläst minus första','Första stämde','Förklaring','Tid förklaring']];for(const t of TASKS){const r=data.rows[t.id]||{},v=guideValues(t),forsta=r.first||r.predicted;for(const[k,l,u]of t.fields)lines.push([markText(t.title),markText(l),u,Number.isFinite(forsta?.[k])?n(forsta[k]):'',tid(r.firstAt),Number.isFinite(r.predicted?.[k])?n(r.predicted[k]):'',r.attempts||'',r.measured?n(v[k]):'',r.measured&&Number.isFinite(forsta?.[k])?n(v[k]-forsta[k]):'',r.measured&&Number.isFinite(forsta?.[k])?(stammer(v[k],forsta[k])?'ja':'nej'):'',r.explanation||'',tid(r.explainedAt)]);}const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`V40_Grundprotokoll_AC_${data.name.replace(/[^\wÅÄÖåäö]+/g,'_')}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function draw(){const el=root.querySelector('.guide-visual');if(el)el.innerHTML=visual(task.visual,el.clientWidth);}
 new ResizeObserver(draw).observe(root);render();return {refresh(){render();}};
}
