import {publishEquipment} from './equipment-state.mjs';
import {markHtml as m,markText} from '../gemensamt/markering.mjs?v=20260928';
import {GUIDE_TASKS,GUIDE_VERSION,guideValues,parseGuideNumber} from './guided-lessons.mjs?v=20260925-ac2';
import {LESSONS} from '../vecka-40/aktuell/lektioner.mjs?v=20260928';
import {visual} from '../vecka-40/aktuell/visuals.mjs?v=20260928';
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const n=v=>v.toLocaleString('sv-SE',{minimumFractionDigits:2,maximumFractionDigits:2});
const KEY='sjoskolan-ac-grund-v2';
export function mountGuide(root){
 let data={version:GUIDE_VERSION,name:'',rows:{}},storageOK=true;
 try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.version===GUIDE_VERSION&&s.rows&&typeof s.rows==='object')data={version:GUIDE_VERSION,name:String(s.name||''),rows:s.rows};}catch{storageOK=false;}
 const params=new URLSearchParams(location.search);
 let task=GUIDE_TASKS.find(t=>t.id===params.get('steg'))||GUIDE_TASKS.find(t=>t.lesson===params.get('del'))||GUIDE_TASKS[0],phase=0;
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(data));}catch{storageOK=false;}const el=root.querySelector('#guide-storage');if(el)el.textContent=storageOK?'Svaren sparas bara i den här webbläsaren. Exportera protokollet före inlämning.':'Lagring är blockerad. Spara som PDF eller CSV innan du lämnar sidan.';};
 const row=()=>data.rows[task.id]||{};
 const ready=()=>task.fields.every(([k])=>Number.isFinite(row().predicted?.[k]));
 function setTask(id){task=GUIDE_TASKS.find(t=>t.id===id)||GUIDE_TASKS[0];phase=row().measured&&ready()?2:0;render();}
 function render(){
  publishEquipment({tab:task.lesson,values:task.setup,locked:phase===0,editable:false,taskId:task.id});
  const lesson=LESSONS.find(l=>l.id===task.lesson),r=row(),items=GUIDE_TASKS.filter(t=>t.lesson===task.lesson);
  root.innerHTML=`<div class="guide-pickers"><label>Del<select id="guide-lesson">${LESSONS.map(l=>`<option value="${l.id}"${l.id===lesson.id?' selected':''}>${l.number}. ${l.title}</option>`).join('')}</select></label><label>Uppgift<select id="guide-task">${items.map(t=>`<option value="${t.id}"${t.id===task.id?' selected':''}>${m(t.title)}${data.rows[t.id]?.explanation?' · antecknad':''}</option>`).join('')}</select></label></div>
  <p class="guide-label">GUIDAD LABB · ${items.indexOf(task)+1} AV ${items.length} I DENNA DEL</p><h2>${m(task.title)}</h2><p class="guide-source">${m(task.source)}</p>
  <ol class="guide-progress" aria-label="Arbetsgång">${['Förutsäg','Läs av och jämför','Förklara'].map((t,i)=>`<li${i===phase?' aria-current="step"':''}>${i+1}. ${t}</li>`).join('')}</ol>
  <div id="guide-step"></div>
  <p class="guide-support"><a href="../vecka-40/aktuell/Genomgang.html?del=${task.lesson}&amp;avsnitt=${task.theory}" target="_blank" rel="noopener">Öppna motsvarande genomgång i ny flik</a></p>
  <details id="guide-protocol"><summary>Mitt grundprotokoll · ${GUIDE_TASKS.filter(t=>data.rows[t.id]?.explanation).length} av ${GUIDE_TASKS.length} uppgifter antecknade</summary><label>Namn<input id="guide-name" value="${esc(data.name)}" autocomplete="name"></label><div class="guide-actions"><button id="guide-print" type="button">Skriv ut / spara som PDF</button><button id="guide-csv" type="button">Ladda ner CSV</button></div><p>Antecknade svar är underlag för lärarens bedömning. De är inte ett automatiskt godkännande.</p><div id="guide-records">${protocolHTML()}</div></details><p id="guide-storage" class="muted"></p>`;
  const step=root.querySelector('#guide-step');
  if(phase===0){step.innerHTML=`<p class="guide-prompt">${m(task.prompt)}</p><details><summary>Visa metod och exempel</summary><p>${m(task.method)}</p></details><form id="guide-predict"><div class="guide-inputs">${task.fields.map(([k,l,u])=>`<label>${m(l)} (${u})<input name="${k}" inputmode="decimal" autocomplete="off" value="${Number.isFinite(r.predicted?.[k])?esc(n(r.predicted[k])):''}" required aria-label="Förväntat ${l} i ${u}"></label>`).join('')}</div><p id="guide-error" role="alert"></p><button class="primary" type="submit">Spara förutsägelsen och läs av</button></form>`;
   step.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const predicted={};for(const [k]of task.fields){predicted[k]=parseGuideNumber(e.target.elements[k].value);if(!Number.isFinite(predicted[k])||predicted[k]<0){step.querySelector('#guide-error').textContent='Skriv ett positivt tal eller noll i den angivna enheten. Både komma och punkt går bra.';return;}}data.rows[task.id]={predicted,measured:true,explanation:''};save();phase=1;render();});
  }else if(phase===1){const values=guideValues(task);step.innerHTML=`<p>Avläsningarna nedan är simulerade. Jämför dem med din egen förutsägelse.</p><div class="guide-visual"></div><dl class="guide-measurements">${task.fields.map(([k,l,u])=>`<div><dt>${m(l)}</dt><dd><strong>${n(values[k])} ${u}</strong><span>Förväntat: ${n(r.predicted[k])} ${u}</span><span>Avläst − förväntat: ${n(values[k]-r.predicted[k])} ${u}</span></dd></div>`).join('')}</dl>${task.id==='grund-topp'?'<p>Multimetern visar samtidigt <strong>12,00 V RMS</strong>. Kurvan visar spänningen vid olika tidpunkter.</p>':''}<p>Om värdena skiljer sig: kontrollera metod och enheter. Avrundning kan ge en liten skillnad.</p><div class="guide-actions"><button id="guide-revise" type="button">Ändra min beräkning</button><button id="guide-explain" class="primary" type="button">Förklara resultatet</button></div>`;step.querySelector('#guide-revise').onclick=()=>{phase=0;render();};step.querySelector('#guide-explain').onclick=()=>{phase=2;render();};draw();
  }else{step.innerHTML=`<p class="guide-prompt">${m(task.explain)}</p><p class="muted">${m(task.hint)}</p><form id="guide-explanation"><label>Min förklaring<textarea name="explanation" rows="4" required>${esc(r.explanation)}</textarea></label><p id="guide-error" role="alert"></p><div class="guide-actions"><button id="guide-measure-again" type="button">Se avläsningen igen</button><button class="primary" type="submit">Spara förklaringen</button></div></form><p id="guide-saved" role="status" aria-live="polite"></p><button id="guide-next" type="button" hidden>Nästa uppgift</button>`;step.querySelector('#guide-measure-again').onclick=()=>{phase=1;render();};const form=step.querySelector('form');form.elements.explanation.addEventListener('input',e=>{data.rows[task.id]={...row(),explanation:e.target.value};save();});form.onsubmit=e=>{e.preventDefault();const explanation=form.elements.explanation.value.trim();if(!explanation){step.querySelector('#guide-error').textContent='Skriv din förklaring med egna ord.';return;}data.rows[task.id]={...row(),explanation};save();step.querySelector('#guide-saved').textContent='Förklaringen är sparad som underlag. Läraren bedömer din metod och förståelse.';root.querySelector('#guide-records').innerHTML=protocolHTML();root.querySelector('#guide-protocol summary').textContent=`Mitt grundprotokoll · ${GUIDE_TASKS.filter(t=>data.rows[t.id]?.explanation?.trim()).length} av ${GUIDE_TASKS.length} uppgifter antecknade`;const next=GUIDE_TASKS[GUIDE_TASKS.indexOf(task)+1];const b=step.querySelector('#guide-next');b.hidden=false;b.textContent=next?'Nästa uppgift':'Visa hela grundprotokollet';b.onclick=()=>next?setTask(next.id):(root.querySelector('#guide-protocol').open=true);};}
  root.querySelector('#guide-lesson').onchange=e=>setTask(GUIDE_TASKS.find(t=>t.lesson===e.target.value).id);root.querySelector('#guide-task').onchange=e=>setTask(e.target.value);root.querySelector('#guide-name').oninput=e=>{data.name=e.target.value;save();};
  root.querySelector('#guide-print').onclick=()=>{root.querySelector('#guide-protocol').open=true;document.body.dataset.printMode='guide';window.print();};root.querySelector('#guide-csv').onclick=downloadCSV;
  save();const url=new URL(location.href);url.searchParams.set('lage','guidad');url.searchParams.set('del',task.lesson);url.searchParams.set('steg',task.id);url.searchParams.delete('flik');url.searchParams.delete('uppgift');history.replaceState(null,'',url);
 }
 function protocolHTML(){return GUIDE_TASKS.map(t=>{const r=data.rows[t.id]||{},v=guideValues(t);return `<section class="guide-record"><h3>${m(t.title)}</h3><p>${m(t.source)}</p>${t.fields.map(([k,l,u])=>`<dl><dt>${m(l)}</dt><dd>Förväntat: ${Number.isFinite(r.predicted?.[k])?n(r.predicted[k])+' '+u:'Inte angivet'}</dd><dd>Simulerad avläsning: ${r.measured?n(v[k])+' '+u:'Inte avläst'}</dd>${r.measured&&Number.isFinite(r.predicted?.[k])?`<dd>Avläst − förväntat: ${n(v[k]-r.predicted[k])} ${u}</dd>`:''}</dl>`).join('')}<p><strong>Min förklaring:</strong> ${esc(r.explanation||'Inte antecknad')}</p></section>`;}).join('');}
 function downloadCSV(){const cell=s=>'"'+String(s??'').replace(/^(\s*[=+@-])/g,"'$1").replaceAll('"','""')+'"';const lines=[['Namn',data.name],['Typ','Guidad AC-labb, ideal simulering'],['Uppgift','Storhet','Enhet','Förväntat','Avläst','Avläst minus förväntat','Förklaring']];for(const t of GUIDE_TASKS){const r=data.rows[t.id]||{},v=guideValues(t);for(const[k,l,u]of t.fields)lines.push([markText(t.title),markText(l),u,Number.isFinite(r.predicted?.[k])?n(r.predicted[k]):'',r.measured?n(v[k]):'',r.measured&&Number.isFinite(r.predicted?.[k])?n(v[k]-r.predicted[k]):'',r.explanation||'']);}const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='V40_Grundprotokoll_AC.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function draw(){const el=root.querySelector('.guide-visual');if(el)el.innerHTML=visual(task.visual,el.clientWidth);}
 new ResizeObserver(draw).observe(root);render();return {refresh(){render();}};
}
