import {readouts,DEFAULTS} from './lessons.mjs';
export const GUIDE_VERSION=2;
const sin={...DEFAULTS.sinus,shape:'sinus',urms:12,f:50,t:5,showB:false,window:'auto'};
const rl={...DEFAULTS.impedans,kind:'RL',U:12,f:50,R:40,L:95.5,C:150};
const power={...DEFAULTS.effekt,U:230,f:50,P:1150,pf:1,character:'induktiv',Qc:0,Rcable:0};
export const GUIDE_TASKS=[
 {id:'kalibrator',lesson:'sinus',title:'Kontrollera båda mätarna',source:'Kalibrator: 10,00 V RMS sinus, 50 Hz',setup:{...sin,urms:10},fields:[['trms','True RMS-mätare','V'],['avg','Sinuskalibrerad mätare','V']],prompt:'Vilket värde ska varje mätare visa när den ideala kalibratorn ger 10,00 V sinus?',method:'För ren sinus visar båda mätarna effektivvärdet. Här är det kalibratorns 10,00 V.',theory:'matarna',visual:'calibration',explain:'Varför visar båda mätarna samma värde i denna kontroll?',hint:'Ange kurvformen och vilket värde mätarna är avsedda att visa för den.'},
 {id:'grund-period',lesson:'sinus',title:'Läs av periodtiden',source:'Grundkälla: 12,00 V RMS sinus, 50 Hz',setup:sin,fields:[['T','Periodtid T','ms']],prompt:'Hur lång tid tar en hel period vid 50 Hz? Svara i millisekunder.',method:'T = 1/f i sekunder. T = 1 000/f i millisekunder. Exempel: 100 Hz ger 1 000/100 = 10 ms.',theory:'period',visual:'period',explain:'Vilka två punkter i kurvan avgränsar en hel period?',hint:'Beskriv två motsvarande punkter, till exempel två nollpassager i samma riktning.'},
 {id:'grund-topp',lesson:'sinus',title:'Jämför toppvärde och RMS',source:'Grundkälla: 12,00 V RMS sinus, 50 Hz',setup:sin,fields:[['peak','Toppvärde û','V']],prompt:'Multimetern visar 12,00 V RMS. Vilket toppvärde förväntar du dig i kurvan?',method:'För sinus: û = √2 · U. Exempel: 10,00 V RMS ger cirka 14,14 V i topp.',theory:'rms',visual:'peak',explain:'Varför kan multimetern visa 12,00 V samtidigt som kurvan når ett högre värde?',hint:'Använd begreppen effektivvärde och toppvärde. Vilket värde beskriver motsvarande värmeeffekt?'},
 {id:'grund-xl',lesson:'impedans',title:'Beräkna spolens reaktans',source:'RL: 12,00 V RMS, 50 Hz, R = 40 Ω, L = 95,5 mH',setup:rl,fields:[['XL','Reaktans XL','Ω']],prompt:'Hur stor reaktans ger spolen vid 50 Hz? Börja med att omvandla mH till H.',method:'L = 95,5/1 000 = 0,0955 H. XL = 2πfL.',theory:'xl',visual:'rl',explain:'Hur ändras spolens reaktans om frekvensen fördubblas?',hint:'L hålls konstant. Läs hur f ingår i XL = 2πfL.'},
 {id:'grund-z',lesson:'impedans',title:'Beräkna impedansens belopp',source:'RL: R = 40 Ω och XL ≈ 30 Ω vid 50 Hz',setup:rl,fields:[['Z','Impedansens belopp |Z|','Ω']],prompt:'Beräkna kretsens impedans när R = 40 Ω och XL ≈ 30 Ω.',method:'|Z| = √(R² + XL²). Rita R och XL vinkelrätt och beräkna diagonalen.',theory:'z',visual:'triangle',explain:'Varför använder vi inte 40 + 30 för impedansens belopp?',hint:'Beskriv hur resistiv och reaktiv del ligger i diagrammet.'},
 {id:'grund-strom',lesson:'impedans',title:'Jämför strömmen med och utan spole',source:'RL: 12,00 V RMS och |Z| ≈ 50 Ω. Enbart R: 40 Ω.',setup:rl,fields:[['I','Ström i RL-kretsen','A']],prompt:'Beräkna strömmen i RL-kretsen. Med endast resistorn skulle strömmen vara 0,30 A.',method:'I = U/|Z|. Använd hela impedansen för RL-kretsen.',theory:'strom',visual:'rl',explain:'Hur ändras strömmens storlek och fas när spolen läggs till?',hint:'Jämför med 0,30 A. Ange vilken kurva som når sin topp först.'},
 {id:'grund-pf1',lesson:'effekt',title:'Ström vid effektfaktorn 1,00',source:'Enfas: U = 230 V RMS, P = 1 150 W, PF = 1,00',setup:power,fields:[['I','Matningsström I','A']],prompt:'Hur stor ström krävs när effektfaktorn är 1,00?',method:'I = P/(U · PF). Vid PF = 1 blir detta P/U.',theory:'resistiv',visual:'power',explain:'Vad betyder effektfaktorn 1,00 i vår resistiva sinusmodell?',hint:'Beskriv förhållandet mellan P och S samt kurvornas fas.'},
 {id:'grund-pf05',lesson:'effekt',title:'Samma aktiva effekt, lägre effektfaktor',source:'Enfas: U = 230 V RMS, P = 1 150 W, PF = 0,50',setup:{...power,pf:0.5},fields:[['I','Matningsström I','A']],prompt:'U och P är oförändrade. Hur stor ström krävs vid PF = 0,50?',method:'I = P/(U · PF). Skriv hela nämnaren inom parentes.',theory:'strom',visual:'power',explain:'Jämför med PF = 1,00. Vad ändrades och vad var oförändrat?',hint:'Ange de två strömmarna. Skilj matningsström från lastens aktiva effekt.'}
];
export function guideValues(task){return readouts(task.lesson,task.setup);}
export function parseGuideNumber(value){
 const s=String(value).trim().replace(/[−–]/g,'-').replace(',','.');
 return /^[+]?(\d+(\.\d*)?|\.\d+)$/.test(s)?Number(s):NaN;
}
export function guideDifference(task,field,predicted){return guideValues(task)[field]-predicted;}
