/**
 * The real places the town feed's stories happen in. Each is a room or street in the game,
 * with the backdrop tools/render-feed-backdrops.mjs captures from it (`shot`: a room the
 * audit hook enters, or a street camera), and the nouns a story can pick up there.
 *
 * kind: shop, food, bar, work, bath, civic, outdoor. `regulars` are the residents who belong
 * there; anyone else is a visitor. `things` are objects actually in the place, `doing` are
 * verbs phrases that make sense there ("{who} was {doing}"). `activity` is what people do
 * there in a comic: the drinks they may hold (izakaya-serving-visuals.js kinds), how likely
 * they are to (chance) and how likely to be sitting (sit).
 */
export const FEED_PLACES=Object.freeze([
 {id:'sakura',name:'Sakura Shōten',short:'Sakura',kind:'shop',regulars:['Thuan'],
  things:['the drinks fridge','the sale poster by the door','the onigiri shelf','the potted palm','the till','the price gun','the ATM','the biscuit aisle','the staff roster'],
  doing:['restocking the biscuit aisle','taping up the sale poster','arguing with the price gun','counting onigiri','dusting the potted palm','reading the staff roster'],
  activity:{hold:['can','coffee'],chance:.4,sit:0},
  shot:{room:'market'}},
 {id:'sakura-street',name:'outside Sakura Shōten',short:'Sakura',kind:'outdoor',regulars:['Thuan','Vy'],
  things:['the parcel sign','the vending machine','the bus stop sign','the shop awning','the bicycle rack'],
  doing:['waiting for the bus','carrying out a delivery crate','reading the shop window','sheltering under the awning'],
  activity:{hold:['can','coffee'],chance:.7,sit:0},
  shot:{at:[-1,-24],camera:{pos:[3.5,1.7,-21.5],at:[-5.5,2,-27.3]}}},
 {id:'minato',name:'Minato Izakaya',short:'Minato',kind:'bar',regulars:['Thao','Barfly'],
  things:['the bottle keep','the karaoke machine','the pink telephone','the yakitori grill','the red stools','the oden pot','the lantern'],
  doing:['queueing for karaoke','tidying the bottle keep','fanning the yakitori grill','sharing a plate of edamame','writing a name on a bottle tag'],
  activity:{hold:['draft','draft','bottle','sake','awamori'],chance:.95,sit:.65},
  shot:{room:'izakaya',time:1200}},
 {id:'sato-ramen',name:'Sato Ramen',short:'Sato Ramen',kind:'food',regulars:['Mrs Sato'],
  things:['the ticket machine','the stock pot','the red stools','the noodle basket','the chopstick box','the window table for two'],
  doing:['feeding the ticket machine','waiting for a bowl of shoyu ramen','watching the stock pot','slurping noodles','mending something at the window table'],
  activity:{hold:['coffee','can'],chance:.5,sit:.8},
  shot:{room:'ramen'}},
 {id:'books',name:'Front-Row Books',short:'Front-Row Books',kind:'shop',regulars:['Nhung','Reiko'],
  things:['the window seat','the evening paper','the poetry shelf','a paper bookmark slip','the printing bench','Tama the cat'],
  doing:['reading on the window seat','proofreading the evening paper','tucking slips into books','negotiating with Tama the cat'],
  activity:{hold:['coffee'],chance:.35,sit:0},
  shot:{room:'frontrow'}},
 {id:'onsen',name:'Umi-no-yu bathhouse',short:'Umi-no-yu',kind:'bath',regulars:['Mrs Higa','Grandmother Higa'],
  things:['the bandai counter','the coin tray','the milk fridge','the noren curtain','the women’s crimson noren','the men’s indigo noren','the price board','the breaker board behind the bandai','the breaker board','the men’s mirror','the comb sterilizer','the swimwear-zone sign over the rock-bath door','a stack of rental towels','the towel rail by the bath door','the three hair dryers','the massage chair','the straw jar on the milk fridge','the uchiwa rack','the giant Hārī fan','Mrs Higa’s rubber plant','Mrs Higa’s account book','Mrs Higa’s noren pole','the box of extension cords under the bandai','the massage chair’s coin timer','the andon on the bandai','the women’s fluorescent tube','the porch lamp','the stone lantern by the rock bath','the harbour lights across the water','the steam over the rock bath'],
  doing:['paying at the bandai','choosing a bottle of milk','reading the price board','waiting for the bath to cool','resetting a tripped breaker','folding rental towels','drying their hair at the mirror','combing their hair at the men’s mirror','hanging a towel on the rail','fanning themselves with an uchiwa'],
  activity:{hold:['bottle','can'],chance:.6,sit:0},
  shot:{room:'onsen'}},
 {id:'town-hall',name:'the mayor’s office',short:'the town hall',kind:'civic',regulars:['Johansson'],
  things:['the island map','the Merry Moose statue','the flag','the filing cabinet','the visitors’ sofa'],
  doing:['studying the island map','filing a complaint','waiting on the visitors’ sofa','saluting the Merry Moose'],
  activity:{hold:['coffee'],chance:.5,sit:.35},
  shot:{room:'mayor-office'}},
 {id:'harbour',name:'the harbour',short:'the harbour',kind:'outdoor',regulars:['Harbour master','Johansson','Mr Toguchi','Riku','Emi Kado'],
  things:['the ferry gangway','a bollard','the quay lamp','a coil of rope','the tide board','a crate of mackerel'],
  doing:['watching the ferry come in','checking the tide board','coiling rope','counting crates','waiting for the gangway'],
  activity:{hold:['can','coffee'],chance:.5,sit:0},
  shot:{at:[3,-48],camera:{pos:[6,1.8,-47],at:[-4,1,-58]},time:960}},
 {id:'pier',name:'the outer pier',short:'the pier',kind:'outdoor',regulars:['Harbour master','Officer Mori'],
  things:['the end of the pier','a fishing rod','the warning light','a bucket of bait','the sea'],
  doing:['fishing off the pier','watching the sunset','reading the night warning sign','feeding a gull'],
  activity:{hold:['can','draft'],chance:.6,sit:0},
  shot:{at:[-1.6,-56],camera:{pos:[-1.2,1.8,-50],at:[-1.6,1,-64]},time:1080}},
 {id:'park',name:'Harbour Park',short:'the park',kind:'outdoor',regulars:['Vy','Grandmother Higa'],
  things:['the park bench','the raised walk','the banyan tree','a lost umbrella','the drinking fountain'],
  doing:['playing jan-ken-pon','doing homework on the bench','walking the raised path','resting under the banyan tree'],
  activity:{hold:['can','coffee'],chance:.6,sit:.55},
  shot:{at:[12,-23.8],camera:{pos:[8.4,2.6,-23.8],at:[18,1.2,-23.8]}}},
 {id:'garden',name:'Aoba Japanese Garden',short:'the garden',kind:'outdoor',regulars:['Mrs Kinjō'],
  things:['the koi pond','the stepping stones','the stone lantern','the raked gravel','the little bridge'],
  doing:['feeding the koi','crossing the stepping stones','raking the gravel','sitting by the pond'],
  activity:{hold:['coffee'],chance:.3,sit:0},
  shot:{at:[-23.4,40.6],camera:{pos:[-25,2.4,47.5],at:[-23.4,1,40.6]}}},
 {id:'rainflower',name:'Rainflower Lane',short:'Rainflower Lane',kind:'outdoor',regulars:['Mrs Kinjō'],
  things:['the flower buckets','the ice cream counter','a hand-made wreath','the lane’s paper lanterns'],
  doing:['choosing flowers','queueing for ice cream','admiring a wreath','strolling the lane'],
  activity:{hold:['can','coffee'],chance:.5,sit:0},
  shot:{lane:{at:[90,112],cam:[91,125],look:[90,99],height:2.2}}},
]);
export const feedPlace=id=>FEED_PLACES.find(p=>p.id===id);
