from pathlib import Path
import struct,json,io,subprocess,math
import numpy as np
from PIL import Image
import sys
with Path(sys.argv[1]).open('rb') as f:
 f.seek(12);n,_=struct.unpack('<II',f.read(8));doc=json.loads(f.read(n));n,_=struct.unpack('<II',f.read(8));data=f.read(n)
def accessor(i):
 a=doc['accessors'][i];b=doc['bufferViews'][a['bufferView']];dtype=np.dtype({5126:'<f4',5125:'<u4',5123:'<u2',5121:'u1'}[a['componentType']]);dim={'SCALAR':1,'VEC2':2,'VEC3':3,'VEC4':4}[a['type']]
 return np.ndarray((a['count'],dim),dtype=dtype,buffer=data,offset=b.get('byteOffset',0)+a.get('byteOffset',0),strides=(b.get('byteStride',dim*dtype.itemsize),dtype.itemsize)).copy()

# Cross sections at ankle, waist and shoulder height, on a 5 cm grid. The
# opaque building core is a separate rectangle; these cover façade columns.
step=.05;cells=set()
for mesh in doc['meshes']:
 for p in mesh['primitives']:
  if p.get('mode',4)!=4:continue
  mat=doc['materials'][p['material']].get('pbrMetallicRoughness',{})
  if mat.get('baseColorFactor',[1,1,1,1])[3]<.01:continue
  pos=accessor(p['attributes']['POSITION'])[:,[0,2,1]]*np.array([1,1,-1])
  indices=accessor(p['indices']).astype(int).ravel() if 'indices' in p else np.arange(len(pos))
  tri=pos[indices.reshape(-1,3)];tri=tri[(tri[:,:,2].max(1)>-1106.4)&(tri[:,:,2].min(1)<1159.6)&(tri[:,:,0].min(1)<0)&(tri[:,:,0].max(1)>-350)]
  for y in [25,55,82]:
   for t in tri[(tri[:,:,1].min(1)<y)&(tri[:,:,1].max(1)>y)]:
    hit=[]
    for a,b in [(t[0],t[1]),(t[1],t[2]),(t[2],t[0])]:
     if (a[1]<y)!=(b[1]<y):hit.append(a+(b-a)*(y-a[1])/(b[1]-a[1]))
    if len(hit)!=2:continue
    a,b=[np.array([-v[0]*.022-14.16,-v[2]*.022+6.1592]) for v in hit]
    for q in np.linspace(a,b,max(2,int(np.linalg.norm(b-a)/.025)+1)):
     if -13.3<q[0]<-7 and -19.352<q[1]<30.5:cells.add((int(np.floor(q[0]/step)),int(np.floor(q[1]/step))))
rects=[]
while cells:
 x,z=min(cells);xx=x
 while (xx+1,z) in cells:xx+=1
 zz=z
 while all((u,zz+1) in cells for u in range(x,xx+1)):zz+=1
 for u in range(x,xx+1):
  for v in range(z,zz+1):cells.remove((u,v))
 rects.append(dict(x=round((x+xx+1)*step/2,4),z=round((z+zz+1)*step/2,4),w=round((xx-x+1)*step,4),d=round((zz-z+1)*step,4),height=1.8))
Path(sys.argv[2]).write_text('// Measured façade cross sections; generated by tools/frontage-collisions.py.\nexport const FRONTAGE_COLLIDERS='+json.dumps(rects,separators=(',',':'))+';\n')
print('Frontage collision rectangles:',len(rects))
